### ISSUE TITLE
Integrating CLI into UI

### ISSUE THREAD

**Issue by sebvil** [uchicago-cs/chiventure#101]
For this task, all we want to do is figure out how to incorporate the CLI with the ncurses library in order to have a working UI.

**Comment by borjasotomayor** [comment]
Please change the title to say "Integrating" instead of "Merging". Merging has a very specific meaning in Git, and can lead to confusion.

**Comment by sebvil** [comment]
One of the first issues in integrating the CLI with the UI is how to handle printing in the CLI and being able to read commands. CLI was using readline to get the commands. The only thing I could find that integrated readline with ncurses was the following: https://github.com/ulfalizer/readline-and-ncurses/blob/master/rlncurses.c.

Another simpler option could be using the ncurses `wgetstr` function. Without calling the `noecho` function, which prevents typed characters to be automatically displayed, the following code could be use to run the CLI:
```
//game loop
while ((ch = wgetch(cli->w)) != 4) {
        char str[80];
        char test[80];
        test[0] = ch;
        test[1] = '\0';
        wgetstr(cli->w, str);
        strcat(test, str);
        / * more code */
}
```
This would store the user input in test.
Some drawbacks of this method would be that we would not be able to handle any commands until enter is pressed. For example, if we want to exit the game or if we want to use Alt+key combinations to switch windows or other functionality,  but the user has started typing a command to the CLI, we would have to wait  until the user presses enter to handle game exiting or the Alt combinations. Other issues are that the left arrow acts as a backspace, and the first character would not be part of the string obtained by wgetstr, which is why it must be manually appended. This also makes it so that that character cannot be deleted from the screen.

**Comment by sebvil** [comment]
>  the first character would not be part of the string obtained by wgetstr, which is why it must be manually appended. This also makes it so that that character cannot be deleted from the screen.

Figured out how to solve it. Calling `ungetch(ch)` right before `wgetstr` will return ch to the buffer, so `wgetstr` will read that character first.

**Comment by sebvil** [comment]
So there is two ways we can get a string: the **wgetstr** function and the **wegetnstr** function. The only difference is the second one allows us to set a limit as to how many characters can be typed. I think this might be a better way to go, since typing more characters than what our string can hold will cause our code to crash.

**Comment by sebvil** [comment]
The print_cli function now passes the string to the CLI functions (cmd_from_string, do_cmd). Right now CLI prints output to stdout, so running program normally you won't be able to see any output. However, it can be verified that the commands are processed correctly by redirecting test_ui output to a file (test_ui is in ui/examples, can be done by calling `make examples/test_ui` for the ui root folder). The UI will not be shown, but typing "HELP" and then Ctrl+D should correctly save the help menu in the file chosen for redirection.

**Comment by sebvil** [comment]
The rest of this task is now dependent on #161 as we need to give CLI our context structs so they have access to the windows to print output there, or switch them if necessary.

**Comment by sebvil** [comment]
Based on a discussion with @ecoble  yesterday, I have created functions that will allow the CLI to easily change stuff about the UI using the commands has table. Specifically, I added a function that allows for toggling the map window, one that allows to switch the position of the CLI, and one that allows to print to the CLI.

**Comment by sebvil** [comment]
For testing purposes, I prevented some stuff from the coordinates and maps from running, as these were causing errors. Once those bugs are fixed I will fix those here too.

**Comment by ecoble** [comment]
UPDATE: Now that the context struct is through, CLI has updated their functions and hashtable to use this struct in place of a game struct (this change not yet in master). We have now updated all of our print functions to print to the UI window, and we have added map and switch to the hashtable

Note: In order to to add map and switch, I had to add a dummy parameter of type char *, because the hashtable requires commands to map to an operation function with parameters of type char * and chiventure_ctx_t. Anywhere switch or map is used, NULL can be passed in as the first parameter. This is not a great solution but it is working for now

**Comment by ecoble** [comment]
CLOSING STATEMENT: UI and CLI are now preliminarily integrated, it has been difficult to test functions since the backend of most of the functions has not been set up and results in a seg fault. CLI now makes use of chiventure and ui context struct, and prints to UIs window. We have also set up "MAP" and "SWITCH" in our hashtable, so the user can show the map or switch the position of the cli and the main window. UI is handling getting user input and passes the input to CLI to parse and process from there.

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
