### ISSUE TITLE
Create Sandbox Example through VirtualMachine

### ISSUE THREAD

**Issue by jiguba** [uchicago-cs/chiventure#1019]
The purpose of this issue is to play a sound file through a Virtual Machine that contains the Linux environment. This work will lay the foundation for playing sound and executing sound files in chiventure.

**Comment by jiguba** [comment]
May 18: Installing Ubuntu 20.04 through Oracle Virtual Box. Will update upon successful installation of Linux environment on Virtual Box.

**Comment by Imagineham** [comment]
May 18: After having installed virtual box, we followed the instructions on this [page](https://howto.cs.uchicago.edu/vm:install) to install the Uchicago cs linux image. The image can be found [here](https://howto.cs.uchicago.edu/vm:index). Upon installing the UC CS linux, we followed the steps on this [page](https://soundprogramming.net/programming/tutorial-using-sdl2-and-sdl_mixer-to-play-samples/). We were successfully able to install sdl and play the main.cpp program.

**Comment by Imagineham** [comment]
May 18: While tech staff works on getting sound to play on the CSIL machines, we've been trying to confirm the issue as being hardware related. Thus, using the UC CS linux image on virtual box we ran this command:

student@cs-vm:~$ aplay --list-devices
**** List of PLAYBACK Hardware Devices ****
card 0: I82801AAICH [Intel 82801AA-ICH], device 0: Intel ICH [Intel 82801AA-ICH]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
  
  Since we received a valid response, we can confirm that there is a bug that occurs only when connecting to the audio drivers with the CSIL machines through either ssh or virtualMachine.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great work getting this sandbox program working, I know it was tough troubleshooting all those issues, you did an excellent job!
