### ISSUE TITLE
Finish implementing and testing xp regression function

### ISSUE THREAD

**Issue by m-ghosal** [uchicago-cs/chiventure#1023]
Assignees: Maya 
team: skilltrees

**Comment by m-ghosal** [comment]
Created a branch called regression, where I'm working on incorporating an xp regression function

**Comment by m-ghosal** [comment]
Figured out a more efficient way to increase the minimum amt of xp points required to level up - instead of having a separate regression function, I incorporated the exponential increment of the min_xp variable within an already defined skill_level_up function, which was previously only used to increment the levels. Now, the function takes the same parameter (a skill_t struct), and changes both the level and the min_xp field of that struct while leveling up. 
I also edited the header file (skill.h) to incorporate this change.

**Comment by m-ghosal** [comment]
Wrote and commented out tests for the skill_level_up function in the skill_test.c file

**Comment by firatciftci** [comment]
Issue Score: ✔️

Comments:
Good work! I have two things to comment on:
- The issue did not include a descriptive summary (see https://uchicago-cs.github.io/cmsc22000/project/policies.html#tasks-issues for more details and concrete examples)
- When an issue is done, you should include a final comment summarizing what was done, and why the issue is being closed.
