### ISSUE TITLE
Integrating Player Class/Item Interactions with Battle Logic

### ISSUE THREAD

**Issue by ideclue** [uchicago-cs/chiventure#1024]
In Issue #959, player classes and items were given more detailed interactions through the addition of multipliers, which allow certain player classes to use an item more (>1.0x) proficiently, less (<1.0x) proficiently, or be completely restricted (0x) from using an item.

Although this code is functional in the player class module, integration with other modules of chiventure is necessary in order for the multipliers to have an effect on game flow. The most pertinent use of items currently exists in the battle module, so my goal is to successfully integrate these interactions with pre-existing code in this module.

**Comment by ideclue** [comment]
- Following a review of relevant code and documentation as well as discussions with the battle team, I've decided that the most effective place to begin facilitating this integration is in `battle_logic.c`, which currently contains the code that governs item interactions in a battle. 

- However, this code uses a `battle_item_t` struct that doesn't currently include player class interactions. Thus, ensuring that `battle_item_t` supports player class interactions will be the first necessary step to complete the original goal outlined above

**Comment by Vincent-Zhang4135** [comment]
Katie, Jonathan, and I met synchronously to discuss how to integrate playerclass/item interaction in battle_logic.c. We noted that there is a `combatant_t` type that contains a `class_t` type, which determines the playerclass of a player. We realized that this is the link between how various player classes can have various battle logic interaction.

In battle_logic.c, there is a `consume_battle_item` function that apply the stat based on the combatant, which will include the player class type. We decided that we will implement switches that will apply stat changes based on the class type of the combatant that is fed in as a parameter

**Comment by Vincent-Zhang4135** [comment]
We have come to the conclusion that we are going to split `apply_stat_changes()` into two functions, one specializing in items (`apply_item_stat_changes()`) and one in movements (`apply_item_stat_changes()`). We are not touching movements for this issue, but we realized that for changing item effects based on class, we need to pass down the combatant's class and also the full battle_item_t struct as opposed to just the changes in the item struct, because the new function `apply_item_stat_changes()` will need to access both the item's id and its associated changes.

**Comment by jroven** [comment]
We have successfully applied one multiplier on the stat changes; specifically, warriors get twice the physical attack bonus when using the consumable Strength Up. We are in the process of coming up with more combinations and will implement them soon.

**Comment by Vincent-Zhang4135** [comment]
Following Jonathans comment, we have created a separate issue for developing a wiki documentation to detail what each player + battle-item should do to the stats. This is linked on #1612. We will use these specifications to implement further combinations, and so this will include warrior and wizard.

**Comment by jroven** [comment]
The implementation broke some of the tests in test_battle_logic.c because the tests were not designed for this feature. I am commenting out the five tests and creating a new issue #1657 to implement working tests.

**Comment by jroven** [comment]
I have implemented the eight multipliers created in issue #1612 into the `class_multipliers()` function in battle_logic.c. Integrated classes include warrior, wizard, bard, and rogue. Integrated items include the consumables strength up, defense up, elixir of life, and healing potion. This issue is ready for a pull request.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
