### ISSUE TITLE
Create a Hashtable to map commands to functions

### ISSUE THREAD

**Issue by ecoble** [uchicago-cs/chiventure#103]
Make a hashtable that maps commands to their functions to avoid having large switch statement. Communicate with action management before implementing this, because we can potentially integrate this with the enums and functions that action management already has. 

//Please add more description here

Primary goals for this task are:
Implementing table using uthash.
Rewriting previous code to work with table.
Creating interface to import lists of actions including synonyms, and put them in command.
Secondary stage of this is to integrate this with more commands, from other groups.

**Comment by Gestalt-R** [comment]
Alright: In my commit to my branch above, I have:
Implemented the data structure
Created and used tests
Created commented out headers for when we do other stuff. 

I invite everyone to take a look at my branch "cli/hashtable". It is not quite ready to push to dev yet, as I want to wait until we get our current pull request filled, and some pieces of action management code done.

**Comment by Gestalt-R** [comment]
For some more details on this implementation:
Functions and references have been provided in the new lookup module, containing functions to help with lookup.

**Comment by Gestalt-R** [comment]
I have been informed that global variables are beyond the scope of this project (see what I did there?). 

The people responsible for implementing them as mission critical parts of the table have not been sacked, because they already put so much care into the project, and fixed it, anyways.

The new commit fixes this, and also implements the hash table inside the cmd module. It made sense to be there, and also, it wouldn't compile where it was because of mutual inclusion.

Tests work as expected, and basic game-integration has been added. This issue is about ready to be pushed to dev-not master yet though, as integration with action management has not been implemented! Pull request being made, with, I suppose, people who want it reviewing.

Lastly, the function implements a placeholder for gamestate. It does this with the handy-dandy placeholder.h file, in the include directory! Please, get rid of it when you can, and replace it with the proper location for the game_t typedef. Besides that, it should be good to go.

**Comment by Gestalt-R** [comment]
This isn't done quite yet, fyi. Need to integrate Borja's new context struct.

**Comment by ecoble** [comment]
UPDATE: As we've begun integration with action management, we've filled out the add_action_entries that loops through action management's list of actions and creates an entry for each one. We have also fixed some type issues, and changed the type of the operation function to include a lookup table as a parameter, since the action operations require a lookup table.

**Comment by Gestalt-R** [comment]
Alrighty, we are done.

The functions are all operational except for the context struct, which will be done soon.

**Comment by ecoble** [comment]
CLOSING STATEMENT: The hashtable is does all its expected functions, it maps a command to an operation function and an action struct. Actions from specified by action management (e.g. take, put, eat) are added iteratively based on a list of actions. Other actions (e.g. help, quit) are each added on their own. This is not yet integrated with the new context struct, but we are closing this issue as the hashtable is function and we will open a new issue for integrating with the context struct in the next sprint.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Great work!
