### ISSUE TITLE
Update class_prefabs.c with functions to create default weapons and prefabricated skilltrees 

### ISSUE THREAD

**Issue by maxsamengo** [uchicago-cs/chiventure#1066]
Currently, `class_prefabs/c` contains two main functions: `class_prefab_new()` and `class_prefab_add_skills()`. The former function creates a new prefab class with a short and long description, and base stats. The latter function takes in a class, checks if it is one of the prefab classes, and adds a skill tree, although it doesn't actually add any skill trees yet. I would like to:
 - Complete the `class_prefab_add_skills()` function:
     - Create skilltrees for the prefab classes 
     - Document them on the wiki
     - Add these skilltrees into the code
     - Add tests
 - Add a `class_prefab_add_items()` function which adds some default items to each class (e.g. a wand for the wizard, a rusty sword for the warrior)
     - With the same steps as above
 - Finally, I would like to separate the existing `class_prefab_new()` function so that it is possible to create classes which only contain a short and long description. 
      - Similarly, I would like to create a function where the dev can specify which fields of the prefab class they would like filled out, which will be more relevant as there are more ways to prefab classes (i.e. prefab items)

**Comment by arya32hub** [comment]
will require to add an empty inventory using the code:

`skill_inventory_t* inventory_new(unsigned int max_active,
                                 unsigned int `max_passive); `

add individual skills to the inventory using:
`int inventory_skill_add(skill_inventory_t* inventory, skill_t* skill);`

**Comment by KabirDubey** [comment]
In the first part of sprint 3, we designed a template to complete the TODO comments in the class_prefabs_add_skills() function. Our plan was to use the skilltree_new function, assign a TID, and implement the function around the following assignment of a skilltree, 

`class->skilltree = skill_tree_new(tid_t tid, char* name, unsigned int num_nodes)`

However, the playerclass team reached out to us and we jointly concluded that we were working on the same thing. See issue/PR #1408. We met to resolve the confusion and concluded the following:

1. The playerclass team took a similar approach to our plans. An overview of their perspective can be found at #1242. After their pull request is approved, we will load skill trees to these classes, write tests, and update playerclass' wiki page* for the following classes:
-druid
-elementalist
-sorceror
-knight
* [This](https://github.com/uchicago-cs/chiventure/wiki/Player-Class-~-Example-Stats-and-Abilities) is the wiki page playerclass has been updating. Note the difference with [this one](https://github.com/uchicago-cs/chiventure/wiki/Player-Class-~-Prefabricated-Classes).
2. The final two bullet points in the initial post for this issue are best reserved for the playerclass team, not the skilltrees team because they do not depend on the skill trees as much as the first bullet point does. A new backlog issue should be created accordingly. 
3. Clarified the NULL parameter mentioned in #1371. It refers to [complex skills](https://github.com/uchicago-cs/chiventure/wiki/Skill-Trees-~-Integrating-complex-skill-(combined,-random,-sequential,-etc.)-implementation).

**Comment by KabirDubey** [comment]
Created 1066-prefabs-skills branch. Worked with Arya to implement classes and tests for druid, elementalist, knight, and sorceror classes. 

Ran into a seg fault along the way. Future teams should take care to put commas in the initialization of the `DEFAULT_CLASS_NAMES` array in lines 20-31 of `class_prefabs.c`. 

31 out of 31 tests pass.

All that remains is to update the wiki page.

**Comment by KabirDubey** [comment]
[Wiki page has been updated](https://github.com/uchicago-cs/chiventure/wiki/Player-Class-~-Example-Stats-and-Abilities).

**Comment by KabirDubey** [comment]
Merged 1066-prefabs-skills with dev.

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Great work on this issue! The comments documenting coordination with the playerclass team were very detailed.
