### ISSUE TITLE
Refactor tests regarding tree implementation in quests

### ISSUE THREAD

**Issue by gabigarc03** [uchicago-cs/chiventure#1078]
The current quest tests are configured for the achievement linked list and need to be refactored to use achievement non-binary trees instead.

**Comment by gabigarc03** [comment]
See more in #957 - I have refactored all existing `quests_state` tests to use trees instead of linked lists but have not added new information to them to test them further (e.g. adding multiple achievements to a tree).

**Comment by gabigarc03** [comment]
All quest tests have been refactored to use achievement non-binary trees and merged into dev as seen in PR #1080.

**Comment by lilyehsani** [comment]
Issue Score: ✔️+

Comments:
Great work overall! I have two comments:
- The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies.html#tasks-issues for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
- For a task of this size, we would've expected to see more status updates and/or status updates that were more detailed.
