### ISSUE TITLE
Implement a basic REPL interpreter

### ISSUE THREAD

**Issue by borjasotomayor** [uchicago-cs/chiventure#11]
Implement a simple module that run a REPL loop to accept commands for chiventure. It won't actually do anything with the commands just yet.

As part of this, we will look into existing libraries for implementing REPL interpreters.

**Comment by efraimdahl** [comment]
On the branch cli_team I just added a very simple interpreter that supports two functions: quit and help. It also includes an example data structure for commands.

**Comment by borjasotomayor** [comment]
Following up on the short discussion after today's lecture, I am very hesitant to include code that is lifted from CS 152 and which may prove inadequate in the long run. In fact, Dr.Shaw specifically warns against this (in https://github.com/uchicago-cs/chiventure/blob/cli_team/cli/cli.c#L86-L90):

```
/* A note to coders who have read this code with interest:
 * one typically doesn't reinvent the wheel to write a shell
 * from scratch like you see here. For more information, please
 * investigate the Command Line Editor Library (libedit). -ams
 */
```

You should really look into [Readline](https://en.wikipedia.org/wiki/GNU_Readline), [libedit](https://thrysoee.dk/editline/), and similar libraries that will do the heavy lifting of reading input in a command-line interface.

**Comment by borjasotomayor** [comment]
Also, please make sure you follow the directory conventions described here: https://github.com/uchicago-cs/chiventure/blob/master/Makefile#L14-L23 Your code should live in the `src/cli` directory and should produce a library, not an executable. If you want to produce a sample executable, then the right home for it is `src/cli/examples` (see `src/libobj` for an example of this)

**Comment by efraimdahl** [comment]
Update: 
Basic REPL implemented using readline GNU, now potentially supports autocomplete and history (not tested). 
NEW ISSUE: When compiling cli (make cli) it throws a bunch of warning from cmd.c, so I would suggest working on integrating the new command module.

**Comment by Tianlel** [comment]
Added function that supports printing out the history of valid commands (using GNU history)

**Comment by dbarer** [comment]
**Summary of Research on various REPLS**
Both [libedit](https://thrysoee.dk/editline/) and [readline](https://tiswww.case.edu/php/chet/readline/rltop.html) are well-supported libraries that are commonly used. 
Each supports basic cli functionality such as auto-complete, history, and editing.
Readline's documentation is much easier to follow, which is the main reason why we chose to use it for this initial REPL. 

Apparently, some people have a strong preference for one over the other, due to license types, and it might make sense to allow our game developer to choose which library they prefer.

Outside of these two major libraries, we looked into one called [linenoise](https://github.com/antirez/linenoise), which focuses on providing a more streamlined version of these 2 libraries. In addition to the basic functions, it also includes a feature called "hints" similar to auto-complete that suggests commands to follow. It's main benefit however, is that it is a much lighter package, with 1,000 lines of code instead of the 20,000 in readline. However, the documentation for it is much more sporadic. But everyone on stackoverflow recommends it. 

I don't think there is a right or wrong choice for this decision, as either one will create a working CLI. The main question is whether we see any value in the hints function of linenoise or if the standard functionality and increased documentation of readline is sufficient and beneficial.

**Comment by borjasotomayor** [comment]
Quick note on "[allowing] our game developer to choose which library they prefer". This is not really practical, as a game author (who will only be writing a WDL file) is unlikely to care about what library is being used to implement the CLI. i.e., you should choose just one library, instead of trying to support multiple libraries and giving end-users a choice of which one should be used.

Regarding licenses, this is something we will likely discuss in class at some point. GNU Readline is licensed under the [GPL](https://en.wikipedia.org/wiki/GNU_General_Public_License), a [copyleft](https://en.wikipedia.org/wiki/Copyleft) license, which means that including any code from Readline in our project requires us to license chiventure with a GPL license. However, we should be fine as long as we only *link* with the Readline library (see https://en.wikipedia.org/wiki/GPL_linking_exception)

**Comment by Tianlel** [comment]
Update:
Our REPL interpreter now supports parsing commands.

Overview of supported actions:
HELP - print out a list of commands
QUIT - exit loop
HIST - print out the history of valid commands
Game actions (GIVE/TAKE/LOOK X TO/WITH/IN Y) - print out the command input

**Comment by Tianlel** [comment]
@borjasotomayor @lydiafilipe could we close this issue now?

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Great work! We gave the benefit of the doubt and interpreted your final update as your closing statement, but in the future please make this more clear as a closing statement.
