### ISSUE TITLE
Sound: Add Sound to Chiventure through Virtual Machine

### ISSUE THREAD

**Issue by jiguba** [uchicago-cs/chiventure#1130]
The purpose of this task is to attempt to add sound to Chiventure through the virtual machine. This is so that expectedly, when the game loads, there will be sound that comes out. this issue is incredibly general because there are so many aspects to the whole game and we don't know which aspect to which sound can be incorporated. 

Assignees: Victor, Jake, Rhea

**Comment by jiguba** [comment]
A demo program was created that creates an output file that opens a window a plays background music on an infinite loop. This would be an ideal audio program to place in the beginning when the Chiventure Logo is displayed. Research was conducted by looking through the chiventure UI to see possible areas where we can implement this audio program.

**Comment by sangerr** [comment]
Another idea of how to add sound is to incorporate sound effects when moving between rooms or picking up objects. We also will want to include background music that match the vibes of certain rooms.

**Comment by sangerr** [comment]
With the new text to speech structs, all conversations between an NPC and a player can have sound that is playing what the npc is saying out loud. The text to speech feature could also be incorporated when entering different rooms or during other interactions.

**Comment by sangerr** [comment]
Closing Statement: This issue ended up being more of an exploration into the ways that we could integrate sound across chiventure, rather than implementing these different features. Through our demo, we showed how text to speech could be used in a conversation between a NPC and player in a sample game on VM. We hope that future sound teams can further explore this area and work to actually incorporate sound throughout chiventure via VM.
