### ISSUE TITLE
Connect Map Visuals with coordinate hash modules

### ISSUE THREAD

**Issue by omorkved** [uchicago-cs/chiventure#114]
We have graphics that display arbitrary rooms, and we have a method of assigning coordinates--time to connect them. Will require refactoring some fcns on both sides.

**Comment by omorkved** [comment]
(Related to #46 and #47 so check those for further discussion)

**Comment by omorkved** [comment]
This task was delayed while we waited on PR's going through to master. We have identified the specifics of this task as follows:

The current method of iterating over the rooms involves array, but now we must iterated over the hash map instead. @Sshatzkin will explain how he is currently iterating and any issues we run into when integrating. This involves using the coordinate keys to find the relevent room pointers.  We will also need to decide upon a mehtod of drawing the map: Will we "draw" the entire map every time in a pad (ncurses struct), or will we create a function to go out, say, five rooms in every direction from the current room and only draw those rooms? 
Finally, there is some cross-over between this task and #131 because both my code and Sam's code specify redundant coord structs, and both will rely upon game state integration in #131

**Comment by omorkved** [comment]
Snag in the road-- we spent like an hour trying to figure out a bug in make. We think it's a problem with circular includes. Sent error msg into slack. E
Error showing: unknown type name "map_t"
however, map_t is defined in our header map.h, which is included on a lot of things...we've been double checking #ifndef 's and the ordering of include statements but can't seem to find the problem

**Comment by Sshatzkin** [comment]
When constructing the map functions the first time, there were some assumptions made about inputs that have since changed, so the functions required a good deal of updating.

Initially, the rooms were stored as an array of pointers to rooms, and drawing the rooms involved iterating over this array. A pointer to this array was stored in the map struct alongside an int that tracks the number of rooms stored. 
Coordinates to rooms were assumed to be stored inside the room struct but this is also no longer the case.

In the final version of the coordinate calculation code, the rooms and coordinates are stored in a hashmap that uses a coordinate struct as a key. All of the map functions had to be updated in some way to accommodate the new context struct or change the iteration method to iterate over a hashmap instead of an array.

The last big changed assumption is that the exits from each room will be stored in the room struct. In reality, we are now getting room exits from rooms using a call to a gamestate function  room_t *find_room_from_dir(room_t curr, char direction) specified in issue #151 . This allows us to determine if leaving a room via a certain direction is allowed and to draw an exit there.

**Comment by omorkved** [comment]
Addressing seg fault issues. Explanation of a fix I made in DFS.c: Right now, chiventure_ctx_new() creates a new game using game_new() and then sends this game into ui_ctx_new(), which calls on create_valid_map() using this game... the problem was game_new() was leaving the curr_room field as NULL -- and create_valid_map() needs to assert that this field is _not_ null. Made a temporary fix to have the create_valid_map() fcn just return FAILURE when given a game with no rooms. This will eventually turn into an assert statement--but for now, since we are just hard-coding a sample coord hash in our map_examples.c, we need this function to just safely exit and not throw seg faults.
Once game_new() is updated by Game State, there should never be a situation where create_valid_map() is called by a game struct that has no rooms (and if so, the assertion statement would catch it and abort)

Still fixing a few seg faults

**Comment by Sshatzkin** [comment]
The map and coordinate modules have been fully integrated.  The map is now drawn from a hash map of rooms stored with coordinate structs as keys which will be the output of our team's coordinate assigning algorithm.  Both the hash map and map drawing functions have now been transitioned from using our own, unique, test room structs, to using game-state's room struct. Additionally, all of the functions that may need to interact with map struct data or hash map data now take a chiventure_ctx as an argument which greatly simplifies the process of passing information.

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
