### ISSUE TITLE
Refactor the kind functions using game state structs

### ISSUE THREAD

**Issue by yoonsjeong** [uchicago-cs/chiventure#115]
Refactoring KIND 1 function: Game state has an "item_t struct" which is what we used in our dummy function, so implementation shouldn't be too difficult. We do have to figure out how "attributes" work and how we would use Game State functions to alter the attributes depending on the item given.

Refactoring KIND 2 function: It appears that in place of the "direction_t struct" we used in our dummy function, game state has their own struct called the "path_t struct" -- we will assign one person to a function that takes this as an input. Something to note: we now have the function "ENTER" as well as "GO" -- we should have game state have a thing that tells you if you can "ENTER" a path versus "GO" a path. (So for example, you could ENTER a house, but you can't ENTER east. You could GO east but not GO house.)

Refactoring KIND 5 to be the KIND 3 function: Tentatively, we are removing KINDs 3 and 4, since NPCs don't (at the moment) seem to be supported by either WDL or Game State. Either way we need to refactor the KIND 5 function (ACTION item item) so that it uses the Game State structs.

**Comment by lucyyutingli** [comment]
As per @yoonsjeong discussing with Borja and Mark, we'll be taking out the synonyms, as they don't seem necessary right now and are only slowing down the implementation of the actions. Mostly through complicating the get_supported_actions function, and they aren't critical at the moment.

**Comment by yoonsjeong** [comment]
I have made some superficial edits replacing the variable names to match the ones provided by game state, but we still need to rewrite the functions for KIND 1 through 3. Let's begin assigning these tasks in the following manner:
- person 1: refactor KIND 1 function
- person 2: refactor KIND 2 function
- person 3: refactor KIND 3 function

**Comment by MTUC08** [comment]
Plan of action: 
1. Switch variables to game state variables
2. Refactor functions to return a string rather than SUCCESS/FAIL
3. Refactor functions to incorporate actual game state functions
    1. Check for validity of the action (presumably in the item-> supported actions)
    2. Check for correctness
4. Tests

**Comment by lucyyutingli** [comment]
A list of functions we need but I haven't seen them implemented yet, whether named the same or not, some I'm just unsure if they're intended to do the same thing as dummy functions we created:

actionmanagement.c:
- toggle_condition (I believe it would be one of the attribute functions but not sure which one, gonna ask game state about it)
- get_long_desc
- remove_inventory_item
- take_object/add_inventory_item (I'm unclear if this is the same as game_state's "add_item_to_player" function, seems take_object would be changed to do something with attributes)
- remove_inventory_item
- player_move (unclear if this is the same as game_state's "move_room" function)

I'm going to inquire with them on Slack about these, to see if they're planning on adding anything new.

**Comment by ellychoi** [comment]
Our first priority is to integrate game state's structs into our code and get rid of the game.h placeholder folder we have.

**Comment by MTUC08** [comment]
Currently in the process of allowing our functions to return strings to CLI rather than printing into stderr

**Comment by MTUC08** [comment]
@lucyyutingli @ellychoi @SnowballAntrobus I've just completed 2 on the above plan of action, and PR #165 completed 1. Since we still need to hear back from game state about which functions they're gonna do, and from the class discussion on Monday, implementing the functions isn't terribly important at least for this sprint to get a prototype up and running, I think we can go ahead and start tests (i.e. 4 on the plan of action) until we hear back. To do that, should we open up mini issues (one for each test category) or just feature branches?

**Comment by lucyyutingli** [comment]
I think one feature branch is fine, we don’t want to have to many branches to PR. We could probably be fine with one test file for actionmanagement.c if I remember correctly

**Comment by lucyyutingli** [comment]
@MTUC08 I know you did some work on this, do we only have tests left? I know we're still waiting on game-state to update their things but I was just wondering what I needed to do. I just wanted to comment it here so it didn't get lost in Slack.

**Comment by MTUC08** [comment]
@lucyyutingli Yeah, we're just waiting on game state to implement #172 so we can add a final check within our action functions, but aside from that, and the tests to check for that, we just have to do the other tests.

**Comment by MTUC08** [comment]
Closing Comments:
For Sprint 3, our kind functions will simply check if an action is the correct kind, and whether it can be used on an item. If these checks pass, we return a statement to CLI indicating that the action has been requested. Otherwise, we return some error statement. This is enough to get a basic prototype up and running. 
Going forward, Sprint 4 will include using game_state functions to check for conditions. i.e. are the correct conditions satisfied, is the item in the room, is the item in inventory, etc. and deal with the consequences of an action, i.e. adding/removing an item from inventory, moving a player to a different room, etc.

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
