### ISSUE TITLE
Add functionality to delete one or all quests from a hash table

### ISSUE THREAD

**Issue by gabigarc03** [uchicago-cs/chiventure#1164]
Quests are partially implemented in the game state. However, the hash table isn't super manipulable - quests can be added, but they can't be removed. See the [current implementation wiki](https://github.com/uchicago-cs/chiventure/wiki/Quests-~-Current-Implementation) for more details.

**Comment by jakeziqiwei** [comment]
Elizabeth and I worked on this issue for sprint 1. Below is a summary of how it was implemented and how we went about it. 

We started off with reading about the chiventure quest structs and familiarizing ourselves with the uthash library.  We used this documentation https://troydhanson.github.io/uthash/userguide.html#_delete_item to understand as well implementing how to delete quest. 

We wrote a function that takes in a quest ID, quest map, and a boolean int indicator(which would tell us if they want to delete all or just 1 quest). It uses Hash_itr for deleting all quests and frees all deleted quests. 

A possible issue/task that comes from this is how to link this with other parts of chiventure(which is on the wishlist).

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work! One minor comment though: your issue did not include any status updates between the opening of the issue and the closing of the issue (and this issue was not small enough to justify having no status updates at all). If you make any intermediate progress before finishing the task, then it should be documented on the GitHub issue via a comment. But besides that great job!
