### ISSUE TITLE
Research and Update NPC Integration Documentation

### ISSUE THREAD

**Issue by srydbergcox** [uchicago-cs/chiventure#1167]
Review the state of NPC integration with CLI, WDL, Battles, Player Class, Skill Trees, and Open World. Deliverables will be updates to existing documentation/creating wishlists.  
Note: started: CLI, WDL, Battle; needs work: Player Class, Skill Trees, Open World

**Comment by srydbergcox** [comment]
After reviewing the documentation concerning NPC integration with Open World, it seems that a significant road block is that the `npcs_in_room` and `room` struct are not fully compatible with NPCs. Specifically, the room struct needs to be able to hold a list of NPCs currently in that room. Also, there are issues regarding room-to-room movement when the rooms do not share a `room-tag`. Fixing these issues with NPCs and the room struct are good candidate issues to pursue in future sprints as it would allow us to move forward with NPC integration into Open World.

**Comment by srydbergcox** [comment]
WDL currently supports loading in NPC inventory, actions, and dialogue. It still needs integration with NPC classes, battles, and movement. While these do align with other potential things that we may be integrating this quarter, I do not believe that there is a WDL team this quarter which may pose challenges. If they are simple implementations that can be completed then we may be able to pursue this further.

**Comment by srydbergcox** [comment]
According to a note in the [NPC - Design and Planning wiki](https://github.com/uchicago-cs/chiventure/wiki/NPC-~-Design-and-Planning#integration-of-NPC-module), the CLI integration for dialogue has been complete. This integration included adding in a new conversation mode to facilitate the parsing of user input during dialogue. There may be ways to expand on this mode system in other situations, such as battle mode. Because of this, if expanding on modes is viable, integration with CLI offers more opportunity for experience with software design as existing documentation/planning for this is somewhat limited to dialogue.

**Comment by emilybae1705** [comment]
**Battle Integration**:

1. dependencies: 
- rpg-battle: specify the appropriate levels of players an NPC will combat with and the types of NPCs that will engage in battle (see below for more information)
- action-management: types of actions both a player and an NPC can take during combat, show_inventory feature to check items such as weapons, heal, etc. left in an inventory during combat
- CLI: after a player has defeated an npc, show_inventory on the command line so that the player can choose what items to pick up

2. wishlist:
- enemy level: 1) explicit range of levels of players that can fight an NPC with a given xp level or 2) set an NPC xp margin such that if a player's xp level is within it, they can fight the NPC
- types of NPCs who will engage in combat: 1) hostile/conditional friendly/friendly 2) just hostile/not hostile and not hostile battles if provoked -> update hostility enum struct accordingly
- update npc_battle_t struct to include more specific stats such as special powers, accuracy, critical damage, etc.
- incorporate temporary stat change (talk to battles team about how to implement this feature)
- support for more moves and have temporary stat changes allow players to have access to certain items and moves (ex. a player/NPC gets a heal item and can create a "protection bubble" around them during combat)
- possibly integrate inventory information specific to battles such as weapons, heal items to npc_battle_t struct
- different hostility level, surrender level, will_fight levels depending on the battle and the opponent class

**Comment by emilybae1705** [comment]
This issue is complete as Sam and I both researched documentation of NPC integration with Battle, Open World, WDL, and CLI and developed the previous year's wishlist to highlight key features that we feel should be a part of the game engine. There are some bugs in the Open World integration implementation and the CLI integration could be developed to include features other than dialogue-related ones. However, Sam and I decided to focus on Battle Integration as it has the highest potential for development and there are many new, exciting features (NPC types, temporary stat change, etc.) that could be added according to last year's wishlist. To this end, we will primarily collaborate with the RPG-Battles team about what features they want to start working on and construct a design document accordingly. During the all-hands meeting on 04/25/22, we also heard that the Open World team wants to collaborate with us so in the future, we will talk to the RPG-Open World for a detailed plan.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work! Take care not to close an issue before it is done. The issue was closed and reopened before any updates had been made.
