### ISSUE TITLE
sound: Identify what needs to be done to integrate sound into Chiventure

### ISSUE THREAD

**Issue by jwschroeder21** [uchicago-cs/chiventure#1171]
members: (documentation) Jason, Victor

**Comment by jiaoboxuan** [comment]
Previous backlogs: Implement `play/load` sound function: Play sound within `src/sound/sound.c` appears to be working, but the `sound_init()` function does not incorporate the given variables correctly. This doesn’t seem to be an issue when playing a sound, so perhaps `sound_init()` is unnecessary. Additionally, to play the sound we are able to use `SDL_OpenAudioDevice()`, `SDL_QueueAudio()`, `SDL_delay()` functionally while also ending and closing the sound file with `SDL_CloseAudioDevice()`, `SDL_FreeWAV()`, and `SDL_Quit()`.

Sounds about right that we could improve on these functions before putting them into `chiventure`, because from the documentation, it could be seen that sound development is still quite preliminary. Upcoming sprint, let's get these implemented first, I figure so?

**Comment by jiaoboxuan** [comment]
Previous team also stated that there is a lot of compiler errors around. So it is possible that we have to refactor the modules for a little bit...

**Comment by JaStarbuck** [comment]
"The initial goal was to implement play sound functions. Currently, there are only skeleton functions for play implementation in sound/dev branch and incomplete implementation in sound/inprogress branch."
We will need to flesh out these functions and integrate these branches together.

**Comment by ecoble** [comment]
Issue Score: Satisfactory

Comments:
Nice job researching the sound module! Please be sure to include milestones on the issue, and additionally make sure that you write a detailed summary of the issue, beyond just the text that is automatically generated from the card. Also be sure that there is a clear closing statement with a brief summary about what was accomplished on this task.
