### ISSUE TITLE
Learning about RPG Battles Wishlist to find "promising tasks" and conduct research

### ISSUE THREAD

**Issue by nicholaswlee** [uchicago-cs/chiventure#1176]
members: Nicholas, Nafis
task: Review wishlist and identify which tasks seem promising and research them
https://github.com/uchicago-cs/chiventure/wiki/Battles-~-Wishlist

**Comment by nicholaswlee** [comment]
Nafis and I discussed and looked at the wishlist and the files associated with RPG battles to get an idea of what we could implement for this quarter.

**Comment by nicholaswlee** [comment]
We discussed with Lily about stubs and how we can deal with them when thinking about implementation for this quarter. We hope to work with other teams so that we can fully integrate out stubs.

**Comment by nicholaswlee** [comment]
Nafis and I have completed and published the Battle Planning 2022 document. We have added a preliminary list of ideas we would like to implement for this quarter and exactly how and where these would be implemented.

**Comment by nicholaswlee** [comment]
We have closed this issue and completed a document with everything we would like to implement in the Battles Module. We have included descriptions of these different items, as well as where and how we would implement these types of components. This document is located [here](https://github.com/uchicago-cs/chiventure/wiki/Battles-~-Battle-Planning-2022).

**Comment by lilyehsani** [comment]
Issue Score: Satisfactory

Comments:
Great work! Two comments:
1. Make sure to assign new issues to the sprint they are worked on (by selecting the appropriate sprint under "Milestone").
2. The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/issue-pr-grading.html#descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
