### ISSUE TITLE
Path Autogeneration Algorithm Design

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1178]
Autogeneration of paths is a feature that we aim to generate within the autogenerate module in open world. There are currently plenty of features allowing for autogeneration of rooms, but none for the autogeneration of paths. 

The goal of this issue is to brainstorm how to design an algorithm to automatically generate a path. Specifically, in this issue, we aim to come up with idea for:

1. The parameters that should be used in an algorithm designed to automatically generate a path. 
2. How to use the parameters to provide an autogenerated direction, room destination, and list of conditions.
3. How to design the algorithm to provide continuity in items and rooms (i.e. the rooms near each other should be somewhat similar in nature and contain similar items) while still maintaining a degree of randomness and chance.

**Comment by williamhu314** [comment]
This issue is currently too big to complete in a single sprint. I have created a new issue that is aimed just at creating an algorithm for path generation rather than at fully implementing path autogeneration. The new issue is provided below:

https://github.com/uchicago-cs/chiventure/issues/1178

**Comment by williamhu314** [comment]
As an update, I am currently working on resolving the following important questions regarding a path autogeneration algorithm:

1. How do we choose the direction of the path?
2. How do we choose the item in the path?
3. How should we make the destination room? 
4. How do we make the list of conditions?

So far, my thoughts are:

1. We could either choose it randomly (although it cannot be in a direction with a path already) using the pick_random_direction function or allow the user to input a direction. I am thinking that we can have the default be a random direction and have an optional input if the user wants to specify a particular direction.

2. Obviously providing a random item would be easy to implement, but would make the game much less interesting. There needs to be some way to relate the items in paths and rooms near each other. To do this I will look into the implementation of the room_generate function to see how items were handled there.

3. One method is to use the room_generate function. This may be an option if we are creating a path to a brand new room. I think using this as a helper function and allowing the user to set the parameters to autogenerate a new room within the path generation function.  

4. This is the question I am the least sure about. I will have to do more investigation into how the path conditions work.

**Comment by helenastc** [comment]
Thoughts on providing continuity and choosing destination room/items:

Since the existing algorithm design already autogenerates rooms sequentially with difficulty level taken into consideration we could implement something similar with room/item "category". We can have a room_correlation struct that stores rooms/items in a weighted graph (represented by an adjacency matrix) to show relationships between similar rooms and associated items. We'll design a numbering system to categorize them so that similar rooms and items are closer together. Then when we pass a speclist_t to the autogenerate module it'll have to consider both difficulty and association.

**Comment by lukasg8** [comment]
One thing we should look out for is that the numbering system should not accidentally create a positive feedback loop. i.e. the relationship between similar rooms should not become stronger forever because it could lead to the same time of room being autogenerated on end. We should make sure to implement a limit on the number of rooms in a row which have a "correlation between rooms" above a certain threshold. For example, there should only be allowed 3 dungeon-like rooms in a row. We can also add some sort of logic which determines which types of rooms exist next to which other types of rooms.

**Comment by williamhu314** [comment]
We have completed our brainstorming and will now move on to determining the specifics of how we will generate the item, list of conditions/obstacles, and destination room associated with a path in issues #1206, #1207, and #1208.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work on this issue, especially the comprehensive set of updates.
