### ISSUE TITLE
cli++: research and document understanable pros and cons of parsing libraries in c

### ISSUE THREAD

**Issue by majorsylvie** [uchicago-cs/chiventure#1180]
team members: Kate, Matteo, Faruk
For each member assigned:
Find one c string parsing library.
Research in order to understand its usecase, pros, and cons.
Record that information in some form of notes and include those notes on this issue

**Comment by katyashchukina** [comment]
Hammer
https://github.com/UpstandingHackers/hammer

Pros:
-Language bindings to C++ and Python (among others)
-one of the intended uses is grammars
-simple usage with `#include <hammer/hammer.h>`
-fits our purposes, no problems with installation and example uses show writing grammars for domain specific languages.
-Seems to have more detailed usage instructions than MPC with installation and running instructions as well as more detailed usage examples

Cons:
-Smaller library so less usage examples 
-A couple of known issues, potentially relevant to us is that Python bindings work with Python 2.7, and Python 3.5+ only

**Comment by mrestuccia1** [comment]
PEG

Pros:
- Seems simpler to use than some other libraries such as MPC
- Fits our purposes, since we only need to define a grammar style and the parser will do the rest. Can do this by inputting a filename or directly inputting on the command line. The library will then define a yyparse() function contained in a source file which will allow us to parse future inputs according to specified grammar rules.
-  From the website "Unlike lex and yacc, peg and leg support unlimited backtracking, provide ordered choice as a means for disambiguation, and can combine scanning (lexical analysis) and parsing (syntactic analysis)  into a single activity." (https://www.piumarta.com/software/peg/peg.1.html)

Cons:
- Hard to say right now without knowing the specifics of what we're doing and more specifics about the library, but simplicity may work against us if we need more complex functionality
- Is a little old (September 2013) and does not seem to have been updated since then, so might be outdated

**Comment by mrestuccia1** [comment]
After doing research, we believe both Hammer and PEG offer more accessible features due to having more extensive usage instructions. We are worried PEG might be outdated, but we have decided to work on proofs of concepts for both of these, as we want to make sure to be able to pick the best library for the job.

For this task, Faruk made the opening statement, Matteo (me) carried out all the research seen here  for PEG and Kate carried out all the research seen here  for Hammer.

**Comment by jacknugent1529** [comment]
Issue Score: E

Comments: Excellent work! The pros and cons of each library are detailed and are very useful for choosing a library. The closing statement is also very well-written.
