### ISSUE TITLE
dsl: research testing frameworks in python and create proof-of-concepts

### ISSUE THREAD

**Issue by jhsivadas** [uchicago-cs/chiventure#1189]
This task entails researching different testing frameworks available to Python. Our goal is to find different frameworks, select the most viable, and create an example testing document to provide reference of proof-of-concept for future uses.

team: Jay, William

**Comment by jhsivadas** [comment]
The follow are a few of the testing libraries that William Zeng and I have researched and are going to test implementation for on DSL. We are currently researching more but these are our initial findings. We are trying to figure out the best testing kit that optimizes functionality, makes implementation easiest, is the most updated, and works the best for our specific needs in the DSL domain.

**Pytest**
- Recently updated with a lot of support
- Mainly used for writing tests for APIs
- Can build unit tests or functional tests
- Simple to use (compared to other testing software)
- Can label tests for multiple functionalities 

**Robot**
- Test automation framework for acceptance testing 
- Keyword driven testing technology 
- Acceptance testing and Acceptance test driven development

**Unittest**
- Unit testing framework
- Create testing functions
- Simple functionality, doesn’t extend much beyond unit testing

**PyUnit**
- Comes with the python package and no additional modules needed to run it
- Offers simple and flexible test case execution
- Quick generation of test reports
- XML reports
- Unittest-sml-reporting
- Needs a lot of boiler code which does not optimize code functionality.
- based on Junit, camelCase naming method is in use, instead of Python’s snake_case naming convention.
Intention of the code isn’t clear sometimes

**Comment by wzeng0** [comment]
After extensive research, we decided to use unittest because of how user-friendly it is with all of its detailed documentation available. Unittest also allows for flexibility of implementation because of the structure of the unit-testing within class and function inputs. We believe that the detailed documentation, constant updates, and flexibility of implementation will allow for ease of use for future testing on DSL tasks compared to the other frameworks we researched. Below is our proof-of-concept for how our future test would look like when using this unittest library.

This code block checks whether the document itself is parsed correctly given that we know what it is supposed to look like
```
import unitest
def room_to_dsl(room_list):
	(the function that converts dsl file to wdl format)
 
class TestRoomList(unittest.TestCase):
	def test_room_to_dsl(self):
		actual= room_to_dsl(list)
		expected = {
			"ROOMS": {
   				"room C": {
      					"items": [],
      					"long_desc": "This is a room C. ",
      					"short_desc": "room C"
   					},
    				"room B": {
      					"short_desc": "A dungeon room.",
      					"items": [
       						"Door"
      						],
      					"long_desc": "This is a room B. "
    					}
  				},
  	  		}
  	  	self.assertEqual(actual, expected)
```

This block of code checks whether a certain item is included in the parsed file
```
import unitest
Class Room:
	def__init__(self):
		Self.has_key = false
	Def has_key(self):
		Self.has_key = true
Class TestItem(unittest.TestCase):
	Def setUp(self):
		Self.room = room()
	Def test_room_empty(self):
		self.assertFalse(room.notEmpty)
	Def test_has_key(self):
		self.assertTrue(self.room.has_key)
 
```

**Comment by jacknugent1529** [comment]
Issue Score: E

Comments: Nice job on this issue! It looks like you have good reasoning for selecting one framework over another. Be sure to convert cards to task shortly after the sprint begins.
