### ISSUE TITLE
dsl: disable default property generation

### ISSUE THREAD

**Issue by jhsivadas** [uchicago-cs/chiventure#1190]
As of before, the dsl generator would always include default values if room/item/action descriptions, etc were missing. However, it would be beneficial to have the option to disable this default property generation with a flag passed to the main function. It would also be useful to have the option to only generate the required properties, and not generate anything for optional descriptions. 

team members: andi and jay

**Comment by jhsivadas** [comment]
Currently have updated parse_dict_to_json within parse.py and to_wdl.py to include a new parameter that checks if (and stores the flag) the user inputs the no-defaults flag or some-defaults flag. Also updated the "Item" "Game" and "Room" classes to include a new instance variable "default" that stores the default flag passed in. If no default flag is passed the classes fill the variable with an empty string. Planning on implementing actual functionality for default flags.

**Comment by awliu2** [comment]
Currently implemented default flag handling. 
"--no-defaults" will not generate any default values, and return warnings to console. Must be used with caution as it can generate unusable WDL files. 
"--some-defaults" generates all required default values. Optional values (i.e item success and fails) are not generated.

These flags should be passed to the call to the main function in the dsl module (i.e when building a wdl file from a provided dsl file). 

Note that enabling --no-defaults may generate wdl files that will not run in chiventure due to missing required descriptions. However this is the intent of adding this function to make it easier for game authors to create WDL files completely under their control, without any generated components.

**Comment by awliu2** [comment]
We have finished implementing this feature into the dsl module. Everything works as expected. We may need to come back to this as more features and functionalities are added to the dsl module.

**Comment by jacknugent1529** [comment]
Issue Score: E

Comments: Nice job with this issue! The updates are thorough and explain your progress and thoughts well. Be sure to create the issue early in the sprint.
