### ISSUE TITLE
Implement a basic command parser

### ISSUE THREAD

**Issue by borjasotomayor** [uchicago-cs/chiventure#12]
Implement a command parser that is able to parse, at least, commands like this:

- Actions with no parameters: `LOOK`
- Actions with one parameter: `TAKE orb`
- Actions with two parameters (and a preposition): `GIVE talisman TO wizard`

Right now, the parser doesn't need to validate the actions/objects, but it should return them so they can be processed further by a calling function. It can also be worthwhile to start making the parser general enough to accommodate the exact actions that will be decided by Action Management.

**Comment by ecoble** [comment]
Researched strtok()

**Comment by borjasotomayor** [comment]
@ecoble: While providing status updates is good, you may want to also include at least 2-3 sentences with more details (in this case, whether you have any thoughts on how well strtok could work, whether you expect to do more work with strtok in this task, etc.) Even just mentioning that you've pushed some code (and describing what it does) can be useful (on top of ensuring that the relevant commit appears in the issue)

**Comment by ecoble** [comment]
A follow up about the parsing function and strtok():

The parsing function uses strtok() to take a string and break it into individual words, then returns a list of those words. This list is a fixed size, this size being the number of possible words a user can enter (currently this number is 4). If the user only enters say "TAKE orb", the last two spaces of the array will be NULL. This function will later be integrated with the cmd files. 

Concerns/Things to keep in mind: Currently the list that is returned is of a fixed size, the idea behind this being the user of the array will be able to easily index into the array and identify commands and objects without having to worry about its size or looping through it. However, this design may prove to be inflexible or inefficient if we want to support commands with more words in the future. Redesigning this will likely depend on how the GameState team would like to use these words.

**Comment by Gestalt-R** [comment]
Adjusted the cmd type.
Before, it had one argument, and one enum acting as the name. 
Now, it has two argument spots, and one enum acting as the name, and another as the preposition.
Added the enum type for prepositions

Wowee, a lot of stuff went on here.

Backported all of the cmd file to fit this.
Added a command that takes the token list and converts it to the command format.
Made a bunch of macros to make this easier.

Concerns: Because I used strcpy, I limited the size of tokens to 32 characters. 
Other concerns. Due to the use of macro, we need to define all commands before compiling engine. This means that we must have a set of all possible command words (and prepositions) listed in file. 

Hopefully, WDL doesn't implement that. If they do, owing to non-mutable enum types, we will have to redesign the entire command system.

**Comment by lydiafilipe** [comment]
Issue Score: ✓-

Comments:
Great updates, however you do not have a closing statement here. Please review the requirements for graded work section in the project spec

**Comment by ecoble** [comment]
Closing statement: Implemented a parser that takes a string and parses it into individual words, breaking on spaces. The parser returns a list of these individual words. Currently the maximum amount of words allowed is four, although this can be changed later on if necessary.
