### ISSUE TITLE
Read the documentation and code and evaluate the current quest tree structure's effectiveness

### ISSUE THREAD

**Issue by JSerf02** [uchicago-cs/chiventure#1201]
There have been significant refactors of the quest tree structure in the past, so we need to determine whether the newest version of this structure suits all of the needs of the quest module.

**Comment by JSerf02** [comment]
Charlie and I read through the documentation and determined that the current tree structure suits our needs. The only issue is that the documentation for the tree structure was extremely disorganized and obscured how the structure actually worked (after our first read of the Wiki pages, we thought it was a binary tree!). We fixed this by updating the documentation with a visualization of the data structure and an evaluation of the data structure's pros and cons.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job, but in the future try to revise the summary as it is currently too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/issue-pr-grading.html#descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
