### ISSUE TITLE
Create Feature/Task Wishlist

### ISSUE THREAD

**Issue by Castel-Jaloux** [uchicago-cs/chiventure#1202]
Although there are issues on the backlog, we, as a project group, need to decide which direction we wish to extend this project in and how we wish to implement the concepts of Quests in Chiventure over the following quarter. This is imperative for the proper development of this aspect of the project and ensuring that we have a path to follow in future sprints.

**Comment by Castel-Jaloux** [comment]
We brainstormed and created a list of possible features, choosing the features we wished to actually implement in Chiventure. In particular, we focused on elements that would add to the usability and variability of the quests feature to broaden overall functionality, thus improving the user experience.

**Comment by Castel-Jaloux** [comment]
We created a page on the project wiki detailing the list of features we intend to implement in Chiventure. This will not only help us remember what we intend to focus on at any given time, as well as track our own progress, but also inform related teams of the work we intend to to over the quarter.

**Comment by Castel-Jaloux** [comment]
We successfully developed a feature wishlist and created a page on the wiki in order to make this information available for the other members of our team as well as other teams.

**Comment by philipchenaux** [comment]
Issue Score: Satisfactory

Comments:
Great job on this issue! Two key issues though:
1. Even though you can add labels to issues to categorize them, you should avoid titles that could plausibly apply to multiple teams. So make it specific to your team!2. 
2. Instead of just referring to the wiki being updated, it would be helpful to explain what elements you added to the wiki during each of these updates. These can be very brief, but it at least makes the updates tangible.
