### ISSUE TITLE
Understand current game loading to begin designing integration of autogeneration in the rest of chiventure

### ISSUE THREAD

**Issue by helenastc** [uchicago-cs/chiventure#1205]
We need to familiarize ourselves with how chiventure is loaded up right now to help us begin designing the implementation of autogeneration. We can also refer to implementation plans from previous years. Document findings in wiki.

**Comment by helenastc** [comment]
Games are loaded from a WDL file in the WDL module.
Our next consideration is at which point we want to integrate our autogeneration features.

**Comment by philipchenaux** [comment]
Issue Score: Satisfactory

Comments:
Great job! Here are a few things you may want to improve in future issues:
1. The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/issue-pr-grading.html#descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.2. 
2. When an issue is done, you should include a final comment summarizing what was done, and why the issue is being closed.
3. Make sure to assign new issues to the sprint they are worked on (by selecting the appropriate sprint under "Milestone")
