### ISSUE TITLE
Path Autogeneration: Brainstorming methods for creating a list of conditions

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1207]
In this issue, we aim to generate ideas about how we can create the list of conditions/obstacles associated with an autogenerated path. This issue is related to issue #1178.

**Comment by williamhu314** [comment]
We are mostly focusing on a generating a game of some sort right now with our create_static_game and create_dynamic_game function. We will come back to this later if we have time but I am moving it to the backlog for now.

**Comment by williamhu314** [comment]
We are not currently working on automation for generating the conditions for paths randomly so we will close this issue.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work. However, the summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/issue-pr-grading.html#descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
