### ISSUE TITLE
Path Autogeneration: Determining how to create the destination room.

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1208]
This issue aims to determine how the destination room of an autogenerated path should be generated. This issue is related to issue #1178.

**Comment by williamhu314** [comment]
Our current approach to generating the game will take care of generating the destination room. Thus, this issue is no longer applicable and I am closing it.

**Comment by philipchenaux** [comment]
Issue Score: Satisfactory

Comments:
Great work on the issue, but here are two areas for improvement:
1. The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/issue-pr-grading.html#descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.2. 
2. Your issue did not include any status updates between the opening of the issue and the closing of the issue (and this issue was not small enough to justify having no status updates at all). If you make any intermediate progress before finishing the task, then it should be documented on the GitHub issue via a comment.
