### ISSUE TITLE
sound: research text to speech

### ISSUE THREAD

**Issue by parkerbroz** [uchicago-cs/chiventure#1217]
Find and demo some suitable libraries which could implement a dialogue tts feature into Chiventure
members: Parker, Jason

**Comment by JaStarbuck** [comment]
From Parker's slack message the other day, thought I should take note of it in github:
"I'm running into issues setting up festival. Not only was it written in c++, but I think the version of c++ it was written in is now outdated. The sample hello world program they gave as a compiler check has errors which stack overflow claims are due to conflicts between pre and post 2000s C++ compilers. I've already spent a few hours trying to get this to work, but I'm wondering if I should chalk festival up to a loss and switch directions to a new library. What do you guys think?"
Reply: 
"if festival is really hard to get running, i think it is a good idea to table it for now and check out other libraries."

**Comment by parkerbroz** [comment]
As written by @JaStarbuck, I initially researched and attempted to implement the Festival library. It came highly recommended from both online forums and Borja. However, I encountered numerous issues when attempting to compile the library for a simple demo and decided to move on after a few hours of fruitless struggling.

Next, I researched [GNUSpeech](http://www.gnu.org/software/gnuspeech/). When reading through it's features, I was struck by the range of inputs it could handle. Aside from a 70,000 word dictionary with 6,000 names, it can parse non-word attributes into words (dates, numbers, etc.) and speak them. It can also pronounce words not in it's dictionary, just with less accuracy. 

Unfortunately, I haven't had time to create a working demo for GNUSpeech due to the hours I sunk into Festival. However, I still feel GNUSpeech is a candidate to move forward with. We can pick a library at the next sprint to fully commit to.

**Comment by JaStarbuck** [comment]
Through my research, I have found espeak. The github showing how it works and a demo is here:
https://github.com/espeak-ng/espeak-ng/blob/master/docs/integration.md
I tried to get the demo to run as it was written in the readme but I ran into the problem of not being allowed to download the libraries on the linux system due to restrictions. I wonder if this is a problem that can be resolved or if it means that we should use a different library. Espeak seems like a really good option for chiventure because of its seemingly straightforward usage, variety of options to choose from, versatility, and the fact that it's written in C.

**Comment by JaStarbuck** [comment]
On @parkerbroz 's last post, he spoke about GNUSpeech. I've also encountered it and am impressed by its seemingly large variety of features. However, there seems to be little recent documentation about how to set it up and how to make a demo. The website is from ~2003 I believe so I'm not even positive its a good idea for us to look into based off of the possibility its simply too old.

**Comment by JaStarbuck** [comment]
The three main libraries we researched were festival, GNU speech, and espeak. It seems like espeak is our best option because of its better documentation than the rest and its wide range of features. However, we have not been able to implement a demo. We will need to use the VM in order to download dependencies to test and create a demo of vspeak before we can fully implement it into chiventure.

**Comment by ecoble** [comment]
Issue Score: Satisfactory

Comments:
Nice job researching these libraries and picking a suitable one, this is really exciting work! Please be sure to include milestones on the issues. Also, while the here summary is descriptive see if you can flesh it out a bit more in the future.
