### ISSUE TITLE
Create a design document for NPC integration with Battles

### ISSUE THREAD

**Issue by emilybae1705** [uchicago-cs/chiventure#1224]
For this sprint, we need to evaluate what structs of the NPC module need work on to successfully integrate with structs in the battle modules. We will meet with the battle team to discuss their plans for the quarter and create a design document/wishlist of our ideas for how to improve the npc structs in relation to battle structs.

**Comment by srydbergcox** [comment]
Today, Emily and I met with the battles team to discuss their plan for battles for this quarter and what changes/improvements needed to be made to the NPC modules. They told us that their goal for the quarter is to make battles more complex by implementing more move options (i.e. moves that can change your stats), status effects (i.e. becoming paralyzed, poisoned, etc.), and, if time allows, random NPC battles (this may involve the Open World team as well). 

In order to accommodate these goals, we decided that we will make sure that the current implication of npc/npc_battle structs are compatible with the battle functions implemented in the battle module. Further, we will confirm the compatibility of the npc structs with the battle_ai header file. To make battles more complex and exciting we also will look into the status of conditional battles which includes npcs being friendly, hostile, or conditional hostile. This means that friendly npcs cannot be fought, hostile npcs will always be fought, and conditional hostile npcs allow the user to choose if they want to fight. Finally, moving forward, we believe that there is room to improve the player classes of NPCs to allow for different move sets and add more variety to battles/npcs in general. 

https://docs.google.com/document/d/1Jbnhc9uAHyTTw3JtAzor__g8URMxm557J4N_vC42b5Y/edit?usp=sharing

**Comment by srydbergcox** [comment]
After looking through the structs that are utilized in battles and for NPCs in general and npc_battle there does not seem to be any compatibility issues.

**Comment by srydbergcox** [comment]
With regards to the difficulty level of battles, this has been implemented into npc_battle.h but it is not immediately clear if/how this will be implemented into the battles. One possible option is to integrate it with the difficulty of battles. Or, it may even be a CLI issue as the use of the hostility struct is to designate NPCs as impossible to fight, having the option to fight, or to always fight.

**Comment by emilybae1705** [comment]
We've created a brief outline of our design document in the [google doc](https://docs.google.com/document/d/1Jbnhc9uAHyTTw3JtAzor__g8URMxm557J4N_vC42b5Y/edit?usp=sharing) mentioned above, which also includes notes for our meeting with Battles. For full design details, please take a look at the newly created [wiki page](https://github.com/uchicago-cs/chiventure/wiki/NPC-~-NPC-Battle-Integration-Design-Document).

**Comment by emilybae1705** [comment]
For this sprint, we created a [design document](https://github.com/uchicago-cs/chiventure/wiki/NPC-~-NPC-Battle-Integration-Design-Document) detailing relevant data structures and modules as well as our wishlist for the quarter. We met with the Battles team to discuss which features they're interested in working on for the quarter and how the NPC team could help. They mentioned they're interested in 1) temporary stat change, such as having moves and battle items that can temporarily change a player's stats during battle and 2) additional status effects (ex. if a player is poisoned, they go to sleep). After the meeting, we set up our primary goal as reviewing whether there are any data structure conflicts between the npc_battle module and the battle_ai module, to which we confirm that there are none. Rather, there are some conflicts that can be resolved between `npc_t` and `npc_battle_t` such as including battle inventory items in the `npc_battle_t`. This is a design consideration that we will make in the next sprint. We've also decided to include 3 different hostility levels for NPCs: friendly, conditional friendly, and hostile. Our goal for the next sprint is to make key design choices that impact npc_battle_t such as _where_ hostile NPCs will be stationed,  _how_ they will provoke players, and which player class_type they will engage with. To this end, we will reach out to the Player Class, Open World, and potentially Skill Trees as well to discuss how NPCs can factor in.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work! While using Google Docs to sketch out some of the documentation, you should avoid posting links to those Google Docs from an issue, as it may cause confusion as to whether that document (or some future update to the wiki) is the most up-to-date version of that documentation. You should instead transfer the contents of the document to the wiki, and then link to the wiki when updating the issue.
