### ISSUE TITLE
Design documentation for conditional skills

### ISSUE THREAD

**Issue by anchristensen** [uchicago-cs/chiventure#1229]
Think through and design header files/functions/structs to support the implementation of conditional skills, one type of complex skills as described [here ](https://github.com/uchicago-cs/chiventure/wiki/Skill-Trees-~-Integrating-complex-skill-(combined,-random,-sequential,-etc.)-implementation)

**Comment by anchristensen** [comment]
@nbilaver and I added a new complex skill enum with CONDITIONAL as an option, and a general complex_skills_t structure was designed with three parts; a complex skill enum indicating which kind of complex skill it is, a list of skills used in that complex skill, and the number of complex skills it uses. We created a complex skills header file which includes supporting functions to allocate, initialize, free, and execute a conditional skill. @nbilaver implemented a reader effect option; in particular, a reader_type enum and a reader_effect struct were added which keep track of the condition being checked/met to execute the conditional effect. Supporting functions were also added for reader effects, for instance to free them.

**Comment by jacknugent1529** [comment]
Issue Score: S

Comments: Nice work! It looks like you've thought through the structure of the code. This should greatly help with implementation. Remember to state a tangible goal when summarizing the issue, and also be sure to add status updates as you work through the issue rather than a single closing comment.
