### ISSUE TITLE
Review/fill in documentation for Example Stats and Abilities, and Class List

### ISSUE THREAD

**Issue by katie-gao** [uchicago-cs/chiventure#1234]
members: Katie
task: Find/review or fill in documentation for Example Stats and Abilities and Class List

**Comment by katie-gao** [comment]
Found that a lot of the information was in this page : https://github.com/uchicago-cs/chiventure/wiki/Player-Class-~-Prefabricated-Classes 
I think that link is lost somewhere in the wiki, so included the info on the already made Class List page and Example Stats and Abilities Page.  As there are limited stats, old classes like elementalist and knight have been removed as too similar to Wizard and Warrior respectively. 
Links to the new pages : https://github.com/uchicago-cs/chiventure/wiki/Player-Class-~-Class-List
https://github.com/uchicago-cs/chiventure/wiki/Player-Class-~-Example-Stats-and-Abilities

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work! The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/issue-pr-grading.html#descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
