### ISSUE TITLE
Integrate Class module with NPC module

### ISSUE THREAD

**Issue by wellingtj** [uchicago-cs/chiventure#1236]
members: Jake, Jonathan
task: Create a design document for complete integration with NPCs

**Comment by wellingtj** [comment]
We have met and reviewed the documentation for the NPC module. We will work on the design document for integration soon.

**Comment by wellingtj** [comment]
[Design document for NPC integration with playerclass](https://docs.google.com/document/d/1WoeLsSxCbhHQQfZ_UaZR3hbTN3YZEGFzIhRWGb8dY64/edit?usp=sharing)

**Comment by wellingtj** [comment]
this document has been approved, we will pick a few key issues and shorten it, put it on the wiki, and then close this issue

**Comment by jroven** [comment]
The contents of the document have been moved to the wiki page Player Class ~ Player Class NPC Integration.

**Comment by lilyehsani** [comment]
Issue Score: Satisfactory

Comments:
Great work! Two comments:
1. The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/issue-pr-grading.html#descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
2. While using Google Docs to sketch out some of the documentation, you should avoid posting links to those Google Docs from an issue, as it may cause confusion as to whether that document (or some future update to the wiki) is the most up-to-date version of that documentation. You should instead transfer the contents of the document to the wiki, and then link to the wiki when updating the issue.
