### ISSUE TITLE
GUI: Making Inventory Displayable, Part 1

### ISSUE THREAD

**Issue by dhirpalshah** [uchicago-cs/chiventure#1262]
After we get raylib working, we need to make sure that we can design a basic inventory that works with raylib. Previously, we designed the main functions that we would need, but we need to actually implement them this sprint. If we cannot use the information provided in the player.h module (a hash that stores items the player is holding), then we can just try to do it with dummy items.

Note previous issue:
https://github.com/uchicago-cs/chiventure/issues/1196

**Comment by dhirpalshah** [comment]
We have completed a very basic interface of what an inventory would look like.
<img width="796" alt="Screen Shot 2022-05-09 at 6 18 00 PM" src="https://user-images.githubusercontent.com/86183980/167513670-c66e1f64-e827-450f-bbd7-a9ceb493d027.png">
We want to add in items that can be interacted with (e.g. a key that can be used, dropped, or moved).

**Comment by csraffaga** [comment]
I have just defined some key structures that are important for the functionality of the inventory module. I created a new inventory struct that takes into account the graphical customizations specified by the author in the GDL file, as well as a representation for the items in the inventory. There is room to decide how to represent the inventory (adjacency list vs matrix) but the struct is complete with its element.

**Comment by ukanyanwu** [comment]
On Thursday, @dhirpalshah, @csraffaga and I met to discuss a further design for the inventory. We settled on a struct for the player inventory, with the items being stored in a 2D array. The current inventory header file establishes the player_inventory struct along with the appropriate new, init, and free functions. We've also decided on functions to update the actual inventory, along with a function that actually draws the inventory. The drawing of the inventory appears to work well, and the next steps are to properly implement the other functions, along with writing tests for them since drawing the inventory itself will be accomplished with eyeball tests.

**Comment by csraffaga** [comment]
The inventory module has been refined. Add and remove from inventory functions have been added to the .h file and implemented in .c. This required a small edit to the inventory struct. The inventory is now a matrix of slots and each slot contains space for an item and a tag (full or empty) which is an enum type I designed.  This is an important inclusion because without it one would not be able to determine the state of any index in the matrix!

**Comment by ukanyanwu** [comment]
Yesterday, @csraffaga and I met to work on the inventory struct and decide what needs to be done to make the first half of this module get further to completion. We looked through our current code and decided that the new/init/free functions for player_inventory needed to be rewritten. This will make it easier for testing, and following chiventure standards when everything is ready to be used in a pullrequest. Tests have been written, however conflicting issues with raylib and criterion on some of our devices make it hard for us to confirm that our tests work as they should. Once we confirm the results from the tests, we hope to make a final round of changes for the player_inventory and slot structs.

**Comment by csraffaga** [comment]
This issue can be closed. Inventory display PRs have been pushed and are awaiting approval. In short, inventories can be draw to the screen and with specialized inputs from the GDL!

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work on this issue and a very through set of updates.
