### ISSUE TITLE
Consultation for the integration of the display_statistics and inventory modules

### ISSUE THREAD

**Issue by csraffaga** [uchicago-cs/chiventure#1274]
There appears to be overlap between the inventory GUI feature and the display_statistics module. There may be merit in combining these into a more general purpose module that is better suited for evolution. This would allow for additional on-screen features to be added.

**Comment by csraffaga** [comment]
Met with @dhirpalshah and @Cyrus-Zhou2302 to discuss the integration of a general pop-up data struct that I implemented as part of my display_stats module in Sprint 2. Our new graphics UI.h module will implement this pop-up data struct to track input information specified in the WDL file for window size and location (this functionality will be adjusted later this sprint) as it is general purpose for different pop-up windows (stats, inventory, class information etc...). The code is currently located in the gui/player_statistics_feature branch.

**Comment by philipchenaux** [comment]
Issue Score: Satisfactory

Comments:
Great work again! Here are a few sources of error with this issue that you can work on for future issues:
1. The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/issue-pr-grading.html#descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
2. Your issue did not include any status updates between the opening of the issue and the closing of the issue (and this issue was not small enough to justify having no status updates at all). If you make any intermediate progress before finishing the task, then it should be documented on the GitHub issue via a comment.
