### ISSUE TITLE
Filling in TODO's for preset prefab classes

### ISSUE THREAD

**Issue by katie-gao** [uchicago-cs/chiventure#1276]
Van and I are going to fill out the TODO sections in the class_prefabs.c file in the playerclass module. These TO DO sections are essentially filling out abilities and skills for classes other than the warrior class. The warrior class is the only class in the function that has code for abilities. This includes being creative with three new combat abilities for each rogue, ranger, bard, wizard, and monk alongside damage numbers that balance them out.

**Comment by katie-gao** [comment]
I feel like wizard and sorcerer are similar? As seen from the player class list on the wiki, it seems that sorcerer is an old class while wizard is a current class. Should we not fill in sorcerer in the preset prefab class? Also, elementalist, druid, and knight are not in the code, so we decided not to add any skills for them.

**Comment by katie-gao** [comment]
Also the now updated wiki page provides a documentation for the additional combat abilities, and damages that matches the changes Van and I made to the code.

**Comment by katie-gao** [comment]
Van and I filled out all of the to do for the preset pre fab classes (Bard, Monk, Ranger, Wizard, Warrior, and Rogue). In the document (check out wiki documentation here: https://github.com/uchicago-cs/chiventure/wiki/Player-Class-~-Example-Stats-and-Abilities )in the previous comment, there is the list of damages and new skills for each class. As can see from class_prefabs.c all is updated, and we have pushed changes to the playerclass/add-prefabs branch in git. Since all the code is now written alongside comments on the new damages , we are closing this issue.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! Two comments:
1. Status updates on an issue should have something tangible to share. Asking questions like "I feel like wizard and sorcerer are similar?" should be done through other means, and the path you choose to take is what should be shared in the update.
2. Ordinarily, an issue associated with a PR shouldn't be closed when the PR is opened, but when the work associated with that issue is done (i.e., when the PR is complete and merged).
