### ISSUE TITLE
Understand NPC dialogue mode and use this to create a run_battle design document for integrating battles with CLI

### ISSUE THREAD

**Issue by aliu65803** [uchicago-cs/chiventure#1277]
First, we will look at and learn from the NPC dialogue mode, which contains an example of CLI integration. We will then meet with the CLI team and figure out what we need from them to implement our run_battles function that is laid out in the Battles ~ Run Function Design Document on the wiki page. Finally, we will update our run_battle design document to reflect any changes we will make after taking inspiration from the NPC dialogue mode.

**Comment by emiliolevinspage** [comment]
We found CLI dialogue mode in an [npc dialogue design document](https://github.com/uchicago-cs/chiventure/wiki/NPC-~-Dialogue#cli-integration). It reads

"CLI Integration
To run dialogue from the CLI, we need a way to parse numbers, as opposed to words. To facilitate that, we use a mode functionality. (See: [mode.h](https://github.com/uchicago-cs/chiventure/blob/dev/include/game-state/mode.h))

In short, when the player types the command talk to <NPC>, the game switches into "conversation mode." In conversation mode, we parse the user's input as numbers rather than words. We then call the associated dialogue function to carry out the conversation. Once the conversation is over, the game switches back to "normal mode.""

Angela and I are going to familiarize ourselves with the integration code in the mode module in game state before we design our own battle-CLI integration.

**Comment by aliu65803** [comment]
Emilio and I decided to take inspiration from NPC Dialogue's Numeric options. We would like all available moves to be listed when the player asks for them and for them to be able to select the move they would like to use simply by inputting a number.

**Comment by emiliolevinspage** [comment]
Found a monkeypatched battles-CLI integration used by Battles example in the mode module in game state. It is pretty buggy and also hardcoded to a particular turn structure, so we will model our more permanent one off of the cleaner, iterative NPC dialogue mode integration. Wondering if this will require a digraph like they use for dialogue.

**Comment by emiliolevinspage** [comment]
After looking at dialogue mode, we updated our run_battle design document with an example of what the ui of battle mode should look like.

**Comment by aliu65803** [comment]
Yesterday, we met with two members of the CLI team and figured out what we would like them to do for our run battle implementation (display move/item choices and send back the response to us). They said they will most likely be able to complete the CLI integration by the end of this sprint.

**Comment by aliu65803** [comment]
In a meeting with Lily on Friday, we talked about ways to change our current design document to be closer to how NPC dialogue is implemented. We will change our current design document to reflect these changes. Moreover, we were told we can split the implementation into a separate issue.

**Comment by emiliolevinspage** [comment]
We updated our [design document](https://github.com/uchicago-cs/chiventure/wiki/Battles-~-Run-Function-Design-Document) and are ready to begin implementing.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
