### ISSUE TITLE
Design modules for a user-friendly custom-scripts interface

### ISSUE THREAD

**Issue by tatmaca** [uchicago-cs/chiventure#1284]
Assignees: Ramarko, Togay

Description: The custom-scripts team decided that it would be helpful to create a module that would allow it to be easier for other dev teams to play around with and implement their own custom-scripts, depending on the needs of their individual projects. Ramarko and I will begin work on designing and setting up a module which allow users unfamiliar with Lua to be able to easily implement their own scripts.

This issue will be complete when we have corresponding C and header files which we can then implement a UI for others to create custom-scripts.

**Comment by RamarkoB** [comment]
See Issue #1330. In short, the functions themselves were simple to use, but required better documentation to understand. Togay further simplified the functions so that Object and Get functions are now type-agnostic, so the usage of the Custom Scripts functions are easier to use. Marking this issue closed, but can be reopened if a more simple interface is required in the future.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Nice job looking into this! There could be a few more updates on the progress of this task, even if it ended up being a smaller task.
