### ISSUE TITLE
Collab with Action Management to Create a Design Document for Unstubbing Current Stubs and Aligning Data Types in Game-State

### ISSUE THREAD

**Issue by nicholaswlee** [uchicago-cs/chiventure#1285]
We will meet with the Action Management team to discuss the integration of current battle stubs with existing code contained in the game-state module. The task will be finished once a design document is created for the unstubbing of current stubs and aligning of data types in game-state.

Members: Nafis, Fatimah, Nicholas

**Comment by corian-jal** [comment]
We are currently trying to arrange a meeting with the Action Management team to discuss certain inclusions in the game-state module.

**Comment by nicholaswlee** [comment]
Met with rpg/battle. We will be taking their surrender level field and putting it into our stat_t struct. Additionally they will possibly changing their structs to add battle_item_t. To add on, they will also be removing their health stat from their npc struct.

**Comment by nmkhan100** [comment]
Met with the action management team and have created a design document for our changes.

**Comment by nmkhan100** [comment]
Looked through all of the data types in the battle module that are stubs and need to be unstubbed.

**Comment by nmkhan100** [comment]
Found structures in battle_structs.h, battle_common.h, and battle_flow_structs.h that require integration into the game state module.

**Comment by nmkhan100** [comment]
Discussed with Sabine the data structures in the game state module that require changes in order to integrate our own data structures (from the battles module) with them.

**Comment by nmkhan100** [comment]
Here is a link to the page we worked on: (https://github.com/uchicago-cs/chiventure/wiki/Battles-~-Unstubbing-Stubs-Design-Document)

In order to integrate the stubs in the battle module with the structures in the game state module, we looked through the battle module for all the stubs that need to be updated, which we recorded in the design document. Sabine and I then discussed the specific data structures in the game state module that need to be modified to accommodate for the stubs we found in the battle module. With all these issues addressed, the action management team can work on the integration process now.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! Even though you can add labels to issues to categorize them, you should avoid titles that could plausibly apply to multiple teams. It would have been good to refer to "battle" stubs specifically in the title.
