### ISSUE TITLE
update tests to reflect new changes in quest_Id for delete quest

### ISSUE THREAD

**Issue by jakeziqiwei** [uchicago-cs/chiventure#1294]
Last sprint, the team members changed some elements of the quest struct, we need to update the quests to reflect this change

**Comment by elizabethli31** [comment]
We forgot to leave a closing comment before, but there weren't many changes made for this issue because we wrote the tests and function in the previous sprint but had to make some small modifications because of the change in quest_id format. We also originally had one function that would either remove all quests or just one but decided to split that into two functions

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work -- short and to the point!
