### ISSUE TITLE
GUI: Making Quests Displayable, Part 1

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1295]
In this sprint, we will collaborate with the quests team to make quests displayable in a separate window with testing data.

**Comment by elizabethli31** [comment]
Worked with graphics team to make task trees visible

**Comment by elizabethli31** [comment]
This issue is separate from #1161 which addressed more of the CLI side. The GUI team and I talked through the specifications of our quest task_tree struct and how we wanted to have these displayed. So far, they created a simple display of the tree positions using letters but not yet with the actual task_ids which will hopefully be done during this next sprint.

**Comment by philipchenaux** [comment]
Issue Score: Satisfactory

Comments:
Great work! Here are three takeaways from this issue that you can try to implement in future issues:
1. The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/issue-pr-grading.html#descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
2. For a task of this size, we would've expected to see more status updates and/or status updates that were more detailed.
3. The issue was closed before it was actually done. Ideally you would close the issue after you have made your closing statement.
