### ISSUE TITLE
GUI: Making NPC displayable, Part 1

### ISSUE THREAD

**Issue by cyruszzhou** [uchicago-cs/chiventure#1297]
In this sprint, we will be making NPCs displayable in a separate window taking in testing inputs.

**Comment by cyruszzhou** [comment]
Update: I have coded up the NPC display. For animation, we will be requiring Chiventure Game Developers to upload equally spaced, multi-frame images. Frame speeds and frame numbers are also taken care of. There is also a textbox for printing out the NPC's lines. NPC can have different actions (stored in a linked list) and lines (also stored in a linked list).

**Comment by Cyrus-Zhou2302** [comment]
The issue is currently closed. I look forward to having this feature integrated into the master branch. I will also be refining the adaptation of this feature into the main program as I finish coding up the wdl parsing program.

**Comment by cyruszzhou** [comment]
The issue is currently closed. I look forward to having this feature integrated into the master branch. I will also be refining the adaptation of this feature into the main program as I finish coding up the wdl parsing program.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work, just a minor note: I though that the summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/issue-pr-grading.html#descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
