### ISSUE TITLE
Research serialization file formats

### ISSUE THREAD

**Issue by borjasotomayor** [uchicago-cs/chiventure#13]
Find 2-3 serialization file formats, along with C libraries to work with them, and determine the possible pros and cons of each library.

Possible formats to look into:

- Protocol Buffers
- Python's pickle format
- UBJSON
- msgpack

**Comment by ellynliu** [comment]
MessagePack is advertised on their website as JSON, but smaller and faster. Here is a guide I found to using msgpack in C: [https://github.com/msgpack/msgpack-c/wiki/v2_0_c_overview].

Pros:
msgpack seems pretty straightforward based off of the overview. There are 4 types of buffers: sbuffer (simple memory), fbuffer (file), zbuffer (zlib), and vrefbuffer (iovec). Each buffer has commands to initialize, destroy, and write all the data types, arrays, objects, and more. Going backwards to unpack the binary data is also taken care of with provided commands.

Cons: 
Although there is a guide on how to use msgpack in C, it is quite brief in comparison to the guide in C++, which contains much more documentation and explanation. The C++ guide seems like it could be useful, but I had a hard time understanding what was going on in C++.

**Comment by jarvislam1999** [comment]
After some digging around, it seems that the general factors that go into picking our serialization format are:
- Space: will the save file takes a lot of space or little
- Time: will the serialization and deserialization speed be quick
- Portability: will it work independently of compilers, machines, languages, where data types can be defined differently.
- Compatibility with C: are there a lot of libraries or existing codes that help with the serialization code in C or do we need to write our own.
- Human readability: for debugging purposes

Regarding these factors (at least only these for now), JSON has the advantage that it will be very easy to define a format and convention to our structs and C code, and then convert it into a JSON file, and then turn that file into binary (I think that's how UBJSON works?). It will also be very human readable. The disadvantage is that we have to write complex codes just to print out the JSON format and read that in (think about all the {} and : we have to detect and string codes :(( ). I also did not find any codes online that really helps out with JSON serialization into C, so minus on the compatibility. JSON files will also take up space and time to run I presume. Generally, I think we should move away from it.

From what Ellyn said, msgpack seems like a good idea, though I have no idea how it works. Also with little documentation on C it may not be worthwhile. You guys should definitely look into it, however.

I found several different libraries worth checking:
https://github.com/liteserver/binn
https://github.com/DiUS/cser
I'm unsure how either of them works though.

For Python pickle format, I did not spend much time on it, but it appears we should not use it simply for the reason that it's made for Python. As we are most likely to be writing in C code, a library that serializes Python objects seems counterintuitive. 

Custom binary format: Probably not, this fails on all fronts of portability, compatibility, space, time, and difficulty. We also don't really want to write all the putchar() codes, do we? 

Protocol Buffers: This seems really promising when I looked into it. It's basically a language-neutral, platform-neutral, extensible way of serializing structured data for use in communications protocols, data storage, and more, developed by Google. Everyone should read over the documentation. 
https://developers.google.com/protocol-buffers/docs/overview?hl=vi
The advantages are that it's somewhat human readable, compact (it's said to be more compact than XML and JSON), language neutral so compatible, have extensive libraries to do the serialization step for us (though mostly for C++) and very defined format (so we don't need to think of one?) (and perhaps providing skills that are quite "resume-able"? yes I just said "resume-able"). I even found a library that takes care of the automatic serialization part for C, so we may not have to even do this part.
https://github.com/protobuf-c/protobuf-c

The disadvantage is that I have no idea how this works, from creating the proto file to serializing it. It has really a specified format that we have to all learn. It may be more complicated than we expected, but I definitely think the coding team should make this one of their main formats to explore.

Another similar format is FlatBuffers, essentially Protocol Buffers but less human readable but better for game development? Protocol Buffers has neither optional text import/export nor schema language features like unions. It is said to be well-liked by the game development community. Definitely should give it a check.
https://google.github.io/flatbuffers/index.html#flatbuffers_overview

Generally, I think we should explore options like msgpack, Protocol and Flat Buffers more rather than the alternatives.

Some useful links to read on serialization:
https://softwareengineering.stackexchange.com/questions/168535/serializing-data-structures-in-c

https://en.wikipedia.org/wiki/Serialization

**Comment by ellynliu** [comment]
UBJSON stands for universal binary JSON, so it should definitely work with C, as they've tried to make it as universal as possible. The first link makes UBJSON seem pretty easy to use, and the second link contains a straightforward example of JSON (human readable) translated into UBJSON.
[http://ubjson.org/](http://ubjson.org/)
[http://ubjson.org/type-reference/](http://ubjson.org/)

Pros:
I think UBJSON would be relatively easy for us to understand and pick up. For each "thing" we want to pack into binary, there is one simple command:
[type, 1-byte char]([integer numeric length])([data])
We would use this command for all data types. The first link explains this in more detail but it seems easy enough.

Cons:
I'm sure there is a way to unpack data with UBJSON but I couldn't find a tutorial on their website. 
While there is a ton of support and documentation for JSON, I did not see as many for UBJSON while I was researching.

**Comment by jonahdf** [comment]
[Here's ](https://en.wikipedia.org/wiki/Comparison_of_data_serialization_formats#Comparison_of_binary_formats) a good table for comparing binary serialization formats. Tomorrow I'll look more thoroughly in how to actually implement protocol buffers and if any other formats from this table seem intriguing.

**Comment by jonahdf** [comment]
[How to use FlatBuffers in C](https://google.github.io/flatbuffers/flatbuffers_guide_use_c.html)
[Protocol buffers in C](https://github.com/protobuf-c/protobuf-c)

**Comment by jonahdf** [comment]
I completely agree with Jarvis: we should really only consider flatbuffers, protocol buffers, and msgpack. I think Christian and Sheryl should really focus on how intuitive each format is, and maybe both of them do two, and we repeat whichever one seems the best.

The link I attached for FlatBuffers has helpful sample code, and great documentation. It is also often used for game development, as Jarvis mentioned. For FlatBuffers, you must first make something called a schema file which is actually quite similar to C, which is nice. In addition, all the sample implementation center around games, which is very helpful. [Here is a tutorial](https://google.github.io/flatbuffers/flatbuffers_guide_tutorial.html), and [here is a helpful sample in C](https://github.com/dvidelabs/flatcc/tree/master/samples/monster). It seems very doable.

The link I attached for protocol buffers is the repository for protobuf-c, the C implementation. It includes a [wiki](https://github.com/protobuf-c/protobuf-c/wiki) with [examples (https://github.com/protobuf-c/protobuf-c/wiki/Examples). It all revolves around a C library. Similar to flatbuffers, you have to create and compile a file (although not schema, it is a .proto), specifying the structures. Unfortunately, this wiki for the C variant does not seem to be as complete as the flatbuffers one, even though protocol buffers is more popular from what I can tell.

From what I've read, Flatbuffers seems by far the easiest to use, with the most comprehensive documentation for c, and most specialized for game development. I will look into msgpack next.

**Comment by jarvislam1999** [comment]
Hi everyone, after some further research and at the suggestion of Mark at the office hour, it seems clear that we should move away from formats such as Python pickle format and UBJSON and towards Protocol Buffers or MsgPack. In short, I think the coding team should work on writing samples in Protocol Buffers and MsgPack, and perhaps Flat Buffers if there's time. Personally, both Mark and I are big fans of Protocol Buffers and I will try to explain why below:
- The size of the save file and the serialization speed of Protocol Buffers are way faster than most of our other formats. As these are important factors that go into the judging of our product, this already restricts our choice down to protobuf, msgpack, and flatbuf.
- There is extensive documentation on how to use protobuf and codes online that can give good examples, which is not true for flatbuf. From what I have seen, coding with protobuf seems relatively simple compared to what we have to do if we use UBJSON. Also, the process is fairly human readable, so no putchar(), getchar(), malloc() (Yay!) We can literally have certain structs automatically serialized by only writing them and call serialize(struct). We do still have to do some designing though, but it would be much simpler than designing our own custom serialization format from scratch.
- There's already code on Github that automatically serialize and deserialize protobuf into C, which neither msgpack or flatbuf have. (maybe I'm wrong but we will see)
- According to Mark, protobuf supports more data types than msgpack. As you can see on their documentation page, their protofile format is also quite C-centric.
- Also according to Mark, protobuf is a highly resume-able skill, perhaps the only one that we may end up using beyond this class. He said dealing with protobuf besides the skill itself also helps us learn more about API and apps which I would love to learn how to do. Personally, I have seen too many times how Python codes on the Internet have "import protobuf". I don't know what those actually do but I'm swayed.

That being said, we should still look into flatbuf and msgpack. Mark said flatbuf are way more niche but it may fit own purpose.

**Comment by jonahdf** [comment]
[Here](https://github.com/msgpack/msgpack-c/wiki/v2_0_cpp_overview) is the wiki for msgpack-c. It includes extensive guides for configuring, packing, unpacking, etc. This also definitely has better documentation for C than protobuf from what I can tell, and seems to simplify the packing/unpacking process more than flatbuf, but may not have as many supported structures/features.

[Here](https://developers.google.com/protocol-buffers/docs/tutorials) is the regular documentation for protocol buffers, which is great and fits all our purposes, but we would have to translate from C++ to C, since there is no official documentation for C. We could definitely figure it out though.

**Comment by ellynliu** [comment]
We decided to use protocol buffers due to the general widespread use of protobuf and its relative simplicity. Packing and unpacking is very fast, the file is somewhat human readable despite being in binary, and the .proto file seems very useful to organize the structs and data on a higher-level. In comparison to code written in msgpack, code in protobuf is easier to understand, as you do not have to pack each piece of data individually as in msgpack.

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Excellent work! This is a model issue.
