### ISSUE TITLE
Incorporate speed depending on NPC Player Class into NPC indefinite movement in auto_gen_movement()

### ISSUE THREAD

**Issue by jroven** [uchicago-cs/chiventure#1306]
NPC indefinite movement paths should be dependent on speed attributes associated with their specific class. Right now the time the NPC spends in each room is completely random, so the min and max times should change based on the class. We will determine how to access playerclass stats through the hash table and come up with a viable strategy to convert the speed stat into a multiplier that affects the minimum and maximum times NPCs on an indefinite movement path spend in a room.

**Comment by jroven** [comment]
Update after team meeting on 5/9: We are addressing the roadblock of understanding the player class stats hash table. We will familiarize ourselves with the structure and then add in the speed stat as a multiplier to the min and max random times the NPC will remain in the room in auto_gen_movement().

**Comment by bvvill** [comment]
> Update after team meeting on 5/9: We are addressing the roadblock of understanding the player class stats hash table. We will familiarize ourselves with the structure and then add in the speed stat as a multiplier to the min and max random times the NPC will remain in the room in auto_gen_movement().

I think all we would need to do is something like `HASH_FIND(hh, npc->class->base_stats, "speed",  5, stats_t speed)` and that will set `speed` to be the `stat_t` struct for the speed of the class of the npc. After that we just have to decide which value (either `val` or `max`) we base the multiplier for an NPC's time in a room.

**Comment by bvvill** [comment]
> After that we just have to decide which value (either `val` or `max`) we base the multiplier for an NPC's time in a room.

Right now I'm thinking the multiplier would equal 100 divided by whatever the speed stat is, such that if the speed stat was 50 the NPC would spend twice as much time in each room then they would if their classes' base speed stat was 100. If that's too drastic then we could probably do the sqrt of it (100 / speed) or something.

**Comment by Vincent-Zhang4135** [comment]
Me and Jonathan have been trying to implement a multiplier on the minimal times spent. However, after many build attempts, we have hit a roadblock mainly due to the fact that we aren't too sure how to utilize the uthash header file. In particular, we tried using the HASH_FIND() function to find and return as an out parameter the speed stat. However, this had led to build fails, most likely to they incorrect parameters we are passing in.

We theorize that it might have something to do with the keys, but have reached out to Lily in hopes of resolving this road block.

**Comment by Vincent-Zhang4135** [comment]
Jonathan and I finally got a successful build after trying to incorporate speed stat multiplier into `auto_gen_movement()` in npc_move.c. We worked on this in a paired programming method by meeting up remotely to work on the coding together. 

We researched into the stats hash table as per Lily's suggestions, and realized we can use this stats hash table function found in stats.h in game-state to change the speed multipliers, and implemented this into `auto_gen_movement()`. However, because the Test case for `Test(npc_mov, auto_gen_movement_indefinite` was not written for this change, it crashed. We decided that this can be a separate task of adjusting the test to work for our new implementation/feature, and will close this issue now.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! Ordinarily, an issue associated with a PR shouldn't be closed when the PR is opened, but when the work associated with that issue is done (i.e., when the PR is complete and merged).
