### ISSUE TITLE
update the openworld module to incorporate new speclist struct type (adjacency matrix)

### ISSUE THREAD

**Issue by lukasg8** [uchicago-cs/chiventure#1318]
Our task is to work through all the functions in the openworld module, most importantly autogenerate.c, to be able to work with new speclist_t struct.

**Comment by williamhu314** [comment]
After manually going through all instances of speclist that appear in the modules, we have concluded that the only things we need to do are to change any instances of speclist to specgraph and to make new, init, and free functions for specgraph, replacing the current new, unit, and free functions for speclist. We will do that, in addition to other manipulation functions, in #1325. We will also have to eventually fix the tests but we will do that later.

**Comment by williamhu314** [comment]
One thing we need to do is update specgraph in utlist so that the code can compile.

**Comment by williamhu314** [comment]
I have fixed the random room lookup function for specgraph functionality. I commented out the speclist_from_hash function since it doesn't really apply to specgraphs and we will probably have to redo the function if we want that functionality later. That function is also causing compilation errors right now. I also commented out the filter_specgraph_with_difficulty function for now since fixing this will require a lot of work as the code for spec_list is not very useful for specgraph. We will work on such a function, if needed, when we work on level-oriented autogeneration. All level-oriented functions have also been commented out for now since we will need to fix those later to accomodate a specgraph.

**Comment by williamhu314** [comment]
I am now commenting out tests that are causing compilation issues and that we will need to rewrite in a later issue. These currently include all functions in the autogenerate and specgraph suites since those rely on the specgraph struct and involve creating a specgraph within the test.

**Comment by williamhu314** [comment]
Write now all functions and tests causing problems with compilation have been commented out or fixed. For the commented out ones, we will now identify the functions where we would like to implement a new version that supports the specgraph struct in future issues.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work! As always an excellent set of updates, and overall exemplary issue.
