### ISSUE TITLE
Create WDL Format for openworld 

### ISSUE THREAD

**Issue by rohandeme** [uchicago-cs/chiventure#1329]
For the first stage in a 3-part process of making the openworld module WDL-compatible, we are making a format for how openworld components will appear in a WDL file. This will allow us to move on to the next stage of the process, where we will design a load_openworld.c file that will create openworld structs/objects from a WDL file.  

In this stage, we plan to:
create an example WDL file that demonstrates the format for an openworld component
create a wikipage for using the openworld class that includes the sample file and provides details about the openworld attributes

**Comment by rohandeme** [comment]
We have finished creating the WDL format for Openworld attributes. We have created a wiki page called "Openworld ~ Loading OpenWorld Attributes from WDL" that contains information on how the Openworld object will appear in WDL and its various attributes.  The next step in this process will be to use this information to design load_openworld.c/.h files in the WDL module.

**Comment by philipchenaux** [comment]
Issue Score: Satisfactory

Comments:
Great work! I have one comment, however, that your issue did not include any status updates between the opening of the issue and the closing of the issue (and this issue was not small enough to justify having no status updates at all). If you make any intermediate progress before finishing the task, then it should be documented on the GitHub issue via a comment.
