### ISSUE TITLE
Refactor code into interface/internal

### ISSUE THREAD

**Issue by a-matai** [uchicago-cs/chiventure#133]
//left for @patrickkoopmans to fill out

**Comment by patrickkoopmans** [comment]
Summary thus far: 
In this issue, I have refactored the code which referenced game-state's use of internal hash tables into several common.h files (room-common.h, item-common.h) so that the hash table functionality is abstracted away from game-state's public facing interfaces. The motivation behind this issue was to reduce the cognitive load of the existing interfaces so that other teams would not need to understand, nor feel pressured to use, our hash-table referencing functions. These functions are crucial to internal functionality, primarily to iterate through the hash data structs which primarily store rooms, items in rooms, and items on players. 

Summary of refactoring: 
common-room.h, common-player.h, common-item.h, common-path.h created in the game-state/src directory

int add_room_to_hash() and int delete_all_rooms() moved from room.h to common-room.h
int add_player_to_hash() moved from player.h to common-player.h
int add_item_to_hash() and int delete_all_items() moved from item.h to common-item.h
int add_path_to_hash() and int delete_all_paths() moved from path.h to common-path.h

Todo: 
Figure out what needs to be changed in the Makefile and ensure all .c/.h files include the relevant new common files.

**Comment by a-matai** [comment]
Update:

Through the actual bug-fixing and abstraction process, we have removed most functions that relate to add_*_to_hash and worked the implementation into those functions.

delete_all_functions that are used in free-ing have not been updated in the same way and still take in hashtables.

**Comment by patrickkoopmans** [comment]
In the process of resolving Issue #137 , we realized that we had to refactor the add_item_to_hash() code into two separate functions: add_item_to_room() and add_item_to_player(), which were existing functions within the room and player modules respectively that called on add_item_to_hash().

**Comment by patrickkoopmans** [comment]
Closing Comments: 

This task is complete because we have removed all mention of hash tables in our public interfaces, and resolved all dependency issues in our refactoring of code. In testing all of our modules, we came to realize some of the hash-table-relevant code was not as abstract-able as previously thought, and we had to refactor code that was formerly shared between multiple functions.

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Good updates and closing statement. It would have been good to see a few more finer-grained updates before your first one. Also, the title is a bit vague and the summary is not filled out.
