### ISSUE TITLE
dsl: Algorithm for verifying validity of NPC dialogue graphs

### ISSUE THREAD

**Issue by awliu2** [uchicago-cs/chiventure#1342]
NPCs have their dialogue and dialogue options stored as graphs. We want to test these graphs and make sure that there are no closed loops, that there are no unconnected nodes, etc.

Assigned to Jay, William, and Alex

**Comment by alexlee0422** [comment]
Here is a example NPC dialog graph: https://docs.google.com/document/d/1aq3eS4vwEB0Agioyb8GoEEdNdueOPAV1j1sxQsdfVTQ/edit

**Comment by wzeng0** [comment]
In terms of checking the validity of the NPC dialogue graph, we were thinking that since there are multiple paths, we should just iterate through the graph given a dialogue case. If it does not reach a certain node at the end, then we claim that the dialogue graph is invalid. In the case of checking whether any situation leads to a closed loop, we want to store the dialogue path locally and check whether the next dialogue brings us back to a previously visited node.

**Comment by wzeng0** [comment]
In terms of checking the validity of the NPC dialogue graph, we were thinking that since there are multiple paths, we should just iterate through the graph given a dialogue case. If it does not reach a certain node at the end, then we claim that the dialogue graph is invalid. In the case of checking whether any situation leads to a closed loop, we want to store the dialogue path locally and check whether the next dialogue brings us back to a previously visited node.

**Comment by jhsivadas** [comment]
Created a Google Document to brainstorm more algorithm verification ideas.

https://docs.google.com/document/d/1mmIpR3MYopZLQu4FrRfVQUr6Dh-hMiTPvfsmXOOhrqY/edit?usp=sharing

**Comment by jhsivadas** [comment]
Brainstormed more potential algorithms different levels of time-complexity per situation. We outlined 3 potential algorithms below:

**Algorithm 1**
In terms of checking the validity of the NPC dialogue graph, we were thinking that since there are multiple paths, we should just iterate through the graph given a dialogue case. If it does not reach a certain node at the end, then we claim that the dialogue graph is invalid. In the case of checking whether any situation leads to a closed loop, we want to store the dialogue path locally and check whether the next dialogue brings us back to a previously visited node.

**Algorithm 2**
Another algorithm design will involve only checking the possible paths given a single user input. This algorithm will take a node as an input (based off a user dialogue choice) and run a graph validation algorithm on all possible routes following that subsequent node. The goal of this algorithm would be to limit the total runtime (as you would not have to run the validation on every node in the graph) for a lower number of node inputs. If the algorithm successfully reaches an end node then the algorithm returns a successful pass. If it reaches an invalid node the algorithm will fail. 

**Algorithm 3**
Another algorithm design we can use is to count the number of nodes that reach any end scenario and match to see whether or not it matches with the total number of scenarios possible. If not, it is not a valid graph.

**Comment by jacknugent1529** [comment]
Issue Score: Satisfactory

Comments: Solid work on this issue! The updates are thorough, but avoid using google docs and instead try to use wiki pages or the comments on an issue. Additionally, be sure an issue is finished before closing it.

The PR grading page gives an explanation for why to avoid google docs:
> While using Google Docs to sketch out some of the documentation, you should avoid posting links to those Google Docs from an issue, as it may cause confusion as to whether that document (or some future update to the wiki) is the most up-to-date version of that documentation. You should instead transfer the contents of the document to the wiki, and then link to the wiki when updating the issue.
