### ISSUE TITLE
dsl: write a design document for dsl skill tree support

### ISSUE THREAD

**Issue by awliu2** [uchicago-cs/chiventure#1345]
We want to support the player skill trees provided by the skill trees model. Thus we need to design the grammar rules and conversion rules involving skill trees. Furthermore, communicate with the skill trees group to see if they have any updates, and if they are using libobj (more info [here](https://github.com/uchicago-cs/chiventure/wiki/Accessing-data-in-a-JSON-WDL-file)).

**Comment by baigh1** [comment]
Created a preliminary design document to get started. https://docs.google.com/document/d/1YLpbbgSjUesqp8583i1A0wRJ4w0ZX_zJ9lQjm5MlUaQ/edit?usp=sharing

**Comment by baigh1** [comment]
``` 48 /* An INDIVIDUAL skill, belonging to a player */
 49 typedef struct skill {
 50     // The skill ID that uniquely identifies the skill
 51     sid_t sid;
 52
 53     // The skill type
 54     skill_type_t type;
 55
 56     // The name of the skill
 57     char* name;
 58
 59     // The description of the skill
 60     char* desc;
 61
 62     // The player's current level of the skill
 63     unsigned int level;
 64
 65     // The player's current experience points associated with the skill
 66     unsigned int xp;
 67
 68     // The maximum level to which the skill can be upgraded
 69     unsigned int max_level;
 70
 71     // The minimum number of experience points needed to level up
 72     unsigned int min_xp;
 73
 74     // The pointer to the linked list that contains all the effects that a skill can have
 75     effect_t* skill_effect;
 76
 77 } skill_t;
```
 
In player classes, we have the following WDL representation:
EXAMPLE:

```
{
"GAME": { ... },
"CLASSES": {
"Knight": {
"short_desc": "Knight's short description",
"long_desc": "Knight's long description",
"attributes": {
"noble": true,
"hot-headed": true
},
"base_stats": {
"health": {
"current": 100,
"max": 200
},
"mana": {
"current": 20,
"max": 100
}
},
"effects": null,
"skill_tree": null,
"starting_skills": null
}
}
}
``` 

As we can see, there is a skill_tree section, along with starting_skills.
 
Based on the current status of the skill-trees team in terms of a WDL implementation, their ideas are in a very high-level state.
 
https://github.com/uchicago-cs/chiventure/wiki/Skill-Trees-~-Potential-Integration-with-existing-WDL
 
They also wish to update the existing ITEM and ROOM classes so that once a certain skill is obtained, they might “unlock” use of that item.
 
“Rooms
Rooms have a 'connections' attribute, a list of rooms that can be entered from the current room. Such a list may be able to be manipulated in order to prevent a user from accessing certain rooms until they have progressed far enough in a certain skill tree. This may require collaboration with the WDL team to alter "locked rooms" and other restrictions.
Items
Items have an 'actions' attribute, a list of available actions that the user can perform on / with the item. Adding skill-specific actions to this attribute can allow us to create skills that transform items, expend items, etc.“

Currently skill_trees is not in a state such that we can implement it.

**Comment by baigh1** [comment]
After contacting the skill-trees team, we they confirmed our beliefs that there is no WDL to DSL implementation we can do currently. Their thoughts on possible integration are listed here:
https://github.com/uchicago-cs/chiventure/wiki/Skill-Trees-~-Summary-of-Skill-Tree-Integration-2022

**Comment by baigh1** [comment]
Overall, for this task we have investigated the current state of skill-trees. While much progress has been made in terms of their implementation, they currently are in very elementary integration with the WDL/JSON format. As such, on the DSL team's end, there is very little we can do to move forward with this team.

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Great work on this issue! Even if it didn't turn out as you might have hoped, it will be useful as documentation for future teams.
