### ISSUE TITLE
Add an NPC flag for class structs

### ISSUE THREAD

**Issue by wellingtj** [uchicago-cs/chiventure#1346]
Potentially slap a flag in the class struct to indicate this is an NPC being represented by the struct. It would be a simple boolean that is something like bool is_NPC? and would go in class_t. The functions using class_t would need to be adjusted accordingly. This has been requested by the NPC team

**Comment by wellingtj** [comment]
The tests fail due to a memory error, but the examples build so I will fix the tests tomorrow

**Comment by wellingtj** [comment]
I have basically done this code, you can reference this branch, but I dont think this is an issue worth completing, or pulling at the moment. All that needs to be done to finish this branch is to fix merge conflicts and to fix testing for the npc module.

**Comment by lilyehsani** [comment]
Issue Score: Satisfactory

Comments:
Great work! Two comments:
1. For a task of this size, we would've expected to see more status updates and/or status updates that were more detailed.
2. The issue was closed before it was actually done. Since the code was not pulled, the issue should have either been moved to the backlog or linked to a new issue about getting the code pulled.
