### ISSUE TITLE
Finalize delete-quest functionality

### ISSUE THREAD

**Issue by jakeziqiwei** [uchicago-cs/chiventure#1350]
After writing all the code for the delete-quest function, we need to finally go through and test it.

**Comment by elizabethli31** [comment]
We wrote two remove quest functions (one that removed one quest from the hash table and another that removed all quests from the hash table). For this issue, we struggled with testing because the previous hash table functions written last year were not properly tested, so we also wrote tests for all of the hash table related functions (add_quest_to_hash and get_quest_from_hash). This issue is linked to pull request #1363
