### ISSUE TITLE
Create a design document for the battle_item_t struct improvements and also add armor/equipment.

### ISSUE THREAD

**Issue by nicholaswlee** [uchicago-cs/chiventure#1355]
We will create a design document for a new battle_item_t struct and a specialized battle_equipment_t type of battle item.

Members: Nicholas, Angela, Fatimah

**Comment by aliu65803** [comment]
We have created a wiki page with the design document for a battle_equipment struct and a more updated battle_item struct. It is linked [here.](https://github.com/uchicago-cs/chiventure/wiki/Items-~-Equipment-~-Design-Document)

**Comment by aliu65803** [comment]
We have decided to change combatant_t and create equipment_type_t.

**Comment by corian-jal** [comment]
We have finished the design document for changes and additions to battle items [here](https://github.com/uchicago-cs/chiventure/wiki/Items-~-Equipment-~-Design-Document). After the move_t pull request is approved, we will start implementation and submit a pull request after the run_turn_component pull request has been completed.

**Comment by lilyehsani** [comment]
Issue Score: Satisfactory

Comments:
Great work! Two comments:
1. The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/issue-pr-grading.html#descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
2. For a task of this size, we would've expected to see more status updates and/or status updates that were more detailed.
