### ISSUE TITLE
Tests for Player Module

### ISSUE THREAD

**Issue by a-matai** [uchicago-cs/chiventure#136]
Write criterion tests for all functions in our player (including common-player) module and fix broken functions returning an unexpected result.

**Comment by jessxia** [comment]
Wrote tests for player_new, player_init, player_free, and some of the get/change functions in the player.h module. Also added to the description of the player_init function in player.h to reflect that it initializes player level to 1 and experience to 0.

**Comment by jessxia** [comment]
All tests passing except for ones that involve adding items/players to a hash table. It is crashing/failing the test because after the function call the hash table still remains NULL.

**Comment by jessxia** [comment]
Pushed the game-state/player-tests branch into game-state/dev because there were changes being made to our hash table functions and too many dependencies on other modules. Add_player_to_hash() was altered to become add_player_to_game() and refactored into game.c. This was due to changes to internal use of the hash table functions to address the above-mentioned issue. Player_init() and player_new() were changed to be formatted consistently with the other modules' init and new functions. The tests were changed accordingly. 

Note: since WDL does not yet support player_id in their specifications, we will be calling player_init() with "1" as the player_id (to be used as the hash table key) since there is only one player. We are leaving the player hash table for future use if we decide to support having multiple players.

**Comment by liuyifan-eric** [comment]
The hashtable of players is not fully freed: contents in each player struct is not freed.
Need to re-adopt delete_all_players (although we only have 1 player right now)

**Comment by jessxia** [comment]
Added in a test for delete_all_players(). Changed the function itself to return SUCCESS (to match its documentation).

**Comment by jessxia** [comment]
To address Yifan's comment: player_free, which is called by delete_all_players, now frees player_id.

**Comment by jessxia** [comment]
For this issue, tests for all functions within our player module were written to test their functionality. This revealed issues with our use of HASH_FIND_STR and HASH_ADD_STR in our adding to hash table functions (specifically add_player_to_game for this module), which now use HASH_FIND and HASH_ADD_KEYPTR. Now our functions can take in structs rather than needing to pass in hash tables! 

Player_new and player_init were changed to take in different arguments in order to be consistent with our other new/init functions. Player_id is now passed in to player_init and space is malloced for it there and later freed by player_free. More tests will be written later as/if the player module expands.

**Comment by jessxia** [comment]
For this issue, tests for all functions within our player module were written to test their functionality. This revealed issues with our use of HASH_FIND_STR and HASH_ADD_STR in our adding to hash table functions (specifically add_player_to_game for this module), which now use HASH_FIND and HASH_ADD_KEYPTR. Now our functions can take in structs rather than needing to pass in hash tables! 

Player_new and player_init were changed to take in different arguments in order to be consistent with our other new/init functions. Player_id is now passed in to player_init and space is malloced for it there and later freed by player_free. More tests will be written later as/if the player module expands.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Good work! Nice job with the progress updates. In the summary it might have been good to specify which functions were broken.
