### ISSUE TITLE
GUI: Write Wiki pages for GDL (graphic description language) and brainstorm GDL features

### ISSUE THREAD

**Issue by imadejski** [uchicago-cs/chiventure#1366]
Plan out graphical description language (GDL) which would allow authors to customize aspects of how their game is represented.

**Comment by imadejski** [comment]
https://github.com/uchicago-cs/chiventure/wiki/Graphics-~-GDL
Wiki created and written about GDL language and plan for it with example. Gabe and I consulted about the current feasible tools we could implement with GDL right now and ones that would be useful for the future.

**Comment by philipchenaux** [comment]
Issue Score: Satisfactory

Comments:
Great job, but I have two main comments:
1. The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/issue-pr-grading.html#descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
2. When an issue is done, you should include a final comment summarizing what was done, and why the issue is being closed.
