### ISSUE TITLE
Quests: Rewrite free functions to ensure no memory issue

### ISSUE THREAD

**Issue by jakeziqiwei** [uchicago-cs/chiventure#1369]
After going through the documentation, we realized that the quest structures weren't freed properly which was causing issues for some functionality. We will need to through and write free functions that properly free each structs properly. 

1 - mission 
2 - quest 
3 - tree 
4 - reward

**Comment by elizabethli31** [comment]
We decided that the mission struct is properly freed because we should not be freeing the items or NPCs related to them (also the mission struct was completed rewritten to no longer include the actual NPC struct). The quest struct does not properly free the task tree which was causing memory leaks. For this issue, we wrote the proper task_tree_free function but the tests were not passing because the find_parent function called by add_task_to_quest was not implemented properly.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great work, but next time I would like to see a brief explanation as to why the initial data structures were not freed properly (i.e. what was incorrect with the original code), as this can be useful for reference.
