### ISSUE TITLE
Creating tests for new playerclass preset prefab 

### ISSUE THREAD

**Issue by katie-gao** [uchicago-cs/chiventure#1370]

**Comment by katie-gao** [comment]
Van and I are now creating tests for the previously written To dos for the player class preset pre-fab classes. We also made a quick edit from check_field_pressence to check_field_presence in the testing files (more accurate spelling).

**Comment by katie-gao** [comment]
We have finished writing tests for the preset prefab classes and have pushed the changes to the git branch playerclass/add-prefabs.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! Two comments:
1. For a task of this size, we would've expected to see more status updates and/or status updates that were more detailed.
2. Ordinarily, an issue associated with a PR shouldn't be closed when the PR is opened, but when the work associated with that issue is done (i.e., when the PR is complete and merged).
