### ISSUE TITLE
Reaching out to the skill-trees team to understand their functions and ask about the NULL parameters in playerclass preset prefab

### ISSUE THREAD

**Issue by katie-gao** [uchicago-cs/chiventure#1371]
Van and I plan to reach out to the skill-trees team to ask questions about the skill_new function with the NULL parameter. We were thinking we could work with the skill-trees team and improve this function, so that we can have more info provided instead of a NULL, and overall more functionality.

**Comment by katie-gao** [comment]
Van and I plan to reach out to the skill-trees team to ask questions about the skill_new function with the NULL parameter. We were thinking we could work with the skill-trees team and improve this function, so that we can have more info provided instead of a NULL, and overall more functionality.

**Comment by katie-gao** [comment]
Van has reached out to the skill-trees team earlier in the week, but have had no response yet. We hope to meet with them this week.

**Comment by katie-gao** [comment]
Notes from the meeting:
- skillstree team seems about the same as what they were doing
- function is for complex skills
- each character gets skill id 
- effect.c has effects and etc. 
so basically we’re going to merge what we have
and they’re going to do druid, elementals, knight, and sorcerer
We’re going to stick with what we did
could do the additional changes

The wiki page is also now updated to match the work both teams have done. 
https://github.com/uchicago-cs/chiventure/wiki/Player-Class-~-Example-Stats-and-Abilities.

**Comment by vanolson** [comment]
We reached out to the skill-trees team, and I had a zoom meeting with Arya and Kabir to discuss how we wanted to approach our prefab additions. It turned out that we were working on very similar parts of the prefab skill-trees, so we decided to use our additions to the existing TODO'd classes in the module, while the skill trees team would add some new classes and create skill trees for them. We'd each create testing for our trees. In addition, we talked a little about the NULL function argument in the skill tree creation function, but we will likely need to talk about that more as we display these classes in the demo. The information discussed and split up has now been done and updated on the wiki page: https://github.com/uchicago-cs/chiventure/wiki/Player-Class-~-Example-Stats-and-Abilities.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! The title of an issue has to convey what the issue will be producing. In the future, try using simple titles with a "Verb-Object" structure that clearly states what you will be doing in the issue (e.g., “Design and implement a ‘circle’ module”, “Research libraries for drawing simple geometric shapes”, etc.)
