### ISSUE TITLE
GUI: Editing item_t struct

### ISSUE THREAD

**Issue by dhirpalshah** [uchicago-cs/chiventure#1375]
Currently, the item struct looks like this:
`typedef struct item {
    UT_hash_handle hh; //makes this struct hashable for the room struct (objects in rooms) and player struct (inventory)
    char *item_id;
    char *short_desc;
    char *long_desc;
    game_action_hash_t *actions;
    attribute_hash_t *attributes; // a hashtable for all attributes
} item_t;`

But, there is no place for the image of the item that the game developer can input. Because we plan to be able to implement the inventory display by looking at the item struct and finding the respective file path to an image, we want to include another element in the struct, something like `char* item_image;` that would be a file path to a png/jpg.

**Comment by KendrickXie** [comment]
Created branch for implementation ```1375-editing_item_t_struct```
Access with:

```git fetch origin```
```git checkout 1375-editing_item_t_struct```

**Comment by KendrickXie** [comment]
**Closing Statement**
The element mentioned above, ```char* item_image``` has been added to ```item_t```. In addition, ```unsigned int* inventory_x_pos``` and ```unsigned int* inventory_y_pos``` have been added to the ```item_t``` struct in order to hold the x and y coordinates of an item within an inventory. In the future, we may need a separate function to allocate these elements, but it is not done in the current initialization functions, because not all items will be using these elements meant for use by the graphics team.

Kendrick made the changes to the code, but the ideas were generated by the other members assigned to the issue.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job on this issue, good summary and closing statement!
