### ISSUE TITLE
Tests for Path Module

### ISSUE THREAD

**Issue by a-matai** [uchicago-cs/chiventure#138]
Tests for path module.

**Comment by liuyifan-eric** [comment]
As mentioned in #158, Macros for iterating the hashtables (that being said, users do not need to know we are using hashtables) are not tested yet. We need to test ITER_ALL_PATHS, and ITER_ALL_CONDITIONS, specifically.

**Comment by liuyifan-eric** [comment]
Implemented tests for ITER_ALL_PATHS. (tests passed)

Just noticed that we haven't done conditions yet (because we need more discussion with other teams) so we just leave all the condition stuff for now.

**Comment by liuyifan-eric** [comment]
Closing comment:
This issue was about writing a lot of tests for functions and macros, and fixing bugs.
The tests we include in test_path.c:
- new
- free
- add_to_room
- search
- find_room
- del_all
And one that is also related to the path module, but implemented in test_room, because a room struct is required:
- iter_paths
Which tests the ITER_ALL_PATHS macro. (This macro was originally in path.h but we have merged that file into room.h)

Hopefully this module will work without bugs in the future :)

**Comment by lydiafilipe** [comment]
Issue Score: ✓-

Comments:
Good work on the closing statement and some of the updates. I think the summary could be a bit more detailed and not just be the title. Maybe mention what functions, and link the module. Also, it looks like there are not enough progress updates given all the commits that were going into this. What bugs were you encountering? How did you fix them? What tests were you writing/finishing at a given point? The only progress updates were for the macros but there were other functions being worked on.
