### ISSUE TITLE
add capability of searching for roomspec_t from room_t

### ISSUE THREAD

**Issue by lukasg8** [uchicago-cs/chiventure#1392]
Discussion with Helena made us realize that in order to verify if we can connect two rooms during autogeneration, we need to be able to relate a room_t struct with its roomspec_t struct because the relationships between rooms are stored in specgraph_t which is an adjacency matrix of roomspecs and not rooms.

**Comment by lukasg8** [comment]
Issue #1351 addresses this functionality by adding a tag to the room_t struct. This tag is a number which is defined by the roomspec_t the room_t struct was generated from. The number of the tag matches the position of the roomspec_t struct in the list of roomspecs found in the specgraph. 

For example, if room1 was generated from the 5th element in the roomspecs list in specgraph, room1 would contain a tag with the number 4 (index from 0). This allows for dynamic integration because even if all the rooms in the game are currently formed, as the player reaches the edge of the map, new rooms will need to be formed dynamically from roomspecs. The tag allows us to check existing rooms with new rooms (their relationship in the adjacency matrix). 

The implementation of this feature can be found in this PR: #1399

**Comment by philipchenaux** [comment]
Issue Score: Satisfactory

Comments:
Great job on the issue, however your issue did not include any status updates between the opening of the issue and the closing of the issue (and this issue was not small enough to justify having no status updates at all). If you make any intermediate progress before finishing the task, then it should be documented on the GitHub issue via a comment.
