### ISSUE TITLE
Write functions to read rooms from the WDL file and create rooms in game state

### ISSUE THREAD

**Issue by Kate32815** [uchicago-cs/chiventure#140]
Use a combination of functions from the room and game modules of game_state/dev and the libobj functions to load the given rooms and connections from a libobj document object into a game_state game struct.

**Comment by mewthew** [comment]
Updates: 
We have finished designing and implementing functions that will load rooms, short descriptions, long descriptions, and connections into a game_state game pointer. We will discuss our code with the entire team to communicate our thought process and decide if this is the right thought process going forward.

**Comment by mewthew** [comment]
Update:
Changed title/summary given our change in direction with the implementation of loading into game_state structs (via Borja's instruction)

**Comment by mewthew** [comment]
We have created two functions: 
1. `add_rooms_to_game`, which accesses a libobj document object, obtains the list of rooms and their attributes, and parses them into the game-state structs (returns a game pointer)
2. `add_connections_to_rooms`, which accesses a libobj document object, obtains the list of connections for each room, and parses them into the game-state structs (also returns a game pointer)

These two functions allow us to translate whatever is in a WDL file for rooms and turn them into game-state structs in the form of a game pointer, and the implementation can be found [here](https://github.com/uchicago-cs/chiventure/blob/wdl/load_rooms/src/wdl/src/load_rooms.c).

NOTE: these two functions rely specifically on the `create_connection`, which game-state has implemented via #163. The latest load_rooms branch does not have this code since it has not been pushed to master yet, thus our code does not yet compile correctly, which will be addressed as soon as game-state's PR to master is approved.

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Good work. However I would like to see more progress updates as you are writing the functions, not just once they are all done, and some more details on the functions.
