### ISSUE TITLE
dsl: implement graph verification algorithm for dialogues

### ISSUE THREAD

**Issue by wzeng0** [uchicago-cs/chiventure#1412]
This task is the next step following the research task from last week. We have identified 3 possible graph verification algorithms to implement, and this task is specifically focused on implementing Algorithm 1. Given a dialogue, we are attempting to check that this dialogue path is a valid one.

team members: Jay, Alex, Hira

**Comment by jhsivadas** [comment]
Created a google doc for code outline and brainstorm:
https://docs.google.com/document/d/1QGo6oYAvGDH9XW1Vgf_8ycJ7HYuCH6-9_mZI12FWqWI/edit?usp=sharing

**Comment by baigh1** [comment]
We created two files, one for example graphs (example_graphs.py) and one for the actual algorithm implementation (graph_validator.py). The first one contains 7 graphs, each one showcasing a different type of graph that would not be considered valid as a dialogue graph. We also had one graph that had no issues as our "normal" case. 

Graphs we created for each specific test case:
SELFLOOP INFINITECIRCLE INFINITELOOPLONG INFINITELOOP NODENOTREACHED SINGLETON VALIDGRAPH1 VALIDGRAPH2

If a graph is "valid", the return value will be TRUE, otherwise it will be FALSE. These tests can also be seen in the graph_validator.py.

**Comment by jhsivadas** [comment]
Updated with 10 tests checking different valid test cases as well, as well as invalid paths in a valid graph depending on starting node. 10/10 test cases have passed.

**Comment by alexlee0422** [comment]
In this task, we constructed an algorithm to test directed graphs and their validity since dialogues for NPC are to be in this form. It is important for us to do so because it would not make sense for the storyline of the game to not be able to reach a node or if an infinite loop will happen. This algorithm will catch these kind of errors and useful in the future when more stuff is implemented. (Task will be closed with the pull request)

**Comment by jacknugent1529** [comment]
Issue Score: Excellent

Comments: Nice work on this issue! The updates are very detailed, but, as mentioned previously, use github wiki pages or the issue discussion itself instead of google docs.
