### ISSUE TITLE
Quests: Write task_tree functions (new, init, and free)

### ISSUE THREAD

**Issue by elizabethli31** [uchicago-cs/chiventure#1430]
Currently, there is no function that allocates memory for the task tree. We will need to write a function and tests that makes this

**Comment by elizabethli31** [comment]
We wrote a task_tree_free function that recursively frees a task_tree and a test as well. The existing function that adds_task_to_quest does not seem to be properly implemented which is why the test is failing, so we have to go back and fix that.

**Comment by jakeziqiwei** [comment]
We have finished writing the functions. Throughout our conversation with the other team members, we realized that we only really needed the task_tree_free function since there were some design choices made to not free certain things. So that's the only function we ended up writing. We also found some errors with the some of the other tree functions, which we needed up fixing. We created a pull request now.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job on this issue!
