### ISSUE TITLE
Create Design Document for Demo

### ISSUE THREAD

**Issue by aliu65803** [uchicago-cs/chiventure#1445]
For this issue, we will create a design document for the battle demo. We would like to showcase our new run_turn_component and run_battle functions, as well as include different items, moves, and equipment to show the updated move_t, battle_item_t, battle_equipment_t, and stats_t structs.

members: Nicholas, Emilio, Angela

**Comment by nicholaswlee** [comment]
Angela, Emilio, and I have met up and discussed what we would like to see in the demo. We have outlined different example moves, items, and equipment that can highlight all the new features we have coded in. Another big thing we would like to showcase our runtime component.

**Comment by nicholaswlee** [comment]
We have decided that we will be using the examples from last year as a "base template" for our demo. We will be updating the data structures and fields as well as implementing run_turn_component.

**Comment by nicholaswlee** [comment]
The design doc can be found [here](https://github.com/uchicago-cs/chiventure/wiki/Battle-~-Demo-~-Design-Document).

**Comment by emiliolevinspage** [comment]
After some tweaks and added details, the design document is finished and the demo is ready to be implemented, inspired by the structure of past examples and using the design doc which details the moves and items that will be used as well as the structure of the turn that will show off the new turn component infrastructure. I am closing the issue because the document is complete and the work moving forward is implementation.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue!
