### ISSUE TITLE
Quests: Implement system for checking for quest completion upon entering a room or collecting an item

### ISSUE THREAD

**Issue by charlieweiler** [uchicago-cs/chiventure#1466]
We need to figure out how to check a quest completion automatically when you enter a room or collect an item. Additionally, we need to account for possible circular dependencies with Player. This issue should cover the implementation of all of these changes.

**Comment by Castel-Jaloux** [comment]
After discussion, we discovered that the best places to check for quest completion in these cases were in the add_item_to_player() and move_room() functions. These are the functions that are called when a player obtains and item or switches rooms respectively. As a result, adding the functionality to check quest completion into these two functions would be the optimal way to make sure that quest completion is detected as soon as possible.

However, there is a circular dependency issue. While the move_room() function is in game.h, posing no difficulties, the add_item_to_player() function is in player.h, which means it cannot access functions in the quest modules. This makes it impossible to call the functionality to check quest completion in that function as planned.

To solve this issue, we decided to move the add_item_to_player() function from player.h to game.h. Since add_item_to_player() takes a player parameter as one of its input arguments, this will not impact the internal handling of the method, especially since game.h includes player.h. There are some functions in other modules that call add_item_to_player(), but all of them include game.h in addition to player.h, so our changes will not cause dependency issues for other teams.

**Comment by JSerf02** [comment]
Implemented the new mission redesign which removes the NPC dependency from the quest module. This will make it so NPCs can now include quests while will vastly simplify NPC integration. Also, this new design is much neater and makes the code easier to read and write, which will be especially helpful for when we implement WDL parsing.

**Comment by JSerf02** [comment]
Added in an `update_player_quests()` function that can be called by other modules to complete other quests. Implementing this function had a complication where the quest module needed to know the current room, but that info is stored in the game struct which can never be accessed by quests. We fixed this by modifying the player class by adding a `crnt_room` string that we update for every player in the `move_room` function. This allows quests to access the current room through the player and also will help when multiplayer is sorted out more, since it's a little weird right now how there is only one current room and it's not player specific.

**Comment by JSerf02** [comment]
Modified `add_item_to_player()` and `move_room()` to call the `update_player_quests()` function so item acquisition and room entrance tasks will automatically complete when you collect the item/move to the room. This change required moving `add_item_to_player()` to game.h and adding a new `game` parameter, so we changed all calls to the function in other teams' files to account for this. After running many tests, we are 99% sure everything worked correctly and there are no errors! :)

**Comment by JSerf02** [comment]
We successfully implemented a system for checking quest completion on room entrance and item acquisition
