### ISSUE TITLE
Research TUI libraries

### ISSUE THREAD

**Issue by borjasotomayor** [uchicago-cs/chiventure#15]
Research a few libraries for building Text-based User Interfaces, possibly including libraries for building terminal-based games. For each library, we'll provide some pros and cons (and maybe some sample code).

Possible libraries to look into:
- ncurses
- SDL

**Comment by adomiter** [comment]
NCurses:

Basic info:
In c file: #include <curses.h>
To link: gcc -lncurses prog.c
(Source: http://www.cs.ukzn.ac.za/~hughm/os/notes/ncurses.html)

Explanation of where to get: http://www.tldp.org/HOWTO/NCURSES-Programming-HOWTO/intro.html#WHATIS

PROS:
- Broadly used library -> many documentation sites online, could make searching up common errors/questions easier
- Windows: can create multiple. Can handle terminal resizing
- Color: multiple options like highlights, blinking colors
- Events: keyboard and mouse
- indow: Has multiple libraries that can be integrated with existing curses functions
- Panels: this allows for screen manipulation that include moving or resizing panels 
- Menus: allows for the creation of a menu that assists the user to choose from a given set of items 
- CDK: includes a list of ‘widgets’ that can be used including calendar, dialogue, graph, item list, histogram

CONS:
- Doesn’t support sounds (maybe: could not find a credible source) 
- Graphics are “old-school”/low-level -- could be a pro though because might mean simpler functions (if we don’t mind limiting game developers to lower-level graphics)

THINGS TO LOOK INTO:
- _default_colors() function -- incorporate default colors of terminal into defined colors
- the function ‘keypad()’ enables the reading of function keys like F1, F2, arrow keys, etc and ‘getch();’ returns an integer corresponding to the key pressed
- the function ‘box()’ can be used to draw a border around the window
- Build the testncurses.c program with gcc -o testncurses testncurses.c -lncurses and run to see ncurses in action. (source: https://www.callicoder.com/golang-packages/)

**Comment by omorkved** [comment]
SDL:
PROS:

- Supports sounds!
- Written in C 
- Additional features: many libraries have been created to work on top of SDL (if we don’t have a feature we want, could be easier to find an existing compatible library with that feature)
- Video: 3D graphics
- Events: Keyboard, mouse events, resizing windows (if window size changes, can have functions that respond to that change)
- Timer Feature (if game state group would like to implement this feature into the game)
- Lots of online tutorials on using SDL


CONS:
- Supports higher-level graphics than what we actually need → This may translate in to too many complex functions to sift through? (Testing team will have to figure out whether or not this is the case in #16 )


Things to look into:

- the extension library SDL_mixer usually makes using sound easier (source: http://lazyfoo.net/SDL_tutorials/lesson11/index.php)
- Extension with pretty fonts!: SDL_ttf
- Support for multiple image formats: SDL_image
- A good beginner’s guide: http://www.brainycode.com/downloads/LearningSDL011.pdf

**Comment by sebvil** [comment]
On how to get ncurses: for linux, it is simpler to run 
`        sudo apt-get install libncurses5-dev libncursesw5-dev
`

**Comment by omorkved** [comment]
More info on SDL_mixer:
http://sdl.beuc.net/sdl.wiki/SDL_mixer

example of an SDL_mixer function
int Mix_Volume(int channel, int volume);
->Looks relatively easy to user/understand

> * the extension library SDL_mixer usually makes using sound easier (source: http://lazyfoo.net/SDL_tutorials/lesson11/index.php)

**Comment by omorkved** [comment]
Turbo Vision:
Written in C++ (also versions in Pascal)
https://www.openhub.net/p/tvision
Good project site and place to download: http://tvision.sourceforge.net/

PROS:

- Features: check boxes, radio buttons, push buttons, input lines, pull-down menus, status bars
- Really great features for managing multiple, overlapping windows! So this choice is good if we want to highlight features that include multiple visuals

CONS:

- I found it much more difficult to find info pages on Turbo Vision -- if we run into questions or problems, may be more difficult to find well-documented web pages/tutorials/stack overflow
- Most of the sources I found were rather out of date
- “requires C++ and Object-Oriented Programming (OOP) knowledge. Turbo Vision is an OO-library (well, almost...) using many C++ features such as inheritance and virtual functions so you have to know them”  (source http://www.delorie.com/howto/djgpp/turbo-vision-howto.html)
- So more of a learning curve for us if we choose this library.

My conclusion is that Turbo Vision is not a super likely contender against NCurses and SDL. Still wanted to include for comparison

**Comment by adomiter** [comment]
NCurses continued...

**Number 3: CDK** 
_Curses Development Kit (a library of widgets)_

PROS:
- Ability to build predefined screens, which will allow for us to switch screens if the character walks into a different room and might help us when creating a map
- Multiple ‘Widgets’: button, calendar, graph, floating scale, item list, pull down menu, scrolling list, scrolling window, item list, radio list (Link to full list below) 
- The widgets test themselves, which would be useful for us when we want to perform automated tests on the final program
- Allows programmers to ‘filter’ character input, which can be useful to CLI

CONS:
- Not as extensive as the other libraries if used by itself and would serve best when used in addition to Ncurses 
- Limited documentation on the library 

Things to look into:
- Link to the list of predefined curses widget: https://www.systutorials.com/docs/linux/man/3-cdk/
- Link to explanation on how you can link a widget to a given key: https://invisible-island.net/cdk/manpage/cdk_binding.3.html

__________________________________________________________________________________

**Number 4: PDCurses** 
_-a curses library for environments that don't fit the termcap/terminfo model._

PROS:
- Great documentation: the GitHub page (link below) has explanations for how to use each of the functions that they have
- Multiple keyboard and mouse related functions
- Display: has functions to manipulate the screen (e.g. color, resize, and border)
- 

CONS:
- Functions are written more for reading and writing into the terminal. This could be a pro if we want to focus on more text based output rather than graphics. 

Things to look into:

- GitHub Page describing each function: https://github.com/wmcbrine/PDCurses/blob/master/man/MANUAL.md
- GitHub Page describing the data types, variables, constants, etc: https://github.com/wmcbrine/PDCurses/blob/master/man/USERS.md
- beep() sounds the audible bell on the terminal and flash() "flashes" the screen

**Comment by adomiter** [comment]
**Additional sources to learn more about the NCurses library and its functions:**
- Ncurses man page: https://invisible-island.net/ncurses/man/ncurses.3x.html
- Ncurses Programming Guide: http://www.cs.ukzn.ac.za/~hughm/os/notes/ncurses.html
- A Hacker's Guide to Ncurses: https://invisible-island.net/ncurses/hackguide.html
- Game Programming in C with the Ncurses Library: https://www.viget.com/articles/game-programming-in-c-with-the-ncurses-library/

**Comment by borjasotomayor** [comment]
Quick tip: when you are researching libraries, and you find yourself wishing you could smash two libraries together (because neither of them has exactly what you want, but the union of the two does), googling for "X with Y" can be surprisingly effective (to see whether someone has already worked on integrating those two libraries, or to see whether someone has developed a library that attempts to provide the best of both worlds).

A cursory search for "ncurses with SDL" leads to two libraries:

- https://github.com/rofl0r/concol
- https://github.com/libtcod/libtcod

libtcod looks particularly promising given that it is game-oriented and may even facilitate tasks like drawing maps, etc.

**Comment by adomiter** [comment]
**Number 5: Libtcod** 

PROS:
- Amazing features that would be really helpful for our game: Path finding toolkit and a field of view toolkit will allow us to draw a really cool map
- Multiple keyboard and mouse related functions
- BMP and PNG image support
- Support for Perlin, simplex and wavelet noises

CONS:
- As Sam mentioned before, the biggest issue with this library is the limited documentation. The pdf file related to Libtcod contained blank chapters and the website with the latest documentation as well. Moreover, the links on their github page go to pages that do not exist at the moment. 

Things to look into:
- Link to the features page: https://bitbucket.org/libtcod/libtcod/wiki/Features
- Latest documentation of Libtcod: https://libtcod.readthedocs.io/en/latest/

**Comment by omorkved** [comment]
**Number 7: Concol**

PROS:
- We get to choose between three backends: ncurses backend, SDL backend, termbox backend
- Better color support -- a highlighted feature is that it is much easier to specify colors than in ncurses
- Supports SDL events like keyboard events and mouse events
- Supports many fonts!
- Makefile has this description: “Makefile snippet for easy inclusion of concol into projects”

Con:
- Doesnt give us anything extra in terms of sound handling (compared to SDL)
- Most of the .c files have very few comments/little documentation (see console.c as an example)
- Issue posted in early 2018 of a broken build with gcc 4.8, issue still open and unaddressed. Might not affect us, but still.


- Note: looks like we would pair this with ncurses or sdl -- not to be used as a standalone

Look into:
Their examples folder: https://github.com/rofl0r/concol/tree/master/examples

**Comment by borjasotomayor** [comment]
All: Great job documenting all your research! If you have not already done so, you should now try to narrow this down to 2-3 libraries for issue #16. You can discuss that here but, if you discuss it out-of-band (Slack, in person, etc.) make sure to post a comment explaining why you feel those 2-3 libraries are the most promising ones.

**Comment by omorkved** [comment]
(Note to Team: See Sam's comment in #16 for response to this)

> All: Great job documenting all your research! If you have not already done so, you should now try to narrow this down to 2-3 libraries for issue #16. You can discuss that here but, if you discuss it out-of-band (Slack, in person, etc.) make sure to post a comment explaining why you feel those 2-3 libraries are the most promising ones.

**Comment by omorkved** [comment]
We have chosen ncurses for now--may add an additional library on top of it later if we choose to support additional features.

**Comment by omorkved** [comment]
@mpcsh Reopened. Is this issue complete?

**Comment by borjasotomayor** [comment]
Yes, please go ahead and close it.

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work here! This is a model issue.
