### ISSUE TITLE
action-management/Adding structures to action management design doc

### ISSUE THREAD

**Issue by Don-Osipov** [uchicago-cs/chiventure#1513]
Will create a wiki page with a design doc explaining all the relevant structures to action management.

**Comment by KendrickXie** [comment]
### Closing Statement
We were able to write up an [entire wiki page](https://github.com/uchicago-cs/chiventure/wiki/Action-Management-~-Action-Types) describing the structure of actions. Specifically, we described actions of kinds 1-4, and what actions are included in each of those kinds. We also linked the NPC team's Wiki for explaining actions of kinds 5-7, since those actions all deal with NPCs.

Harrison, Kendrick, and Don all worked on the Wiki.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Great job creating documentation that is much needed! The summary could be expanded to be a bit more detailed.
