### ISSUE TITLE
Implement a get_item function. 

### ISSUE THREAD

**Issue by efraimdahl** [uchicago-cs/chiventure#152]
Implement a function that returns an item given an item_ID as string and a pointer to the current room. 

/*
 * Return a pointer to an item
 *
 * Input:
 *  - o: string that identifies item. i.e cube, wand, etc.
 *  - r: A pointer to a room struct (can be changed) 
 *
 * Returns:
 *  - A pointer to the item if the item is in current_room
 *  - NULL if it is not in current room
 */
item_t * get_item(char *i, room *r)

**Comment by patrickkoopmans** [comment]
@efraimdahl as per our Slack conversation, let me know if this function meets your specifications. 
Interface is located in room.h within our include directory. Tests have been written, and to my knowledge the function works as expected. Will pull request this to master so that you can use it.

**Comment by efraimdahl** [comment]
Closing Notice.
This looks good ! Tests are well written, I believe I can now easily in cooperate it into the cli code.
Good Job !

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
Good work! Since this is a smaller issue it's fine that there aren't a ton of progress updates, although it would have been good to provide some of the key details of the slack conversation that is referenced, and maybe have a progress update first for the function itself then the tests. I think in the closing notice it also would have been better to phrase it in terms of "this is what we did and why it's good" as opposed to "good job"
