### ISSUE TITLE
Update functions to account for tag in room struct

### ISSUE THREAD

**Issue by williamhu314** [uchicago-cs/chiventure#1526]
We have included a new tag field in the room struct so that we can figure out what the roomspec of a given room is which is important for our autogeneration functions. However, most of our functions currently do not support the tag field as in they do not correctly assign the correct integer to the tag field when a new room is generated. In this issue, we aim to update our functions to account for this new tag field so that we will be able to know what roomspec each room was generated from.

**Comment by lukasg8** [comment]
After working on this issue, we realized that it would be beneficial to add a matching tag element to the roomspec_t struct. Otherwise, functions such as roomspec_to_room would be very dependent on having a specgraph struct which would make it difficult. 

Ideally the input to roomspec_to_room would only be a roomspec rather than an entire specgraph since this would give developer more flexibility. Furthermore, it could make certain functions more efficient since there would be backwards functionality from roomspec to specgraph as well, rather than just the other way.

**Comment by lukasg8** [comment]
Currently, the function roomspec_autogenerate iterates through specgraph until it finds the corresponding roomspec to identify the 'tag' (the position of the roomspec in the roomspec list in specgraph). 

This method seems inefficient, especially since this function will be run every time a roomspec is generated **and.** because the roomspec list gets longer in specgraph, the function time increases linearly O(n) time. 

Furthermore, it means that this information can only be accessed via running the function and the function does not output the position in the list either.

Will work on this in new issue: #1544

**Comment by williamhu314** [comment]
The tags have now been added to the roomspec and room structs. The roomspec_to_room function now adds the tag of the roomspec to the newly generated room. All other autogeneration functions rely on the roomspec_to_room function so they will now be able to add the correct tag when generating new rooms.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job on this issue with a good set of updates!
