### ISSUE TITLE
update functions for tag struct in roomspec struct

### ISSUE THREAD

**Issue by lukasg8** [uchicago-cs/chiventure#1544]
This issue was found while working on issue #1526. 

The lack of a tag struct in the roomspec struct means that functions need to iterate through the specgraph every time in order to find the relative position of the roomspec in the list of roomspecs in specgraph. This is critical information for the autogenerate function because it will be used to search up the edges between different roomspecs to prevent incompatible rooms being generated next to each other. 

By adding a tag struct, we prepare for growing roomspec lists in specgraph and therefore be far more efficient as opposed to if we just iterated through the list, we would have O(n) processing time.

**Comment by philipchenaux** [comment]
Issue Score: Satisfactory

Comments:
Great job, but I have two key comments about this issue:
1. Your issue did not include any status updates between the opening of the issue and the closing of the issue (and this issue was not small enough to justify having no status updates at all). If you make any intermediate progress before finishing the task, then it should be documented on the GitHub issue via a comment.
2. When an issue is done, you should include a final comment summarizing what was done, and why the issue is being closed.
