### ISSUE TITLE
sound & rpg-battles: make a design doc for integrating sound effects into rpg-battles module

### ISSUE THREAD

**Issue by jiaoboxuan** [uchicago-cs/chiventure#1553]
in this issue, the `sound` team (myself) will work with the `rpg-battles` team to integrate sound effects.

Assignees: `sound`: Victor; `rpg-battles`: Emilio and Nafis

**Comment by jwschroeder21** [comment]
sent in a PR with updated documentation in the README file for RPG-battles team. hopefully their questions are answered there

**Comment by jiaoboxuan** [comment]
Will work with`rpg-battles` team on Wednesday afternoon.

**Comment by emiliolevinspage** [comment]
We have run into tricky linker issues and given the timeline we are going to instead focus on making a design doc/guide on the wiki to make battle-sound integration go smoothly in the future once the issues are resolved.

**Comment by emiliolevinspage** [comment]
[here](https://github.com/uchicago-cs/chiventure/wiki/Battles-~-Sound-integration-with-battle-(design-document)) is the design doc for future sound implementation. It details the fields, functions, and sound API calls required to use sounds in battle functions. Any move, item, or battle can have sounds associated with it- files are placed in battle/src/sound. We are closing the issue because this documentation is complete.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Nice work debugging this, and also pivoting when you realized you wouldn't be able to make the initial plan work given time constraints. The summary could be a bit more fleshed out in terms of what you want to accomplish, since it is a bit broad right now. Additionally you should not close an issue if it has an associated PR until that PR is merged, but it looks like you realized this and reopened the issue, nice job!
