### ISSUE TITLE
Create a script in the sandbox testing the boolean data type with Lua

### ISSUE THREAD

**Issue by tatmaca** [uchicago-cs/chiventure#1561]
The custom-scripts team has decided that, along with the documentation we've written up this quarter, we wanted to leave a substantial code base through which future teams can clearly see how they can implement Lua with the different data types described in our arg_custom_type module.

This issue is complete when a successful merge request is made which incorporates a Lua function which can accurately update a boolean data type ingrained in a unique game struct.

**Comment by mxu24** [comment]
Due to issues with building the sandbox, we've decided to move the files (dark_room.c, dark_room.h, and flip.lua) over to examples. While initially aiming to have two separate actions (LIGHT and UNLIGHT) to act on item torch, we realized there would be much more difficulty in using conditionals and booleans with lua, so we decided to change paths slightly to make the test case more clear and straightforward. We will now have one action (FLIP) to act on torch, turning it on and off whenever the action is called. We are still figuring out how to change this while the demo is running, as it is not something we can initialize like the gold.c demo. We also need to add dark_room files to the makefile.

**Comment by mxu24** [comment]
Completed, replaced SWITCH action with two actions LIGHT and UNLIGHT to act on item torch. Makefile was changed, pull request updated with update-sandbox branch.

**Comment by tatmaca** [comment]
This issue is now closed! In preparation for our final demo, we've merged a branch that runs a chiventure game and experiments with using Lua to manipulate boolean values. This simple function is critical as it can add easy game manipulation through the use of ON/OFF, ACTIVE/INACTIVE, etc. to implement logic on the players end as they progress through a game. This demo can be found in dark_room.c.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Nice work on this sandbox, and great job keeping the issue updated!
