### ISSUE TITLE
cli: implement our end of `view quests`

### ISSUE THREAD

**Issue by majorsylvie** [uchicago-cs/chiventure#1565]
follow our end of the implementation as defined in the documentation of `view quests`

**Comment by majorsylvie** [comment]
Here's the branch
```
git fetch origin
git checkout cli/1565-cli-implement-our-end-of-view-quests
```

**Comment by katyashchukina** [comment]
We all had a group meeting with action management and quest teams and came up with this document with specific requirements:
https://docs.google.com/document/d/1XEtIJlm0A2CyZ-WRf0a7PABN_FjYQ_BLR5ccnZuM8H4/edit

**Comment by majorsylvie** [comment]
Actually, since the PR for view stats has not come in yet, instead use the
```
git checkout 1271-cli-implement-view-stats
```

**Comment by katyashchukina** [comment]
We made the changes outlined in the document, which are:

- Sanitize the token list to be 3 entries (removing the action word)
- Remove the check for only 2 words

Currently it shows a warning because the quest team haven't changed do_self_action on their side (because one of the types has changed from a string to a list of strings as per their request), but we are closing this issue because we have made all the changes they requested.

**Comment by katyashchukina** [comment]
Reopened issue because we forgot to pull request!

**Comment by katyashchukina** [comment]
We made the changes outlined in the document. Currently it shows a warning because the quest team haven't changed do_self_action on their side (because one of the types has changed from a string to a list of strings as per their request), but we are closing this issue because we have made all the changes they requested

**Comment by jacknugent1529** [comment]
Issue Score: Satisfactory

Comments: Nice work on this issue! The updates are detailed, however the issue description should go into a bit more depth about the specifications. Additionally, the specifications should be placed in a wiki page rather than google docs.
