### ISSUE TITLE
GUI: Create Wiki page for graphics sandbox 

### ISSUE THREAD

**Issue by imadejski** [uchicago-cs/chiventure#1572]
Create Wiki page to update future chiventure graphics workers on the modules in the sandbox and next steps we would like to take. This includes a review and explanation of each module.

**Comment by csraffaga** [comment]
Wiki sidebar enhanced to include sandbox future directions.

**Comment by csraffaga** [comment]
Given that this year's graphics team has been deviating sharply from what has been done and accomplished in previous years, it is important to highlight and document for future graphics teams the new direction and course we have set for GUI in Chiventure. Not only are we reorganizing the current graphics code to be more readable and flexible by adding function parameters and changing structures, we are also revolutionizing how graphics are interpreted. Now, with the GDL, authors can specify how certain key features are displayed. It is important for future classes to be able to interpret our code and build upon it so that chi venture may improve efficiently. 

I have begun the wiki to discuss the GDL, future directions of our project, and written specifics about each module (what they entail and how they differ from the current code base).

**Comment by ukanyanwu** [comment]
A page discussing possible future directions for the current modules in chiventure is added to the Wiki. So, new developers of chiventure now have an additional reference point on how to expand upon the graphics module, which is especially important since this version of the module is new during this iteration of CMSC 220.  It is desired that the page can give a starting point when starting work with the module, both in understanding what can/should be modified in the modules, and possibly ideas on what can be added to make them even more flexible and easy to use for authors of chiventure games.

**Comment by philipchenaux** [comment]
Issue Score: Excellent

Comments:
Great job on this issue with a good set of updates!
