### ISSUE TITLE
Create the NPC demo based on the design document

### ISSUE THREAD

**Issue by srydbergcox** [uchicago-cs/chiventure#1587]
Using the [design document](https://github.com/uchicago-cs/chiventure/wiki/NPC-~-NPC-Demo-Design-Document) that our team made earlier in this sprint, we will create our demo. The goal of this demo is to create one example that showcases the work of all four sub-teams. To do this, we may need to monkey-patch some things, this is something that we will look into. The design document has more details about the exact vision for this implementation. Also, given the upcoming code freeze this will need to be done by Friday 5/27.

**Comment by bvvill** [comment]
I've created the `npc/demo-2022` branch for us, and I'll create another branch for myself stemming from that one

**Comment by junasano** [comment]
The WDL file is now mostly complete. The rooms, items, and npc is added

**Comment by bvvill** [comment]
I don't think it's going to be wise for us to make a WDL file for our demo, there's just so much about NPCs that hasn't been integrated with the format. I've been up for a while mainly working on an in-memory game based on last year's battle_move_example, so I could iron out the kinks of many of the functionalities we want to show off this year. The example is simply named `npc_example_2022`, and it's in the `npc/demo-2022` branch.
Some of the things I was able to implement are:
1. adding a condition to a dialogue node of a CONDITIONAL_FRIENDLY npc (in this case, friendly_fiona) that, when triggered, changes the npc's hostility_level to HOSTILE, and makes them eligible to be attacked, whereas before, typing "attack" would only affect hostile_harry
2. another command called "FIND", which the user can use to find the location of an npc by typing their name after 'find', which should be very useful when dealing with indefinite-moving NPCs
3. having time_dependent_functions() be run on a detached pthread, which currently only moves indefinite NPCs, should it be time for them to do so.

Some things I'd like to try to do today if possible:
1. Figure out an accurate logic for switching NORMAL, CONVERSATION, and BATTLE game modes. Right now, the game literally goes into conversation mode whenever dialogue is started, and won't go back into normal mode until ALL of an NPCs dialogue edges have been exhausted, which just doesn't seem right.
2. I'd also like to modify the monkey-patched "attack" function to attack a specified NPC instead of just all NPCs in a room that are HOSTILE.

honestly the last 8 hours have made me think that every struct should just have some sort of struct-specific validity enum that controls whether the data in that struct can be modified in certain ways or not, but there's no time for that lol. I'll be awake by 2p hopefully

**Comment by srydbergcox** [comment]
Looking at the current .c file that we have, I think that we should aim to implement a little bit more of a logical progression. What I am currently thinking is this:
1. Player talks to Hostile Harry which prompts a battle. Player runs attack 5x and kills Harry.
2. In the arena, wandering william "watches" the battle so we go talk to william who offers us a sword that does 5 damage so only have to run one "move" to win the battle.
3. Player goes back to the lobby and talks to Fiona. They have a conversation where player provokes fiona. The content of the conversation is something along the line of fiona also has a weapon of some sort and they basically challenge each other to a fight.
4. Player goes back to arena to fight Fiona. Player beats Fiona which prompts Fiona to drop her weapon which then the player can pick up.

I think that William identifies good roadblocks above, specifically figuring out how to control the game modes of chiventure. Also, I think we will need to find a way to only send one NPC to the arena at a time, which should fix William's second concern.

Edit: I am not sure about the difference between items and weapons in the `npc_battle` struct right now, so maybe have just an item that the player tries to take which prompts a battle.

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! For a task of this size, we would've expected to see more status updates and/or status updates that were more detailed. The given updates are thorough, but they identify some uncertainties that I would expect further updates to clarify.
