### ISSUE TITLE
Demo with Conditional WDL File loaded with C

### ISSUE THREAD

**Issue by RamarkoB** [uchicago-cs/chiventure#1604]
So far, we have been experimenting with WDL files using command line arguments. Before we move further with integrating Lua and the WDL, we first want to create a C file that is able to load a WDL file with conditional statements. This Issue will be ready to be marked complete when we have a working Chiventure demo that is able to include a WDL file with conditional actions.

**Comment by jackjackkimkim** [comment]
We implemented the inventory conditional function developed by the action-management team. Their function allowed us to check for the existence of an item in the inventory before performing a certain action on another item. After implementing this change in our own WDL file, we were able to link to directly to our demonstration c file so that the WDL file can be used in conjuncture with Lua scripts.

**Comment by RamarkoB** [comment]
This Demo was merged successfully. There is now a working demo that loads WDL from C within the Demonstration File within the src/custom-scripts/examples folder. We are planning to build off this by creating new pull requests that will load in Lua that interacts with a loaded WDL file. Marking this issue as closed.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Nice job creating this demo that utilizes WDL files!
