### ISSUE TITLE
Create UI context struct

### ISSUE THREAD

**Issue by sebvil** [uchicago-cs/chiventure#161]
In this task, we want to create an UI context struct that will hold important information relevant to the UI that other teams might need to use in their code. Such information includes window structs that CLI might need to access to print info or modify the UI. 

Other work in this task will include modifying the main context struct (and related functions) so that they include our UI context struct, and modifying our existing UI functions so that they take the main context struct as a parameter.

**Comment by omorkved** [comment]
Explanation of the coord_t field in ui_ctx:

We need to know the current _coordinate_ location of the player to know where to center the map. The current thinking is that, as the player moves through the map, we update the actual coordinate instead of reading the updated room *curr_room out of game state's curr_room field. (This is because our hash uses coords as keys to room *s, so finding a coordinate _from_ a room * would involve just searching from top to bottom of the hash map looking for that room *--seems inefficient, which is why we think it is better to just track the current coordinate location of the player).
In short, this would look like 1. writing a quick function that adds/subtracts one to either the x or y field (never both at the same time) (also this is more complicated if portals are supported) and 2. telling action management how to call this function with the appropriate fields whenever they allow the player to pass into a new room.

The alternative to this is to read the curr_room field out of game state everytime we redraw the map (which happens with any key press to change windows + every time the player moves) and then iterating through the hash to lookup which coord key corresponds with that specific room.
(Having coordinates as keys made sense for the purposes of DFS creating the map to efficiently check uniqueness of coord assignments)

**Comment by omorkved** [comment]
Here are the current three fields in our ctx struct:

 UI context struct.  Contains the following fields (explanation of player_loc in my comment above):
```
/*
 *  - coord_hash: a pointer to the head of a hash map that matches
 *                coordinate keys to room pointers
 */
typedef struct ui_ctx
{
    map_t *map;
    coord_t *player_loc;
    coord_record_t *coord_hash;
```

However, previous commits will show that we had initially included pointers to windows in our actual ctx struct:

```
/*
 *  - map_win : contains the map
 *  - main_win : main window. May contain images or other info about the game
 *  - cli_win : window that contains the CLI. It's always displayed
 *  - displayed_win : window that is diplayed along with the CLI.
*/
```
We are still on the fence for this. @sebvil , could you post a summary of why we initially included windows and now are not including them?

**Comment by sebvil** [comment]
> Here are the current three fields in our ctx struct (as of [d41476d](https://github.com/uchicago-cs/chiventure/commit/d41476d540b158f62fd6ae7fe72e9e0bb7f8edc7))
> 
> UI context struct. Contains the following fields (explanation of player_loc in my comment above):
> 
> ```
> /*
>  *  - coord_hash: a pointer to the head of a hash map that matches
>  *                coordinate keys to room pointers
>  */
> typedef struct ui_ctx
> {
>     map_t *map;
>     coord_t *player_loc;
>     coord_record_t *coord_hash;
> ```
> 
> However, previous commits will show that we had initially included pointers to windows in our actual ctx struct:
> 
> ```
> /*
>  *  - map_win : contains the map
>  *  - main_win : main window. May contain images or other info about the game
>  *  - cli_win : window that contains the CLI. It's always displayed
>  *  - displayed_win : window that is diplayed along with the CLI.
> */
> ```
> 
> We are still on the fence for this. @sebvil , could you post a summary of why we initially included windows and now are not including them?

Main reason to get rid of the window structs from the UI context struct was to remove some circular dependencies that were generated as a result. Since the window_print functions that were associated with a window would need to take in the chiventure_ctx struct, including the windows in the ui_ctx struct would create circular dependencies in the code. Thus, for now the windows will not be included in the ui_ctx, but this might change later if deemed necessary. This would also mean that print functions would have to be modified, too.

**Comment by sebvil** [comment]
Trying to solve another problem with circular dependencies, I figured out I could use forward declaration to have the chiventure_ctx structs be a parameter of the win_print functions, while the ui_ctx contains the window structs. Thus, I added the window structs back to the ui_ctx structs.

**Comment by sebvil** [comment]
Closing statement: Our final ui context struct looks as follows:
```
typedef struct ui_ctx {
    map_t *map;
    coord_t *player_loc;
    coord_record_t *coord_hash;
    window_t *map_win;
    window_t *main_win;
    window_t *displayed_win;
    window_t *cli_win;
    int curr_page;
    int cli_top;

} ui_ctx_t;
```
`map` contains info to print the map to the UI.
`player_loc` contains the current location of the player.
`coord_hash` contains the a hash of all rooms with their coordinates as keys.
`map_win` window where map is printed
`main_win` main window
`displayed_win` window being currently displayed along with the CLI
`cli_win` CLI window
`curr_page` indicates what window we are displaying
`cli_top` indicates the position of the CLI

This context struct is contained in the chiventure context struct and is used by the CLI team to modify the appearance of the UI and print to the CLI.

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
