### ISSUE TITLE
sound: Add initializing functions for sound type declaration

### ISSUE THREAD

**Issue by jiaoboxuan** [uchicago-cs/chiventure#1622]
This issue is created because we found that there are no initialization functions of any kind for `sound_t` module, which comes to be a huge hassle while writing for tests, because the same lines of code will have to be repeated (specifically, `malloc` of `sound_t` and assigning values and pointers within `sound_t`.

**Comment by sangerr** [comment]
Closing Statement: We created this issue because there are no initialization functions of the sound_t module, so we created a sound_new and sound_init function in the sound.c file. The creation of these functions are critical to us writing tests as well as the overall usage of the sound structs. We are still waiting for the pull request to be merged, and will close the issue once it is.

**Comment by ecoble** [comment]
Issue Score: Satisfactory

Comments:
Nice job creating these new functions! Though this issue wasn't too difficult, there should still be a couple status updates on your progress.
