### ISSUE TITLE
Adding two WDL files for each class that is used for custom-scripts demonstration 2022

### ISSUE THREAD

**Issue by jackjackkimkim** [uchicago-cs/chiventure#1636]
Different WDL files will be loaded into the game depending on the output of the LUA file. There is one WDL specifically for the wizard class and another one for the Warrior Class. Each WDL associated with its respective class have different items and actions.

**Comment by jackjackkimkim** [comment]
#1637 is the pull request associated with this issue.

**Comment by tatmaca** [comment]
This issue is now closed! Both WDL files are read correctly by the Chiventure game and in both demonstrations the correct items are being loaded in with the proper associated actions. Since everything runs as it should, all tests have passed, and the merge request went through, this pull request is closed!

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Great job creating this for the demo! The status updates could be a bit more detailed.
