### ISSUE TITLE
Integrate gold.c elements with demonstration

### ISSUE THREAD

**Issue by mxu24** [uchicago-cs/chiventure#1648]
Include chest and torch functionalities using Lua from the gold.c and dark_room.c files respectively into the current demonstration (pending pull request). This issue will be closed once we have successfully updated the demonstration.

**Comment by RamarkoB** [comment]
This issue was already partially accomplished with Pull Request #1651, which combined the dark_room demo with the Warrior/Wizard Demo. A final step would be to combine those two demos with the gold.c demo. Combining all three demos would give us a final Presentation-ready demo that we can present next week

**Comment by RamarkoB** [comment]
Over the course of Multiple pull requests, we now have a single demo that combines our previous smaller demos. This will be our final demo file for the year, and is called demo_2022.c

**Comment by ecoble** [comment]
Removing the milestone since this is a duplicate issue and will be ungraded.
