### ISSUE TITLE
Implement testing for `apply_item_stat_changes()` in battle_logic.c

### ISSUE THREAD

**Issue by jroven** [uchicago-cs/chiventure#1657]
In issue #1024, player class and item interactions were integrated into battle logic, specifically making a lot of changes to `apply_item_stat_changes()` in battle_logic.c. These changes involved creating multipliers based on player class that affect stat changes due to items. In the process, five tests in the battle_logic suite broke because they were not designed for this implementation. The tests were `consume_a_battle_item`, `uses_battle_item_correctly`, `remove_single_item`, `remove_item_of_multiple`, and `remove_last_item_of_multiple`. These tests have been commented out for the time being but they should be fixed so they correctly test the new multiplier feature.

**Comment by Vincent-Zhang4135** [comment]
Jonathan and I have been working together on why there are segfaults for the Tests, and we realized that this is because in the old Tests, the previous generations of devs initialized class and items as NULL. As a result, we realized that in order to get these tests to work, we need to initialize the class and items, so that we can access the names of them we comparing them in our `apply_item_stat_change()` function.

**Comment by jroven** [comment]
I have fixed all the tests by initializing items and classes for them, so there are no more segfaults. A pull request can be made now.

**Comment by Vincent-Zhang4135** [comment]
As a part of issue #1024, we have applied an `apply_item_stat_changes()` function battle_logic.c, and since it broke some of the tests, which was what this issue was for, we have also fixed the original tests that broke. Unfortunately, due to some conflicting design directions from battle teams and our side, some of our tests works while the additional ones that battle teams added fails, and so I have closed this issue, and will create a new issue in the backlog to fix these additional tests that were added towards the end of the sprint. 

The issue in the backlog is linked here: #1718

**Comment by lilyehsani** [comment]
Issue Score: Excellent

Comments:
Great work on this issue! The summary and closing statement are very thorough.
