### ISSUE TITLE
Write function tests and new .wdl for load_npc.c (new dialogue-quest implementation)

### ISSUE THREAD

**Issue by sglenn-uchi** [uchicago-cs/chiventure#1658]
There currently are no tests for NPC implementation in WDL, including how JSON objects are parsed into their structs. As I am currently working with the Quests team to add implementation for dialogue in quests in WDLs, I think having at least a test WDL file would help. For this issue, I will write a WDL with Quests, Items, and an NPC, to maintain previous features, and most importantly, a list of Quests and Tasks within the NPC with unique dialogue in addition to its normal dialogue. I will also write tests for the new functions defined in npc.c (creating, initializing, and freeing npc_quest_list and npc_task_list).

**Comment by sglenn-uchi** [comment]
I wrote tests for the new functions and revised the functions so that they all pass. I also made a draft of a .WDL file extending the work of pokemon.wdl called pokemon_plus.wdl where some of the NPCs now have quests and tasks with unique dialogue.

**Comment by lilyehsani** [comment]
Issue Score: Satisfactory

Comments:
Great work! Your issue did not include any status updates between the opening of the issue and the closing of the issue (and this issue was not small enough to justify having no status updates at all). If you make any intermediate progress before finishing the task, then it should be documented on the GitHub issue via a comment.
