### ISSUE TITLE
Adding extra tests in test_types.c to confirm the functionality of Lua in final demo

### ISSUE THREAD

**Issue by mxu24** [uchicago-cs/chiventure#1702]
Due to the new changes in the demo (integrating dark_room.c and gold.c with demonstration.c) and earlier difficulties implementing Lua functionality with WDL, we must create additional tests to confirm the working status of the demo, particularly after further added functionality and final edits.

Tied to pull request #1692.

**Comment by tatmaca** [comment]
This pull request is now closed! The custom-scripts team realized that our new demos for the end of the Spring Quarter incorporates some new Lua functionality. In order to make sure that this functionality is documented and proven in our codebase, we decided to create new tests. These tests have all passed, cover all new cases, and has been successfully merged!

**Comment by ecoble** [comment]
Issue Score: Satisfactory

Comments:
Nice job writing new tests! Please provide status updates on issues as you go.
