### ISSUE TITLE
Integrating Checkpointing Load Command into CLI

### ISSUE THREAD

**Issue by dbarer** [uchicago-cs/chiventure#197]
Continuing our work from the previous sprint with integrating save, this issue will tackle integrating load. This is a little more complicated as in addition to calling the check pointing load function, we also need to load a WDL file into a game.

**Comment by dbarer** [comment]
Update: Added skeletons of functions to implement load command. This includes adding it to the hash table list of commands, as well as adding functions to the operations module. Need to double check with WDL tomorrow what the best way to load a WDL file is. Also, waiting for a completed load function to test out the code. This code for now lives in the cli/dbarer/load branch.

**Comment by dbarer** [comment]
Update: Talked to Checkpointing and WDL today. CHeckpointing will call the WDL load command inside their load function, so I no longer need to worry about that on the CLI side. This means that the load operation is ready to be implemented, and after working versions of save/load are added, integration will be complete. I'm working now with people on checkpointing to fix the integration issues.

**Comment by jarvislam1999** [comment]
Hi, sorry for bothering you but the information that checkpointing provided 2 days ago about how we will take care of the WDL load function may be wrong. From my communications with Mark and Borja early this sprint, CLI and action management are responsible for the calling of the WDL load function on top of our load functions. 

I'm sorry for the misinformation. The good news is that load is error free atm in both compilations and execution so you can begin using it once we push to master. It may have errors we haven't detected it yet but you can now work on the integration part. Please let me know your thoughts soon.

**Comment by jonahdf** [comment]
I've been working for a while on doing small fixes to get UI's test to run. Unfortunately, what started small has now gotten quite large, and in order to make the fix I have to change a few lines in over 6 files, and 3 makefiles (and I'm still not done yet). At this point, I think it is better to just wait for checkpointing's new pull request so we no longer have to work around the dummy.h structs. I will also put the new makefile changes in our dev branch so it should work right off the bat when we merge to master.

**Comment by chrisfernandes18** [comment]
Okay @dbarer, so we have our save and load functions compiling well. Now we just need to integrate the cli component to work with our functions. Since this component is for both cli and checkpointing and you need our functions to work, why don't we edit the cli stuff in our dev branch so that can be tested in there. If we did a PR to master that would probably take too long so doing this in out dev would be a quick work around. Can you edit the save cli function in our checkpointing/dev so we can test to see if it works?

**Comment by jonahdf** [comment]
@dbarer has made required edits in operations.c, operations.h, and cmd.c, and I have edited the Makefiles for CLI, top-level, and common to include all the changes. The CLI, checkpointing, and common directories all compile, but top level still does not. I believe this is because some groups include CLI, which includes checkpointing and some game-state directories, but around specifying the required paths in their makefile

**Comment by dbarer** [comment]
Update: We have found the issue that was plaguing us with the Makefiles, where we both required each other's libraries to be created first. And have found a solution, though it is not pretty. Additinally, I have updated cli/dbarer/load with the updated save & code this should all be good, but it includes a wdl function that has not yet been pushed to master, thus I cannot do a PR yet. However, once that goes through we'll be able to know for sure if everything is correctly integrated, and then we can push my PR.

**Comment by jarvislam1999** [comment]
@dbarer When you say a solution, was you referring to my solution or a new one that you found? We should compare them to see which one should be used for master.

**Comment by dbarer** [comment]
Closing Statement: I'm gonna close this issue as all the code is done, and is waiting in cli/dbarer/load for wdl to add their load_wdl files from their wdl/dev into master, and then I'll merge with cli/dev and do a PR to master from there. This branch has all the function calls from other groups needed to save & load and fully integrates CLI with the other two teams. Next steps are actually making sure that these function calls work, but we need to have a WDL game properly loaded in order to test this out.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Nice work!
