### ISSUE TITLE
Show Player Position in Map

### ISSUE THREAD

**Issue by omorkved** [uchicago-cs/chiventure#206]
Show player position in map with a character. Update whenever player moves rooms

@Sshatzkin

**Comment by Sshatzkin** [comment]
I have since expanded this issue to include a variety of quality of life fixes to the map and it's functionality.  This includes indicating player position and the creation of a function to assign player coordinates in the UI struct.

It also includes a border for the map window and a visual display indicating a player's current coordinates.

The specific changes are outlined in PR #352

**Comment by dwahme** [comment]
This appears to have been completed in #352
