### ISSUE TITLE
Load: Continuously update to reflect most recent changes in master

### ISSUE THREAD

**Issue by ellynliu** [uchicago-cs/chiventure#220]
Whenever game state pushes to master (including the hotfix for iterator functions), if necessary, update our load.h and load.c files to reflect changes. This could include changes in structs, new functions, function names, parameters, etc.

**Comment by schin99** [comment]
all iterators are replaced with the new functions that game-state implemented and compiles without any errors or warnings

**Comment by schin99** [comment]
Although this was more of a testing issue, we had problems with functions that were undefined but that's now resolved due to some reason that no one really knows but I'm not complaining.

**Comment by schin99** [comment]
Since it compiles, I believe this issue is done so I'm just gonna close it.

**Comment by jonahdf** [comment]
To clarify when @schin99 and @ellynliu said, we replaced what prevents compiling, and updated the AM/GS integration: 
-ITER_X has now been replaced with all_x_in_x
-Now that action management has integrated with game state, we have updated the "action" saving mechanism when attribute tag is "ACTION"

The remaining bugs will be fixed in the checkpointing/loadtesting branch

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
