### ISSUE TITLE
Save: Test updated save function

### ISSUE THREAD

**Issue by schin99** [uchicago-cs/chiventure#221]
When save.c is updated with game-state's new functions, test to make sure the code we could not previously test works and game-state's function works with our code.

**Comment by chrisfernandes18** [comment]
The test_save.c tests all pass now. The functions that game-state provided to be able to make a small game to test if our functions save now work and compile when we run make tests. Our functions are able to store all the game-struct values into the proto file. The last thing we need to test is if it serializes everything into a file.

**Comment by ellynliu** [comment]
This was fixed a couple of days ago, but because game state introduced new structs, we had to modify our save code to take into consideration a possible attribute_tag of ACTION, which was used in attribute_value_t and now contained a game_action_t, which contains an action_type_t, which is a struct found in action management.

**Comment by ellynliu** [comment]
To add upon the previous comment, to implement these changes, save.c had to be changed to use game state's functions for get_bool_attr, get_char_attr, get_str_attr, get_char_attr in order to access the information stored in hash tables. Also, save_attribute now accepts three inputs (item_t, attribute_t, Attribute) in order to use the get_ functions, as they needed the item name, not just the attribute. 

In addition, since game state altered their iterator functions to return a linked list instead of using an iterator macro as in the prior sprint, we had to change our functions to go through a linked list and put the elements into an array to be serialized. The rest of the functions were largely similar.

**Comment by schin99** [comment]
All tests passed! We added a few more items to the inventory in player and more rooms to game. We may add more tests but that probably will be only for load.

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
