### ISSUE TITLE
Introduce an "inventory checker", requiring item prerequistes to perform actions

### ISSUE THREAD

**Issue by yoonsjeong** [uchicago-cs/chiventure#236]
*this is a backlog issue and is not a current priority*
Here is a rough example of what we would expect from this issue.

We want to create a game in which you must be holding the item KEY in order to perform the action OPEN CHEST. In being able to perform the task here are some alterations to the current project that may potentially need to be added.

- WDL: the item CHEST would have to be able to take an attribute that specifies that searching through inventory for item KEY
- Game-State: the above info from WDL would need to be translated into an attribute of CHEST
- Action-Management: game-state's functions for changing an attribute given an action would be used

**Comment by Dumplingz** [comment]
The action-management and game-state part of this issue is complete. Details are here: #577. The wdl part of this issue can now be found here: #786.

**Comment by HarrisonD123** [comment]
It seems like the action-management and game-state side of this issue has already been resolved. Going forward, the action-management team will have to collaborate with the DSL team in order to close the entire issue. DSL still needs to implement some way of saving inventory conditions, based on the current implementation of conditions as linked lists. Functions `add_end_condition_to_game` and `add_condition` in `game.c` of the game-state module will also need to be referenced in order to determine how to best proceed. I've just reached out to the DSL team in order to collaborate on this issue.

**Comment by sabinecodes15** [comment]
After learning that the action management team has the capacity to add wdl functionality without the help of other teams, we will be implementing this part on our own. Updates will be posted under issue #786; once this feature is implemented, we will add a closing statement here.

**Comment by sabinecodes15** [comment]
The WDL portion of this issue will be implemented with the approval of PR #1492. The last thing that needs to be done to close this issue are tests to ensure that inventory conditions are properly implemented- see issue #1516

**Comment by sabinecodes15** [comment]
### Closing Statement
Inventory conditions have been fully implemented and pass all tests, so we can now close this issue.

**Comment by ecoble** [comment]
Issue Score: Excellent

Comments:
Great job finishing this issue that has been in the work for a long time!
