### ISSUE TITLE
Support for History Command

### ISSUE THREAD

**Issue by ecoble** [uchicago-cs/chiventure#271]
CLI previously supported "HIST" as a command, that printed out the user's history of commands. This command was causing a lot of issues during integration and testing, so we stopped supporting it. The goal of this issue is to debug the history operation and add support for it again.

**Comment by Tianlel** [comment]
Closing statement:
I've successfully implemented the history command and I've added the hist option to the help_text.

**Comment by dchen0258** [comment]
The goal is really the same as the one described before. Talking to Elizabeth, it seems like the committed code from above was close to finished but there simply wasn't enough time before the end of the project to complete a pull request.

**Comment by dchen0258** [comment]
The old code in the cli/tianlel/history branch does not work with the updated chiventure. When building, there were undefined references to many of the history operations and function calls.

**Comment by dchen0258** [comment]
Knowing this, the easiest thing to do is to use Tianle's old ideas and incorporate them into chiventure. 

This will include:
- Create a way to store all the operations that have been called
- Adding the HIST command back into the cmd.c file
- Printing the command when the HIST command is called 

This a high level way of looking at the problem. More details to come.

**Comment by dchen0258** [comment]
The more detailed implementation:

- For storage: A linked list of strings (char arrays) might be the best way to store the operations, since we don't know how many commands they will call.
*Need to find where exactly a command is processed so it can be easily added to the linked list (or whatever data structure we end up choosing* - maybe we can take from cli/src/cmd.c line 231 with the variable char *s (decide whether to add commands that did not work or were NULL to list)
- For adding the HIST command back: simply uncommenting line 112 in the cli/src/cmd.c file should accomplish this
- For printing I saw the Tianle's use of "print _to_cli" for this which I think should still work. 

Other design decisions to be made: 
- If they call history, does that go in the history, does it reset it, or should it stay the same?
- I assume a NULL command call should not be included, but what about functions that are technically erroneous for chiventure? Should they be considered?

**Comment by dchen0258** [comment]
Only thing left to consider is where exactly to initialize the linked list.

**Comment by dchen0258** [comment]
Have implemented the function following most of the thoughts above with two main error/issues:
1. When HIST is called, it prints out the history, but only HISTs show up- the exact number of commands that would be in the history
2. It interprets "go north" as just "GO"

**Comment by dchen0258** [comment]
Fixed the interpretation of multi-word commands so it interprets "go north" as "go north". Other issue is still being debugged.

**Comment by dchen0258** [comment]
Submitted pull request.
Main problem: I was duplicating the command when I was appending. 
Secondary problem: Not checking the command was NULL before appending.

**Comment by dchen0258** [comment]
Pull request merged!

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great work bringing back the history command! utlist can be a little confusing at times, nice work debugging those problems!
