### ISSUE TITLE
Update do_item_item_action tests to reflect #245 

### ISSUE THREAD

**Issue by MTUC08** [uchicago-cs/chiventure#288]
In #245 , we added a new out parameter to hold the status string returned by our do_item_item_action function, and changed the return format to return an int reflecting the status of the action. However, this change will break our original do_item_item_action tests, so the goal of this issue is to update/fix our do_item_item_action tests to reflect the new parameters and return format.

**Comment by SnowballAntrobus** [comment]
Complies and all tests pass in branch actions_change_return_format_tests

**Comment by SnowballAntrobus** [comment]
Closing Statement:
In #245 we finally changed the return value of our function do_item_item_action to output an error code int instead of a string. This makes testing much more easy and reliable since we no longer compare strings, instead just checking the return value. In future work we will update the function once again this time to change game state, i.e move the player, and check for conditions before executing. We will be writing tests for these new features as well.

**Comment by SnowballAntrobus** [comment]
It is important to note that we defined various macros for the error code ints the function outputs. This function is particular in that it has an additional macro for when the function fails on a not allowed action in the direct vs in the indirect.

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
