### ISSUE TITLE
Validate number of objects is correct for a given command

### ISSUE THREAD

**Issue by ecoble** [uchicago-cs/chiventure#357]
We should validate the number of words a user types in corresponds correctly to the action kind. For example, currently if the user types "PUSH [obj] [obj]", the second object will be ignored and the command will be passed off with just "PUSH" and the first object. We should add validation to see if the user tried to give more than one parameter following a command like "PUSH," and if so return an error message and not try to execute their command.

**Comment by dchen0258** [comment]
Initial brainstorm (before coding):
For kind1 actions: 
In the function in operations.c that deals with kind1 actions. To validate the number of objects it should check the tokens[2] slot for if it is NULL or not. The only thing to consider is if it is not NULL then it may be a preposition or conjunction for example: push table and chair. I am not sure if this is something that needs to considered since the description of kind1 actions is ACTION <item>, which does not account for the above, but there is an issue currently being worked on that wants to implement the acknowledgement of "and"

**Comment by dchen0258** [comment]
For kind2 actions it should be a relatively similar process, however for kind3 it may be a little different (though still with the same method of checking the tokens array) since these actions allow for two different items. The implementation depends on whether we want to allow for prepositions or not.

**Comment by mberamendiconde** [comment]
Yeah so speaking to your point David, I think using token[2] is risky cause that would end up limiting chiventure input options that could still work (like actions for 1 item but with several words). I think a possible approach could be in the implementation, like if the first word already 'covers' the action, the action -> path -> action item mechanism just continues (as if the second word isn't there) and if that bypass needs to occur it can return an error message while doing the command from the first item

**Comment by mberamendiconde** [comment]
another idea is that for now we can include a check for token[2] to see if it's "and" and if it is its almost like we 'restart' the mechanism? but then if token[2] is NEITHER "and" or NULL we can return an error

almost like killing two birds with one stone?

**Comment by dchen0258** [comment]
Fixed issue of validation for kind1 and kind2 functions (still need senior dev to validate code) by checking the token[2] slot to check if it is NULL. Have not fully implemented this validation for kind3 because we need to wait to see if prepositions and conjunctions are included the token lists.

**Comment by dchen0258** [comment]
Pull request submitted.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great job with this issue! You especially did a great job updating this issue with your ideas and progress. Be sure to change the milestone when an issue rolls over into the next sprint.
