### ISSUE TITLE
Commands that affect state

### ISSUE THREAD

**Issue by efraimdahl** [uchicago-cs/chiventure#38]
CLI team, talk with Game-State team to access and manipulate game-state. 
Commands such as LOOK, MOVE, INVENTORY are Game-State tasks. 

Write these commands

LOOK should give a brief description

MOVE should change current room;

INVENTORY should print the names of the objects in inventory

**Comment by Tianlel** [comment]
Update:

1. We decided that commands that should be handled by a game state function should be limited to 1 argument (exit, save, inventory....) with the exception of move + direction (if this were to be handled directly by game_state instead of action_management)

2. We need game state team to provide a function that returns the current game state (e.g. game* get_current_game()) against which we can check whether an object is present

3. We'd like game state to add a new field to their object struct that specifies the supported actions for the object (after this checking we will construct an action struct from the list of tokens, and then pass this struct to the action management team to make changes to the game state)

**Comment by efraimdahl** [comment]
UPDATE: The validation we wrote for the different files should in cooperate both game state actions and action actions (for lack of a better term). It is being clarified at the moment what actions will be handled through action management and what actions will be handled directly. Once the game structures are ready in cooperating will be a more concise task.

**Comment by ecoble** [comment]
Closing Statement: We are closing this issue as it is too broad. We originally thought commands such as "GO EAST" would be handled by Game State, but the spec has changed and whether this is handled by Game State or Action Management is yet to be determined. We will instead open up new issues individually for each Game State function we want to handle, such as handling "LOOK" and inventory.

We still have the basis of functions for Save, Quit, Load, and Help.

**Comment by lydiafilipe** [comment]
Issue Score: ✓+

Comments:
Good work overall. The title however is very vague. Things that could be incorporated into it are, for example, which commands or the  type of commands
