### ISSUE TITLE
Make .proto file

### ISSUE THREAD

**Issue by ellynliu** [uchicago-cs/chiventure#42]
Look at game state structs and create a .proto file based off of the game state. Loading and saving will use this file.

**Comment by jonahdf** [comment]
Jarvis and I updated the .proto file to one of the most recent versions of Game State's structs. We had to determine a method to store pointers, since they are not supported by protocol buffers. For example, instead of storing the current room in the game message as a submessage, we decided to store it as a room id, to avoid infinite recursion. We also determined a few conventions: 
- Messages match the struct names, start capitalized, and add an "_" after (ex. "player_t" -> "Player_")
- Message members match struct members exactly
- Only use int32
- "Required" fields used sparingly—want to make most variables optional to game designer except features we rely on, such as object id) 

Unfortunately, because game state is still:
- Making drastic changes to structs
- Sorting out the issue of condition handling with action management, 
- and finally, working on providing helper functions for all the members stored in hash tables,

it is not really possible to make this a complete prototype. The most important part of this task is that now everyone in the group understands how protocol buffers generally works, and we have a strategy for handling pointers and other unsupported structures.

In the future, we must fix: 
- Members of updated structs
- Variable names of updated structs

**Comment by mpcsh** [comment]
Issue Score: ✓

Comments:
There were no progress updates here.
