### ISSUE TITLE
Write the Design Doc that will explain the structure of our code (modules, important algorithms/funcs etc..)

### ISSUE THREAD

**Issue by edward3-uchi** [uchicago-cs/chiventure#426]
Name: Eddy
team:  rpg-worldwide

**Comment by edward3-uchi** [comment]
The design document has been finished and posted on the wiki. Inside the document you can find answers to a few questions:

1. What will our modules look like?
2. How is the autogeneration algorithm generally going to work?
3. What sorts of things are going to be autogenerated?

If you have any more questions, please message any of us from team-rpg-openworld!

**Comment by dwahme** [comment]
✔️-
Good job! Here are a few things you may want to improve in future issues:

The issue did not include a descriptive summary (see https://uchicago-cs.github.io/cmsc22000/project/policies/#a-descriptive-summary for more details and concrete examples)

Your issue did not include any status updates between the opening of the issue and the closing of the issue (and this issue was not small enough to justify having no status updates at all). If you make any intermediate progress before finishing the task, then it should be documented on the GitHub issue via a comment.

Remember that Scrum board cards should be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
