### ISSUE TITLE
Create a design document for battle systems

### ISSUE THREAD

**Issue by Isaaq-Khader** [uchicago-cs/chiventure#428]
Design modules that have structs and other needed functions for a battle to occur.

**Comment by nmartinez233** [comment]
Isaaq and I met over Zoom today where we created the [Design Document](https://docs.google.com/document/d/1HO7sIoHnzswylXVdYv223QvekvQbJMudRUaWdSHIPX0/edit?usp=sharing) for Battle Systems. We specified 3 modules: The Action Manager, Logic Handler, and AI/CPU. The Action Manager will take care of all command line text the user inputs to be used in the Logic module. As the name suggests, the logic module manages most computations associated with the command line text (outside of AI/CPU moves). For that, we designed a separate AI/CPU module which enables the user to select different difficulty levels for the enemy's moves in battles.

**Comment by Isaaq-Khader** [comment]
Although we do not have structs and functions, we have three modules we will have along with sub-modules that may become functions in the foreseeable future.

**Comment by dwahme** [comment]
✔️+
Good job! Here are a few things you may want to improve in future issues:

The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies/#a-descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.

Remember that Scrum board cards shold be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.

While using Google Docs to sketch out some of the documentation, you should avoid posting links to those Google Docs from an issue, as it may cause confusion as to whether that document (or some future update to the wiki) is the most up-to-date version of that documentation. You should instead transfer the contents of the document to the wiki, and then link to the wiki when updating the issue.
