### ISSUE TITLE
Write requirements doc to detail what exactly we want to implement in terms of custom actions

### ISSUE THREAD

**Issue by sonkinss** [uchicago-cs/chiventure#430]
Name: Sergey, Emma, Annabelle
team: custom-actions

**Comment by sonkinss** [comment]
Google doc featuring user story done, included road map for how we plan to go about accomplishing things

**Comment by emmamedeiros** [comment]
https://docs.google.com/document/d/1kQxi32eDNIDfJe72I-9Zjdf53tRfBtj-ZOQHS9CuxNQ/edit?usp=sharing

Link to document, which details plan for implementation and how we plan to accomplish our tasks as we move forward 

In summary: 
1. Work on implementation for action blocks
2. Create a sequences implementation that is able to incorporate our implementation of the individual action blocks
3. Create custom traits functionality 
4. Create blocks for "conditionals" that are used
5. Implementation for reading a file and storing the custom actions in Chiventure

**Comment by MaxineK36** [comment]
Issue Score: ✔️

Comments:
Good work! The updates on this are helpful. 
A few things to work on for future sprints:
1. The issue did not include a descriptive summary (see https://uchicago-cs.github.io/cmsc22000/project/policies/#a-descriptive-summary for more details and concrete examples)
2. When an issue is done, you should include a final comment summarizing what was done, and why the issue is being closed.
3. While using Google Docs to sketch out some of the documentation, you should avoid posting links to those Google Docs from an issue, as it may cause confusion as to whether that document (or some future update to the wiki) is the most up-to-date version of that documentation. You should instead transfer the contents of the document to the wiki, and then link to the wiki when updating the issue.
