### ISSUE TITLE
Research WDL and open up communication with WDL team to plan ahead how custom scripts will fit in WDL file

### ISSUE THREAD

**Issue by tammytran134** [uchicago-cs/chiventure#448]
Name: Tammy

Team: custom-scripts

**Comment by tammytran134** [comment]
[Tam Tran-Lua scripting.docx](https://github.com/uchicago-cs/chiventure/files/4573273/Tam.Tran-Lua.scripting.docx)

**Comment by tammytran134** [comment]
https://github.com/uchicago-cs/chiventure/wiki/Lua-Scripting-and-WDL

**Comment by tammytran134** [comment]
I've written a wiki documentation that explains on a high-level how Lua will be incorporated in WDL++ based on WDL team's specification. Specifically, I have created code in C that allows me to load, pass arguments from the game (data structure, action name,..) to Lua functions and call Lua functions and return any changes implemented by the script. The next task is working with WDL team to see how WDL++ parsing work, as WDL files stand as an intermediary between C file and Lua files.

**Comment by firatciftci** [comment]
Issue Score: ✔️

Comments:
Good work! The wiki page seems thorough and it's clear that you've put in a considerable amount of work. The only issues I see are the issue creation date and summary description. Remember that scrum board cards should be converted to issues shortly after the sprint meeting on Monday, and also make sure that you have a thorough summary description for the aim and purpose of your issue, instead of just having your name and team handle.
