### ISSUE TITLE
Research and document requirements and possible interfaces with other teams.

### ISSUE THREAD

**Issue by avianurag** [uchicago-cs/chiventure#450]
avianurag
rpg-npc

- Before we begin work on the specification and design of NPC features, we must first explore what these implementations would require in terms of collaboration with other teams.
- Moreover, I will also identify the specific aspects of the existing code base that we should all be familiar with (with a focus on existing data structures).
- I will also attempt to explore the potential requirements for our modules. This may not be completed at this time, for it will require us to first flesh out our specification and design further.
- I will document these on a txt file (or perhaps a docx or tex if I think that formatting will help the structure of the document significantly).

Progress:
- I have updated the wiki found here (https://github.com/uchicago-cs/chiventure/wiki/RPG-NPC-Planning-Document:-Establishing-Dependencies.) with my contributions. 
- I am closing the issue.

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good work! The wiki page seems thorough and it's clear that you've put in a considerable amount of work. The only issue I see is the issue creation date — remember that scrum board cards should be converted to issues shortly after the sprint meeting on Monday. Also, in the future make sure that you post a separate comment for your issues' closing notes, instead of appending it to the summary description like you have done above.
