### ISSUE TITLE
Create a design plan that supports conditional connections between rooms.

### ISSUE THREAD

**Issue by victoriavillalba** [uchicago-cs/chiventure#453]
We will figure out what types of structs/information need to be accessed to make these connections and how the game needs to be changed in order to efficiently check for these conditions. 
In terms of action management, we will create a list of the things we will need/things we will need to collaborate on in order to make sure that there are pre-requisite actions for specific rooms.

**Comment by victoriavillalba** [comment]
Shé added a branch called action-management/conditional_rooms in order to organize extra code that may be necessary to execute pre-requisites for connecting rooms.

**Comment by victoriavillalba** [comment]
Shé and I developed a plan on how to make rooms conditional and wrote it out in a wiki page. It's called: Conditional Connections Between Rooms Design Plan

**Comment by victoriavillalba** [comment]
We finished the design plan and will expand on the conditional connections project in another task that works more towards implementation of our idea.

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Good work! The summary of this issue is particularly clear and useful.
One thing to work on in the next few sprints: 
Remember that Scrum board cards should be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
