### ISSUE TITLE
Research how dialogue trees work and have been implemented in other real-life projects.

### ISSUE THREAD

**Issue by shayna-k** [uchicago-cs/chiventure#455]
To start off this new feature, I will look into how dialog trees can be implemented - considering ways that have been used in other software design projects, and what we require in this particular project.
Will also have an involved group discussion thinking about this feature should be integrated in the project source code.

Progress:
Looked into ways dialog trees are usually implemented and researched about ways (xml etc.) that can be used to do so. 

Follow-up task:
Discuss the extent to which we will implement npc features such as dialog trees, with other related teams, and distribute tasks as required. (created an issue)

Name: Shayna

Team: rpg-npc

**Comment by shayna-k** [comment]
Progress:
Looked into ways dialog trees are usually implemented and researched about ways (xml etc.) that can be used to do so.

**Comment by shayna-k** [comment]
Follow-up task:
Discuss the extent to which we will implement npc features such as dialog trees, with other related teams, and distribute tasks as required. (created an issue)

**Comment by firatciftci** [comment]
Issue Score: ✔️-

Comments:
Good work! I can see that you have accomplished your task based on your comments above, but here are some notes to keep in mind for your future issues:

1. Remember that scrum board cards should be converted to issues shortly after the sprint meeting on Monday.
2. Make sure that your issue summary describes a clear goal; I can see what you have aimed to accomplish from your description above, but there should be more detail on what outcome you have gathered from your research.
3. When closing your issue, you should have a rundown of your findings, and if possible, a wiki page that showcases your work so that your group members and we can see what you have found. Ideally, your closing note should be a brief paragraph, instead of a sentence.
