### ISSUE TITLE
Communicated a time to meet with WDL team 

### ISSUE THREAD

**Issue by navila-luna** [uchicago-cs/chiventure#456]
Figured out a time to meet with the Graphics team that works. Will meet again with battle systems after they finish their own team meeting .

**Comment by navila-luna** [comment]
Met with the Graphics team to discuss the implementation of a map. Graphics in rooms were discussed. It was discusses that as of now, Graphics team shall not focus on the implementation of graphics in different rooms.

**Comment by navila-luna** [comment]
Met with the WDL team to discuss the features(potions, weapons, and different rooms according to user level) that we would like to have implemented into Chiventure. Learned that there is currently no player definition for the weapons, potions, and distinguishing level. These are features that WDL team may consider implementing through the WDL ++. They are also looking into the different kinds libraries to use to provide the file memory for all teams.

**Comment by dwahme** [comment]
✔️
Good job! Here are a few things you may want to improve in future issues:

The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies/#a-descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.

An issue should have the goal of producing something tangible, such as code or documentation, which must be specified in the summary.

Status updates on an issue should have something tangible to share.

Remember that Scrum board cards should be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
