### ISSUE TITLE
Explore and document ways to implement player classes and/or player races

### ISSUE THREAD

**Issue by shayna-k** [uchicago-cs/chiventure#465]
An independent rpg-npc feature we thought of was player races and/or player classes. I will research ways this can be implemented in the code, and the level of abstraction that would be required. In addition, collaboration with rpg-playerclass and possibly other reg teams will be necessary.

**Comment by shayna-k** [comment]
An inter-team meeting with rpg-playerclass would be needed to define and clarify npc dependencies player classes might have - and hence we would be able to successfully integrate these dependencies in npc structs as well. 
Post-meeting updates shall follow.

**Comment by shayna-k** [comment]
Post a meeting with rpg-playerclass, we concluded that this feature could be thought of collaboratively, in upcoming sprints.
Something we could add functionality for would be having certain NPCs interact with only certain player classes, or choose a certain kind of NPCs to correspond to specific player classes.

**Comment by shayna-k** [comment]
This feature essentially implied enabling the creation of a whole separate class of NPCs for a specific player class. 
This turned out to be something that should be thought of in a later sprint, and something that would require some level of collaboration with rpg-playerclass. 
The possible implementation of this was discussed in a meeting with other rpg related teams : https://github.com/uchicago-cs/chiventure/wiki/RPG-NPC-Dependencies:-Player-class,-Open-world,-Battle
Implementing this would require thinking through some details related to battle and open world as well.
I will close this issue for now and we shall take it up in a later sprint if it seems feasible.

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Great work! A few things to keep in mind:

1. Make sure that your issue title isn't too generic. Ideally, the issue title should make it clear which team and which feature the issue is tied to.
2. If your issue requires meetings with other teams, make sure that you post extensive meeting notes in your issue update comments. These notes should include who the point of contact was, when the meeting happened, what was discussed, and what are the tangible outcomes from the meeting.
