### ISSUE TITLE
Met with Graphics and coordinated a time to meet with WDL

### ISSUE THREAD

**Issue by navila-luna** [uchicago-cs/chiventure#469]
Met with the Graphics team to discuss the implementation of a map that tells the user where they are. Coordinated a time to meet today with WDL that works for both ends. Our team plans to implement weapons and potions as a feature and WDL needs to see if they need to implement these in the file.

x/rpg-openworld

**Comment by dwahme** [comment]
✔️-
Good job! Here are a few things you may want to improve in future issues:

Your issue did not include any status updates between the opening of the issue and the closing of the issue (and this issue was not small enough to justify having no status updates at all). If you make any intermediate progress before finishing the task, then it should be documented on the GitHub issue via a comment.

When an issue is done, you should include a final comment summarizing what was done, and why the issue is being closed.

Remember that Scrum board cards should be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
