### ISSUE TITLE
Write up on how libzip would work with WDL if it is used

### ISSUE THREAD

**Issue by dtbukowski** [uchicago-cs/chiventure#479]
Look to see where libzip would be implemented and how libzip would change how files are stored within the directory structure.

**Comment by dtbukowski** [comment]
Made page at https://github.com/uchicago-cs/chiventure/wiki/WDL:-Looking-into-options-to-store-JSON-objects.
Pinged Maxine (my senior dev) to check if it is up to standard in slack.

**Comment by dtbukowski** [comment]
Added descriptions of functions that will be useful for parsing the JSON objects in the zip directories.

Also changed the document to say that the user will need a zipped file rather than the game_state and other teams knowing how to use zip as other teams won't be interacting with the zipped file.

**Comment by dtbukowski** [comment]
Forgot to close issue

**Comment by MaxineK36** [comment]
Issue Score: ✔️

Comments:
This issue does many things very well, including have a clear title and tangible updates! A few things to work on for next time: 
1. An issue should have the goal of producing something tangible, such as code or documentation, which must be specified in the summary.
2. When an issue is done, you should include a final comment summarizing what was done, and why the issue is being closed.
