### ISSUE TITLE
Discuss higher level module design/layout for the generation algorithm.

### ISSUE THREAD

**Issue by edward3-uchi** [uchicago-cs/chiventure#491]
Create a design of the generation module to post on wiki and then work on implementing it for next weeks sprint. The generation module aims to generate rooms with certain items and short/long descriptions given.

**Comment by navila-luna** [comment]
Currently, there are support for rooms and items and actions for those in WDL. It's under the include/room.h and include/load_room that give a layout and load a new room. I discussed with WDL team about the implementation of a room generator that also implements different levels and  we are thinking that WDL ++ might be the best approach. They have written some examples of what the code will look like once WDL code is translated to WDL++.  I'm thinking to have three .h files to distinguish adventure, battle, and indoor rooms. However, would need to hear from my teammates and their feedback.

**Comment by navila-luna** [comment]
Created a wiki document labeled "Open World Generation Module Design layout" that describes the design for the layout/design as well as questions to consider when implementing the generation module.

**Comment by dwahme** [comment]
Issue Score: ✔️+

Comments:
Great job! Here are a few things you may want to improve in future issues:

The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies/#a-descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
