### ISSUE TITLE
Determining what class statistics we need represented by rpg-playerstat + communicating this with them

### ISSUE THREAD

**Issue by simrenk** [uchicago-cs/chiventure#494]
Team: rpg-playerclass
People: Simren

Based on the classes we have drafted + hardcoded, determine what statistics we need to have represented. Communicate this with player-stat so they can integrate this into the data-structure they are creating for information storage

**Comment by simrenk** [comment]
**5/9** Went through @PaulTreitel's writeup on classes and synthesized potential statistics from there. Informed @carlosazpurua1004 of these statistics so player-stats can incorporate them in their data structure

**Comment by dwahme** [comment]
Issue Score: ✔️

Comments:
Good job! Here are a few things you may want to improve in future issues:

Your issue did not include any status updates between the opening of the issue and the closing of the issue (and this issue was not small enough to justify having no status updates at all). If you make any intermediate progress before finishing the task, then it should be documented on the GitHub issue via a comment.

Status updates on an issue should have something tangible to share.
