### ISSUE TITLE
Identify list of potential classes and class themes

### ISSUE THREAD

**Issue by PaulTreitel** [uchicago-cs/chiventure#495]
We want a list of various classes we could support and the themes/mechanical flavors of each class. The result should include a description of each class to give the team better idea of stats and core mechanics might be necessary.

**Comment by PaulTreitel** [comment]
I've added a document [to the wiki](https://github.com/uchicago-cs/chiventure/wiki/Player-Class:-Potential-Class-List) with some classes and short descriptions of their flavor and mechanics. I won't yet close the issue just in case we decide to add to/change the list.

**Comment by PaulTreitel** [comment]
I don't think anything needs to be added to the existing list at this time so I'm closing this issue.

**Comment by dwahme** [comment]
Issue Score: ✔️+

Comments:
Great job! Here are a few things you may want to improve in future issues:

The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies/#a-descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
