### ISSUE TITLE
Create a few sample classes within the playerclass framework

### ISSUE THREAD

**Issue by PaulTreitel** [uchicago-cs/chiventure#500]
We want to have a few (~3-5) fully-fleshed-out mockups of classes. These examples should be mechanically complete with a name, stats, and actions/combat abilities like the initial design calls for. The mockups should give us a better idea of how specific individual classes will function and what might be required to make that happen. We intend to draw from the classes and themes identified by #495.

**Comment by ericbre21** [comment]
Created [a wiki page](https://github.com/uchicago-cs/chiventure/wiki/Player-Class:-Example-Stats-and-Abilities) for this task.

**Comment by dwahme** [comment]
Issue Score: 

Comments:
Great job! Here are a few things you may want to improve in future issues:

The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies/#a-descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.

Remember that Scrum board cards should be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
