### ISSUE TITLE
Develop a Design for the Implementation of Custom Actions

### ISSUE THREAD

**Issue by brentd313** [uchicago-cs/chiventure#511]
We are going to create a design document for the implementation of custom actions in Chiventure. This will entail considering the design for the implementation of both action blocks and action sequences. We plan to focus on the data structures that will provide the desired functionalities of custom actions, which are outlined in our requirements document from sprint 1. In this process, we will also consider integration into the existing code base and with other teams.

**Comment by brentd313** [comment]
As discussed above, our design will proceed from our requirements document from sprint 1, but it will also work off of the attached initial design put together by @NuclearWaffles 

Requirements Doc: [https://docs.google.com/document/d/1kQxi32eDNIDfJe72I-9Zjdf53tRfBtj-ZOQHS9CuxNQ/edit?usp=sharing](url)
Initial Design Doc: [https://docs.google.com/document/d/1_VAf-vyxNfj53l-mtSIn-LS9nS6ABe5JAXjQWJhlhIE/edit?usp=sharing](url)

**Comment by sonkinss** [comment]
Met today, in agreement on design. Will spend next 24 hours rewriting current Design Document into a bullet point format then will meet 7:30-9 tomorrow to work on implementation

**Comment by brentd313** [comment]
We met today to review the updated design document. Although the design may be adapted as we move forward consulting with other teams, we are happy with the product at the moment. The updated document is linked below.

The focus moving forward is on understanding the needs of other teams, what we will need from other teams, and to start putting the skeleton of our design into code (i.e. structures, function prototypes, descriptions, etc).

[https://docs.google.com/document/d/1_VAf-vyxNfj53l-mtSIn-LS9nS6ABe5JAXjQWJhlhIE/edit?usp=sharing](url)

**Comment by brentd313** [comment]
Converted design document to a wiki page: [https://github.com/uchicago-cs/chiventure/wiki/Custom-Actions-Design-Document](url)

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
This issue looks great overall! Two things to look out for in the future:
1. While using Google Docs to sketch out some of the documentation, you should avoid posting links to those Google Docs from an issue, as it may cause confusion as to whether that document (or some future update to the wiki) is the most up-to-date version of that documentation. You should instead transfer the contents of the document to the wiki, and then link to the wiki when updating the issue.
2. When an issue is done, you should include a final comment summarizing what was done, and why the issue is being closed.
