### ISSUE TITLE
Stub and Document Stats interface 

### ISSUE THREAD

**Issue by carlosazpurua1004** [uchicago-cs/chiventure#517]
Once the Stats Module is created, we will stub out functions, primarily so that other RPG teams have some interface from the RPG-Stats team. We will also document the function that we think are important for other teams in the wiki.

**Comment by Rusah1129** [comment]
This task partially relies on the completion of the other tasks assigned to rpg-stats...one of which made its final adjustments yesterday. This issue is mostly complete, but we plan to resolve some lingering questions among the team and finish it by tomorrow.

**Comment by carlosazpurua1004** [comment]
All of our headers are written, but we realized we don't actually have to pass the player pointer into our functions! Fixing our headers accordingly

**Comment by Rusah1129** [comment]
We have created a list of functions to implement and added their stubs to our stat.h and stat.c file, largely building off recently-designed stat structs; our work can be seen in rpg-stat's latest pull request. I am closing this issue for now, though it may be reopened to fix a few parameters due to design changes.

**Comment by ecoble** [comment]
Issue Score: ✔️+
Comments:
Great job! A couple things, be sure to convert the card to an issue right at the start of the sprint, and if your issue is going to result in a pull request, you should wait until that PR is merged to close the issue.
