### ISSUE TITLE
Documenting tasks that would be independent of other teams

### ISSUE THREAD

**Issue by shayna-k** [uchicago-cs/chiventure#523]
- unlike battle systems, which overlaps with rpg-battle, for example

**Comment by shayna-k** [comment]
After multiple meetings with the other NPC and RPG teams, we found that since we are more of a bridging team, our tasks in the first two sprints largely involved collaboration with other teams. 

We collectively came up with tasks that we should begin implementing independently in the third sprint and have begun adding them to the backlog.

By the end of sprint 2, these include:
- Writing sample code for implementing generating specific NPCs in specific rooms
- Writing sample code for inter-room movement of NPCs
- Creating a design document for implementing the basic features of quests
- Integrating player-class enum in the NPC struct

**Comment by firatciftci** [comment]
Issue Score: ✔️-

Comments:
Good work! I like the extensive summary of the issue you have in the closing comment. A few things to keep in mind for future issues:

1. Make sure that your issue title isn't too generic. Ideally, the issue title should make it clear which team and which feature the issue is tied to.
2. The issue's initial summary should be at least a paragraph long. It should include details about why you're creating this issue, your final goal, and how you are planning to achieve it.
3. If your issue requires meetings with other teams, make sure that you post extensive meeting notes in your issue update comments. These notes should include who the point of contact was, when the meeting happened, what was discussed, and what are the tangible outcomes from the meeting.
4. You should create a task mid-sprint the latest, and convert it from a scrum board item to an actual issue in 24 hours.
