### ISSUE TITLE
Implement the logic level functions for the battle system

### ISSUE THREAD

**Issue by Isaaq-Khader** [uchicago-cs/chiventure#532]
For whenever the player or enemy casts an attack, it should use the same calculation and reduce health using the calculation.

**Comment by Isaaq-Khader** [comment]
Based on the design document, the logic module should be implemented using some code from the sandbox that the battle team worked on previously. This should ensure everything is valid with return codes when possible and ensuring the battle can continue.

**Comment by Isaaq-Khader** [comment]
To make a PR simple, I decided to create my own branched named battle/logic so that once I complete my tests and everything runs as expected, I can do a separate PR instead of doing a large PR that would result in integration hell.

**Comment by Isaaq-Khader** [comment]
Currently, I have not been able to run tests since I have been filing through a lot of errors. I have most of them fixed. I set up the build for myself so that once these errors are dealt with, I can run and ensure that all functions are running as desired. I am going to reach out to my senior developer to discuss why I am getting the error I specified above.

**Comment by Isaaq-Khader** [comment]
Today, I met with my team to discuss dependencies and to clear out a few underlying issues. Based on this, I was able to understand what the `check_target()` function was meant to accomplish. So far, all of my tests pass and I am now going to begin writing tests for `check_target()` and finish writing `player_use_item()`

**Comment by Isaaq-Khader** [comment]
Currently, I met with my senior developer and we went over the errors I was getting in my code. We still have yet to resolve them. The current issue right now is that the `check_target` function is not correctly checking if an enemy exists or not. There is also an error that has to do with the `free_combatant` function. Once these errors are resolved, I will be able to make a PR.

**Comment by Isaaq-Khader** [comment]
I was finally able to figure out the issue of `check_target` with help from TAs and the professor. The functions in logic are now running as expected. I am going to make the last change of the name of the logic files into `battle_logic`.

**Comment by Isaaq-Khader** [comment]
The file names have been changed as follows:
`logic.c` -> `battle_logic.c`
`logic.h` -> `battle_logic.h`
`test_logic.c` -> `test_battle_logic.c `

**Comment by Isaaq-Khader** [comment]
The logic module has been merged into the dev branch with functions based on the design document for rpg-battle. Because of this, the issue will close.

**Comment by dwahme** [comment]
Issue Score: ✔️+

Comments:
Great job! Here are a few things you may want to improve in future issues:

The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies/#a-descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.

An issue should have the goal of producing something tangible, such as code or documentation, which must be specified in the summary.
