### ISSUE TITLE
Implementation of structs and basic functions for Battle State Module.

### ISSUE THREAD

**Issue by alex-sheen** [uchicago-cs/chiventure#533]
This sprint is dedicated to setting up the Battle State Module. This includes creating the battle struct and its init/free functions. The character struct will likely have multiple stubs and dummy values, since it is heavily dependent on code not yet implemented.

**Comment by alex-sheen** [comment]
I set up the basic folder layouts according to the developer guidelines. I then created the following files:
battle_structs.h
battle_state.h
battle_state.c
test_battle_state.c
Within these files, I implemented the battle and combatant structs with their corresponding new/init/free functions. I left stubs for many modules, including things like moves/stats/items.

The pull request can be found here: https://github.com/uchicago-cs/chiventure/pull/593

**Comment by dwahme** [comment]
Issue Score: ✔️

Comments:
Great job! Here are a few things you may want to improve in future issues:

The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies/#a-descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.

When an issue is done, you should include a final comment summarizing what was done, and why the issue is being closed.
