### ISSUE TITLE
Overhaul game_action_effect to allow for custom actions

### ISSUE THREAD

**Issue by isaacfink21** [uchicago-cs/chiventure#541]
Currently, game_action_effect only allows for predetermined action types. To allow users to make their own action types, effect structs will need to be generalized to an effect type and a list of arguments for that effect type, using the design of "action blocks" from [custom actions design](https://github.com/uchicago-cs/chiventure/wiki/Custom-Actions-Design-Document).

```
typedef struct action_block {
    enum action_type action_type;
    int num_args;
    attribute_t** args;
    AST_block* next;
} action_block_t;
```

This will require rewriting the game_action_effect struct, expanding it from using an item pointer to a union of an item with its target. We will also need to resolve any issues in other functions that will result from this change downstream.

**Comment by isaacfink21** [comment]
I met with Zak today, and we decided that I would work on the structural changes in item.h and Zak will deal with the downstream effects of changing the struct.

**Comment by NuclearWaffles** [comment]
Currently, it seems like the functions `do_effect` in `game_actions.c` (current implementation of functionality) and `do_item_item_action` in `actionmanagement.c` (it relies on the `item` pointer in `game_action_effect`) are going to be the main ones affected by our changes. 

There is also the obvious changes that need to be made to `add_action_effect` and `effect_new` in `game_action.c` that comes with refactoring all the variables in the struct. These function calls are also going to have to have their parameters changed, but it seems like the changes that need to be made to code that calls them is going to be minimal (namely due to a lack of aforementioned calls)

**Comment by isaacfink21** [comment]
This issue had been stalled while we were waiting for team custom actions to implement the effects structure. I just refactored the game_action_effect struct to accommodate these changes.

**Comment by isaacfink21** [comment]
Given time constraints and unexpected circumstances, we will not be able to implement the downstream effects of refactoring the `game_action_effect` struct, and thus will not complete this overhaul. We have opted to close the issue.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! The closing statement is clear, which is especially important since this issue didn't result in a PR.
