### ISSUE TITLE
Implement functions which allow class-item restrictions to be added and checked

### ISSUE THREAD

**Issue by simrenk** [uchicago-cs/chiventure#545]
Team: rpg-playerclass
Name: Simren Singh Kshetrapal

Last sprint, I hardcoded some examples of items + which classes could use them. This sprint, the plan is to implement a function which can add a class to the "Class Restrictions" attribute in an item + another function which, given a class and item, will check whether the item is usable by the class

**Comment by simrenk** [comment]
**5/15** Implemented functions using a hardcoded struct
**5/18** Rewrote code to take @ethanwtai's class struct into account + wrote tests
**5/19** Merged with Ethan's playerclass/struct branch and debugged until tests were passing. Created pull request.

**Comment by simrenk** [comment]
**5/21-5/22** Applied Ethan's edits. 
**5/23-5/24** Had git issues with my branch so had to recreate branch and paste relevant code into new branch
**5/25** Merged successfully!

**Comment by dwahme** [comment]
Issue Score: ✔️+

Comments:
Great job! Here are a few things you may want to improve in future issues:

For a task of this size, we would've expected to see more status updates and/or status updates that were more detailed. Specifically, the difficulties that arose due to the linked list restrictions could have been mentioned when it was encountered, before the issue was closed.
