### ISSUE TITLE
Implement the official playerclass struct

### ISSUE THREAD

**Issue by ethanwtai** [uchicago-cs/chiventure#552]
To solidify the idea of a playerclass as well as to provide a foundation for implementation, I will implement the basic playerclass struct, for instance new, init, and free functions.

**Comment by ethanwtai** [comment]
Created [a new branch](https://github.com/uchicago-cs/chiventure/tree/playerclass/struct) with the basic implementation of [the design ](https://github.com/uchicago-cs/chiventure/wiki/Player-Class:-Design-Plan) of the playerclass struct. This branch currently has a fake stats_t struct to store stats information inside and does not store action information. It also does not have any functions to get/set individual values inside the struct. The CMakeLists.txt included in [src/playerclass](https://github.com/uchicago-cs/chiventure/blob/playerclass/struct/src/playerclass/CMakeLists.txt) is based off of the CMakeLists in [src/libobj](https://github.com/uchicago-cs/chiventure/blob/master/src/libobj/CMakeLists.txt) and may be faulty.

**Comment by ethanwtai** [comment]
To create more file structure, I have split up the code into two files, one containing the structs and one containing the functions to manipulate the struct. I have also stubbed out code relating to skilltrees, combat actions, and noncombat actions. I still need to update the overall CMakeLists.txt and add tests.

**Comment by ethanwtai** [comment]
I've written the test functions Also, I've corrected the CMakeLists.txts such that chiventure compiles and executes tests without any errors.

**Comment by ethanwtai** [comment]
I've merged my code with dev.

**Comment by ethanwtai** [comment]
Since the pull request has been approved and merged into dev, I will close this issue. I've implemented basic new, init, and free functions for the class and stubbed out code that will be integrated in future tasks.

**Comment by dwahme** [comment]
Issue Score: ✔️+

Comments:
Great job! Here are a few things you may want to improve in future issues:

The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies/#a-descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
