### ISSUE TITLE
Incorporate mock skill functions into playerclass main struct

### ISSUE THREAD

**Issue by ericbre21** [uchicago-cs/chiventure#569]
This task seeks to incorporate a set of skills into the struct for playerclass, so that classes now come with their own skills, such as a basic attack for a warrior, a basic attack for a mage, etc.

Team: rpg-playerclass
Name: Eric

**Comment by ericbre21** [comment]
I am closing this issue despite not having a PR made for it, because the task has been superseded by advancements in the way skilltrees has advanced code as well as our switch to properly using custom actions for skills instead of placeholder code. After conferring with Dawson, I will be revamping the ethos of this issue for the next sprint in a way that actually fits the requirements of the way the code has evolved.

**Comment by dwahme** [comment]
Issue Score: ✔️+

Comments:
Great job! Here are a few things you may want to improve in future issues:

The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies/#a-descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
