### ISSUE TITLE
Implement mock skill functions for specific class attacks

### ISSUE THREAD

**Issue by ericbre21** [uchicago-cs/chiventure#570]
Pokemon style attack system basic implementation

Team: x/rpg-playerclass
Name: Eric

**Comment by ericbre21** [comment]
Now that we have met with rpg-skilltrees, I will apply the skills within their framework of a skill tree containing a list of skills.

**Comment by ericbre21** [comment]
Like issue #569 , I am closing this issue despite not having a PR made for it, because the task has been superseded by advancements in the way skilltrees has advanced code as well as our switch to properly using custom actions for skills instead of placeholder code. After conferring with Dawson, I will be revamping the ethos of this issue for the next sprint in a way that actually fits the requirements of the way the code has evolved.

**Comment by dwahme** [comment]
Issue Score: ✔️

Comments:
Great job! Here are a few things you may want to improve in future issues:

The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies/#a-descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.

An issue should have the goal of producing something tangible, such as code or documentation, which must be specified in the summary.

For a task of this size, we would've expected to see more status updates and/or status updates that were more detailed.

If, as part of an issue, you have a meeting or conversation with other developers, make sure to include a summary of that conversation, with an emphasis on any decisions that were made in that conversation. It is not enough to just state that you talked with someone.
