### ISSUE TITLE
Decompose interface functions into helper functions

### ISSUE THREAD

**Issue by NuclearWaffles** [uchicago-cs/chiventure#574]
Take high-level interface functions 
* `search_for_custom_action`
* `do_custom_action`
* `compile_custom_action`
* `free_custom_action`
* `get_custom_action_name`
and write out prototypes for the helper functions they would call. For simple ones such as `free_custom_action` and `get_custom_action_name`, write out a basic implementation (with the assumption that any functions called, even if just prototypes, work correctly).

**Comment by annabelleperng** [comment]
In interface.h, added a custom_action_t struct which will later be refactored into its own module. The custom_action_t will hold the contexts for each action (action, context, item, and class - these fields will be null if they don't apply), as well as a pointer to the first block (AST_block_t) in the action sequence.

We (the entire custom actions team) determined that fully implementing compile_custom_action and search_for_custom_action will likely be out of our scope for this year (they require more interaction with game-state/game.h), though we intend to hard-code a list of custom actions stored in a struct within interface.h for now so that future teams may easily change compile_custom_action and search_for_custom_action to refer to game.h when they're ready.

**Comment by annabelleperng** [comment]
In interface.c, split compile_custom_action into translate_custom_action and add_custom_action_to_game. 
- translate_custom_action translates information from an obj_h struct into a custom action (custom_action_t) struct. (An obj_h results from a custom action being parsed from a json file - see libobj/obj.h).
- add_custom_action adds a created custom action (custom_action_t) to a placeholder list of all previously-defined custom actions, mentioned in the comment above.

Also added new, init, and free skeleton functions for the custom_actions_list_t placeholder struct.

Implemented do_custom_action to refer to iterate through blocks in a sequence and call the respective helper functions for executing each block.

Notes: Stopped working in custom-actions/intial-headers branch to work in custom-actions/interface-functions. Helper functions are now located in their respective modules (helper functions for do_custom_action are now in action_block.h, branch_block.h, conditional_block.h, and control_block.h; the struct definition for custom_action_t and its associated functions are in custom_action.h. Sergey, Brent, and Emma are working on these on their respective branches).

**Comment by annabelleperng** [comment]
Replaced custom_actions_list_t struct with a hash table of custom_action_t structs. The name of each custom action (action_name) is used as a unique identifier. Implemented search_for_custom_action and add_custom_action_to_game with that in mind (and adjusted parameters accordingly).

**Comment by annabelleperng** [comment]
Communicated with WDL team about using their structs and updated interface.h to use object_t from wdl/object.h instead of obj_t from libobj/obj.h.

**Comment by annabelleperng** [comment]
Wrote tests in test_interface.c which tested the following:
- adding custom actions to the hash table
- searching for existing custom actions using name as an identifier

To test searching in detail, I created multiple test cases which deal with adding + searching for a single custom action, searching for a custom action from an empty list, adding multiple custom actions and searching for each (in a different order than they were added in), and searching for a custom action which does not exist within a list of multiple custom actions.

Created pull request ([792](https://github.com/uchicago-cs/chiventure/pull/792)), currently under the process of review.

**Comment by annabelleperng** [comment]
Added more tests to test adding custom actions specifically (without testing searching).

Made a backlog issue (#796) for translate_custom_action (which is called by compile_custom_action) to be implemented, since we didn't get a chance to fill it out this year.

The pull request has now been merged.

**Comment by annabelleperng** [comment]
Closing remarks - this issue turned out to be focused both on breaking down interface functions and implementing them, since they turned out to be closely related.

To handle search_for_custom_action, I created a hash table struct (which may be moved into game-state/game.h in the future) to hold all previously defined custom actions. The hash table uses action_name as an identifier. 

I wrote code for do_custom_action which executed individual blocks using helper functions. Later Sergey handled a similar implementation on a different branch, so I removed my implementation of do_custom_action from this branch to avoid conflicts.

compile_custom_action is dependent on two things - 1) getting/interpreting information from a parsed JSON file and 2) storing a custom action into the game's list. I split compile_custom_action into two functions,
- translate_custom_action (this is on the backlog to be implemented in the future - it translates an object_t from the WDL team, which handled parsing, into a custom action struct, custom_action_t). At the time of writing code, the module containing object_t was not yet finalized in dev.
- add_custom_action_to_game, which takes a custom action and puts it into the hash table of all defined custom actions - this got implemented
 
free_custom_action and get_custom_action_name, along with the custom action struct definition, ended up getting refactored into their own module (custom_action.c). 

Through the interface functions are not fully integrated with the rest of chiventure, we now have the framework necessary to create/add custom actions, search for them, and run them. It should be straightforward for future teams to move the list of custom actions into game.h and work with translating object_t structs.

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Good work! The closing statement is very helpful, since it includes both what was done and what wasn't. One thing to improve for future issues: even though you can add labels to issues to categorize them, you should avoid titles that could plausibly apply to multiple teams.
