### ISSUE TITLE
Finishing up documentation details of WDL++ 

### ISSUE THREAD

**Issue by blakemoss** [uchicago-cs/chiventure#578]
Continuing from last week's initial preparation of WDL++ documentation, a few details need to be added to the more general skeleton of the documentation- specifically, solidifying NPC and dialog specifications (along with any requested .json files from other teams) by communicating with the relevant teams, as well as creating a clear list of atomic actions possible within the actions.json file and adding more examples and clarification across the board.

**Comment by blakemoss** [comment]
I met with various members of the NPC teams to discuss their design requests for WDL++ and these changes were added to the existing documentation- although this is not fully finalized, it will be cleaned up along with the structure and interface documentation in our final documentation task, #688, which will be completed in the next sprint. After the structure and interface documentation has been finalized, we will begin a pull request for that issue. For now, this issue can be closed as it has been superseded by issue #688 .

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Great work! One to improve on for future issues: your issue did not include any status updates between the opening of the issue and the closing of the issue (and this issue was not small enough to justify having no status updates at all). If you make any intermediate progress before finishing the task, then it should be documented on the GitHub issue via a comment.
