### ISSUE TITLE
Implementing custom script module that allows Lua scripting changes on individual types like int, bool, char in a given chiventure struct. 

### ISSUE THREAD

**Issue by tammytran134** [uchicago-cs/chiventure#594]
Custom script will facilitate game state changes by allowing individual fields within a given chiventure struct to be changed by Lua. Specifically, we will create union structs for individual types such as int, bool, char in which there's either the type itself or a lua file path that when called, will produce the type. After this is implemented, these union structs can replace certain fields in a given chiventure struct and other modules can include custom script module to enable custom scripting.

**Comment by hugo-chan** [comment]
We decided to open this issue because our original idea of using custom scripts to support custom actions seems unfeasible at this moment in time. Speaking with one of the senior developers, we decided to change our focus to game-state where we will provide a simple yet powerful functionality for game authors as well as Chiventure developers in the future. On top of their current ability of hard-coding data (such as the description of the rooms), they will be able to generate this data through a Lua script (which will hopefully allow for more complex conditional flows in the future).

We will know this issue is finished once the code is complete, and we have written tests and are able to successfully compile.

**Comment by hugo-chan** [comment]
I just finished writing the specification of the pseudo-int, pseudo-bool, and pseudo-string structs and init and new functions for each type. The code is in `custom-scripts/game-state`. I have also written tests for each type's init and new functions. 

I am now going to write a getter function for each type, and then I will try to actually replace some of the current code with these pseudotypes.

**Comment by hugo-chan** [comment]
I just finished writing the specification of the pseudo-int, pseudo-bool, and pseudo-string structs and init and new functions for each type. The code is in `custom-scripts/game-state`. Getter functions for each of the types have also been written (except the Lua parts). We will try to replace some of the current code with these pseudotypes.

**Comment by tammytran134** [comment]
Finished completing the getter functions that involve calling Lua. Still has some difficulty with linking Lua library to cmake.

**Comment by tammytran134** [comment]
Managed to link Lua library to Chiventure. Here's the wiki page on how to do so: https://github.com/uchicago-cs/chiventure/wiki/Linking-Lua-library-to-Chiventure-on-CSIL-machine

**Comment by hugo-chan** [comment]
We had originally written a module containing these pseudotypes. However, we were given feedback on our design so we decided to rewrite the module. Now instead of having a pseudotype for each of the underlying type, we have one data structure representing all possible types. As such, this will require modifying current code and tests.

**Comment by tammytran134** [comment]
We finished modifying our design according to Borja's suggestions, specifically writing new, init, and getter functions for fundamental data types in our obj struct. We found a workaround to link Lua library to chiventure code from our own CSIL machine, and we also write tests that can interact sucessfully with Lua script. We've submitted a pull request for our codes at #640.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Good work on this issue!
