### ISSUE TITLE
Implement and write tests for functions change_stat, get_current, get_max, and get_mod

### ISSUE THREAD

**Issue by Rusah1129** [uchicago-cs/chiventure#595]
The above functions have been stubbed in the stats module and must be implemented with an updated global and local struct design. It will be closed with a pull request with the implemented functions present.

**Comment by richardxd** [comment]
Things got messy with the branch that we checked out 22 days ago(1200+ commits behind). We decided to check out a new branch and work on the new branch.

**Comment by richardxd** [comment]
Closing statement: 
The stubbed out functions have been implemented and tested. Note that tests for get_stat_mod and get_stat_max have not been written. They will be moved to the sprint backlog. Some of the functions return value has been changed to -1 when encountering a failed case because return FAILURE (1) may be in conflict with a returned modifier = 1, which is why the tests weren't written as we didn't finalize the design until the example program is merged.

**Comment by ecoble** [comment]
Issue Score: ✔️+
Comments:
Great work writing these functions! This issue could use some more thorough updates to have a better idea of what's happening.
