### ISSUE TITLE
Determine representation of room connections 

### ISSUE THREAD

**Issue by jessxia** [uchicago-cs/chiventure#60]
In the first sprint, the room struct was created to contain a linked list of "entrances," intended to be a kind of object struct that points to an accessible room from that location. We now want to develop a new way to represent connections to other rooms that can accommodate various directions (beyond north, east, south, and west) while also accounting for interactions with doors or other objects that are required to move between rooms.

This will involve communicating with the WDL and UI teams since it concerns the way rooms are connected and walk actions and changing the room struct. A new struct for "path" or something similar may be added for these connections.

**Comment by jessxia** [comment]
Our room struct now contains a hash table of a new struct called a path. The key of the hash table is a string representing the direction the player wants to move in. Each path struct contains the string ID of the room in that direction and a linked list of conditions. The condition struct contains a pointer to an object, a string representing a desired attribute of that object, and an integer value that indicates whether the condition has been met. This should support objects needing to be interacted with in order to move between rooms, such as a door that needs to be unlocked/opened or a sconce that needs to be pulled.

**Comment by borjasotomayor** [comment]
@jessxia: The integer field feels like it would be redundant. Why not check the conditions each time the player wants to move from one room to another? (otherwise, you have to take care that the integer field is always in a consistent state) This also seems to only check whether an attribute exists, which feels too limited. If you're going to place conditions on whether a user can walk from one room to another, it would make more sense to have conditions that check whether a given attribute has a specified value. For example, a "locked" attribute (in a "door" object) could have the value "yes" or "no", and a condition could specify that "locked" must be "no" for the player to be able to walk to another room through "door".

**Comment by jessxia** [comment]
@borjasotomayor Thank you! I took that into account: now the value is still either 1 or 0 but represents the value of the listed attribute. This did not change the struct.

**Comment by borjasotomayor** [comment]
Doesn't this go against how attributes are being defined in #52, where the value of an attribute can be an int, double, char*, or char value? Why constraint it to an `int` here? (and specifically to just 0 or 1?)

**Comment by jessxia** [comment]
Int value has been changed to the union used in object.h for attribute_value_t. The condition struct should hold the desired value of the given attribute.

**Comment by liuyifan-eric** [comment]
Pulled item.h/.c files (renamed object.h/.c) from the objeto branch
Need to change all the "object" in the current files to "item"

**Comment by liuyifan-eric** [comment]
We have resolved the room connections in sprint 2. We refactored the modules by adding a new path.h and its corresponding path.c, specifically for the connections between rooms. Currently, the structures we use to deal with room connections include: 
In each room, we have a hash table taking directions (north/south/etc) as keys and the whole path struct as entries; 
In each path struct, there is path_id (the key, aka directions), path_dest (the room this path leads to), and a linked list of conditions; the conditions (e.g. door open) must all be met in order to go through this path;
Each condition struct contains a pointer to an existing item (which needs to meet the condition, e.g. door), attribute name (e.g. is_open), and the attribute value (e.g. is_open = "yes"). This is consistent with the definition in item struct (attribute struct is defined in item.c and uses union).

Such design resolved the room connection issue, and the multi-level design may also benefit future improvements. For example, for action conditions (e.g. "pull sconce" requires "sconce not pulled", we may directly use the implemented condition structs. 
We also implemented a series of intuitive functions so that it would be easier for wdl/checkpointing teams to build/read the whole game struct.

**Comment by lydiafilipe** [comment]
Issue Score: ✓

Comments:
This has  good title, summary, and closing statement, and there was initially some really good progress updates, however the progress updates largely stopped after Jessica and Borja's discussion even though there was much more work done. It's important that you're continuing to make the progress updates as you are working
