### ISSUE TITLE
Implement & integrate a dialog module into Chiventure

### ISSUE THREAD

**Issue by ketchupkeith** [uchicago-cs/chiventure#607]
Based on the work completed by PR #586 (and the tasks referenced therein), we want to use our formalized conversation data structures (and functions to build/access/free them) to build a true dialog module that Chiventure will be able to use.

**Comment by ketchupkeith** [comment]
I've taken the relevant work from our sandbox file and started making the .c and .h dialogue files.  Function explanations and structs have been split into their proper header file now.  Previously-convenient features like the enum scene tag are now gone to make the module more broad-use.  

Most importantly, two new structs have been added (node_list_t and edge_list_t) in order to transition away from fixed arrays and towards compatibility with utlist.h

**Comment by SadracUchicago** [comment]
I previously created an implementation of the dialogue module before the team decided to use linked lists instead of directed graphs. This now lives in dialogue_list.c and dialogue_alt.h. I am leaving this implementation to serve as reference for any future code that could be assisted by the work I did. 

The implementation uses directed graphs. A simplified illustration of how the structure works can be seen in the image below. 

![struct](https://user-images.githubusercontent.com/40720199/82886191-0836a400-9efb-11ea-8021-272bc3d7d9ce.PNG)

Three functions operate most of the module; these being, convo_init, set_node, and set_edge. The process could have gone as follows: a dialogue structure is created (convo_init), two nodes could be set (and created) into the structure, a connecting edge could be placed in both of their connections arrays. This would constitute an operable branch of dialogue and could be extracted via get_branch. This method, in essence, uses the flexible member arrays node by node and edge by edge, preventing the allocation of all memory for all dialogue options at once. 

This implementation faces the problem of not being as memory efficient and dynamic than the linked list approach, an issue that was even larger in the previous iteration of dialogue_alt.  In that revision, all known nodes and edges were allocated via calloc() at once. All struct values were thus set to NULL or 0 and the structure was intended to not be operable until all arrays were filled and pointers correctly set. This, again, is not efficient or flexible and would be slower. 

The current implementation uses hash tables to pair edges with nodes. Edges are set by including an origin (char* from) scene (or node) and a destination (char* toward) scene (or node). A scene struct stores the scene number (int) along with the scene name (char*). When an edge is set, the two strings (scene names) are checked for a non-NULL value, and then fulfilling this requirement, their respective scene numbers are used to fetch their placement in the conversation array. This proves more efficient and preferable to, for example, iterating through the array for equivalency. In all, this experiment still contributed to the software writing process, as learning those implementations which are not optimal is an important part of determining those which are.

**Comment by lilyehsani** [comment]
I have made the following changes to this module:
- Added a hash handle to the edge struct so that it can be hashed as an `edge_hash_t`
- Added `convo_free()`, `node_init()`, `node_free()`, `edge_init()`, and `edge_free()` functions
- Separated add_node() into `node_prepend()` and `node_append()` and made them compatible with utlist macros
- Made `add_edge()` compatible with uthash macros
- Changed the outputs of `read_input()` and `transverse_edge()` to `edge_t*` and `node_t*`, respectively; made them compatible with utlist/uthash macros
- Changed `run_convo()` to be compatible with utlist/uthash macros
- Added functions `delete_all_nodes()`, `delete_all_edges()` and `node_cmp()` to help with utlist/uthash macros

**Comment by ecoble** [comment]
Issue Score: ✔️+
Comments:
Great job here, especially with such thorough updates! Issues that are closed by PR do still need closing statements.
