### ISSUE TITLE
Change class-based item attributes to use linked-lists

### ISSUE THREAD

**Issue by simrenk** [uchicago-cs/chiventure#615]
Edit functions for adding class item restrictions + checking whether a class is restricted from item use to be linked-list based. Dependent on the implementation and approval of game-state functionality for attributes being set to linked lists

**Comment by ideclue** [comment]
Currently, the mechanism for adding and checking **class item restrictions** (#614) is outlined in [https://github.com/uchicago-cs/chiventure/blob/dev/include/playerclass/class_item_restriction.h](url). The two methods include functionality for:
- Determining if a class is restricted from using an item, given the class and item
- Adding an item restriction to a class, given the class and item 
This process currently uses the `set_bool_attr` and `set_bool_attr` methods in the Game State module. However, it could be streamlined through the use of a list-based control system, where items can have multiple class restrictions (as outlined in #624).

**Comment by ideclue** [comment]
Spoke with @LapsededPacifist to discuss the `attribute_list_t` struct that is currently being built in the Game State module (#624). This struct will provide the functionality needed to add a list of class restrictions (attributes) to a single item.

In order to modify the current class item restriction framework to use `attribute_list_t`, the following will be necessary:

- Change the methods in `class_item_restriction.c` to use the `attribute_list_t` struct
- Include additional options beyond the basic getter/setter for the game developers to view what other player classes are restricted from certain items

To implement these changes, I will have to work in a new branch built off of the `action_management/attribute_list` branch which contains the current working code for the `attribute_list_t` struct.

**Comment by ideclue** [comment]
Reviewed the unmerged changes in the `rpg-playerclass/class-item-restriction` branch in order to check which of these changes are relevant to this issue. Most of the unmerged changes are deletions from the Action Management module, and will be largely irrelevant to this issue. However, an important addition I noticed were the pre-written test cases testing class item restrictions. These will be useful when testing my new implementation using attribute lists.

**Comment by ideclue** [comment]
86d92d0928b33e4d81a31a0732f85ad506f274e3

**Comment by ideclue** [comment]
Created a new branch `playerclass/class_item_restriction_lists` off of `action_management/attribute_list` to implement the changes listed above. `item` now includes a `class_restrictions` field of type `attribute_list_t` that is a linked list representing all class restrictions on a certain item. This way, class restrictions are easily accessible and are managed outside of the current framework set up for item attributes. Remaining elements of this task include:
- Adding a function to retrieve all class restrictions from a certain item
- Adding a function to remove a class restriction from an item
- Updating documentation

Potential concerns with this design include:
- Management of items in the Game State Module. So far, there are no causes for concern (all tests pass), but class restrictions are not currently included in the same hash table as other item attributes, and this may cause some unforeseeable issues.

**Comment by ideclue** [comment]
Updated function documentation and tests (which were still utilizing the old framework and not adapted to the new `class_restrictions` field of an item). In order to increase readability, I also changed the name of the function `get_class_restrictions` to `is_restricted`, as this function returns a boolean "check" of whether or not an item is restricted from a class.

**Comment by ideclue** [comment]
Successfully added tests for a new `remove_item_restriction` method. Currently, the Player Class module now supports adding an item restriction, checking if a player class is restricted from using an item, and removing a class item restriction. All functions are now implemented utilizing linked lists of attributes.

**Comment by ideclue** [comment]
Closing Statement: 

The `class_restrictions` field of an `item` now manages class restrictions via a linked-list framework. Additionally, updated functions for interacting with and adding class item restrictions have been added to the `playerclass` module.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great job! Your update comments are very detailed and informative.
