### ISSUE TITLE
Write documentation for interactions with other modules

### ISSUE THREAD

**Issue by michaelleestuy** [uchicago-cs/chiventure#622]
As we begin to implement features reliant on other teams, and as other teams begin using features that skill trees provides, it will be useful for these interactions to be well documented. The goal is to maintain a wiki page that lists out these dependencies.

**Comment by michaelleestuy** [comment]
Spoke with @ericyc16 (action management) and @richardxd (player stats) today about how our modules will be interacting. Clarified how passing effects through skills to action management would be handled, and some divisions between rpg features.

**Comment by michaelleestuy** [comment]
I pushed this issue back to sprint 4, because I expected that there would be more formalized and concrete interactions with other features that would be developed, however, it seems like we could not progress as far as we initially thought in this area, and most of our time is spent on writing test cases and finalizing the fundamental code. Therefore, I will pivot this issue slightly to further update the documentation on [this wiki page](https://github.com/uchicago-cs/chiventure/wiki/Skill-Trees:-Design-Document-and-Interface-Guide), which should serve as a guide for other teams who are interested in incorporating skill trees into their featurese.

**Comment by michaelleestuy** [comment]
[Wiki page](https://github.com/uchicago-cs/chiventure/wiki/Skill-Trees:-Design-Document-and-Interface-Guide) is now updated to reflect the current code, for version 2.1. This page will now provide a guide to interacting with the skill tree module.

**Comment by firatciftci** [comment]
Issue Score: ✔️

Comments:
Good work on this issue! The only things I'll point out are that the title is a bit too generic (ideally we should be understand which team the issue is tied to from the title), that the summary card should have more detail in terms of the purpose, the steps needed to be taken, and the goal of the issue, and that the issue should have had some update comments regarding your progress with the task, as it is difficult to quantitatively and qualitatively assess the issue with just a summary and a closing comment.
