### ISSUE TITLE
Creating functionality for setting attributes to linked lists in game-state (so that #615 can be implemented)

### ISSUE THREAD

**Issue by simrenk** [uchicago-cs/chiventure#624]
Adding a linked list struct (and associated malloc, free, init functions) and a set_linkedlist_attr function in game-state/item.c and item.h so that rpg-playerclass can eventually set items to have multiple class restrictions using just one attribute (issue #615)

**Comment by simrenk** [comment]
**End of Sprint 3** Moved to backlog because this is more game-state specific. Will be spending more time on playerclass-specific tasks for the last sprint

**Comment by jasulcaf** [comment]
4/21-4/22: Both @LapsededPacifist and I went through the documentation and various other Issues to understand what the current state of the issue was. We discovered that there already existed an attribute list `attribute_list_t` in game-state/item.h as well as an associated delete function. However, since we want other developers to create these attributes, specifically those working on rpg-playerclass, we would still need associated malloc and initialization functions. We are also considering/are unsure of if we would create a new field for `item_t` called `attribute_list_t* class_restriction` which a previous reference: https://github.com/uchicago-cs/chiventure/issues/545#issuecomment-633748707, seems to indicate. A pro to this decision would be that we would get a very clear distinction of having _class_ restriction on an item vs. _attribute_ restriction on an item (something that is currently confusing since class->name was being treated as an attribute in playerclass/src/class_item_restriction.c). The con would be having more memory associated with every item.

**Comment by jasulcaf** [comment]
After implementing an `add_attribute_to_list, list_contains_attribute, and remove_attribute_from_list` and corresponding tests, we are leaning strongly to creating a function that simply returns an `attribute_list_t` with a dummy node. This allows for a) users having an extremely simple way to create a list that can be manipulated with the mentioned functions instead of manually creating one every time, b) Allow for use of LL_ functions in utlist.h since removing the last attribute from an attribute list results in certain Crashes currently.

**Comment by jasulcaf** [comment]
Me and @LapsededPacifist decided to go with the dummy node function, which we called `create_list_attribute.` This function can be called with zero parameters and will output an empty list that can then be manipulated by the function we have added, which as a recap, are: `add_attribute_to_list` (which takes an attribute and adds it to a given list), `remove_attribute_from_list`(which removes a specified attribute from a given list), and `list_contains_attribute` (which checks if a given attribute exists within a given list). Pull Request to be done very soon.

**Comment by jasulcaf** [comment]
As a summary, this issue was opened to implement attribute linked list functionality in chiventure. This was done so that in the future, the functionality of setting multiple restrictions on an item (based on attributes) could be implemented. This issue can be closed now since there now exists functions to create and delete attribute lists, add and remove attributes from an existing list, and search if a given attribute exists in a list or not.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Excellent work! Your descriptive updates are very helpful for ensuring that any future chiventure developer can understand exactly what happened and why. I'd recommend also trying to bullet some of those updates when possible, to make it easier to skim, but the content is all there and looks great!
