### ISSUE TITLE
Implement new ast_block.c file in order to streamline capabilities for creating new AST blocks

### ISSUE THREAD

**Issue by emmamedeiros** [uchicago-cs/chiventure#636]
We will be altering the AST_block_t struct to include a pointer to an AST_block_t *next, thereby removing it from the individual block structs where it previously was located. This will allow for an enhanced design for the AST_block_t new and init functions, and allow for more simplicity as we begin to work with parsing and further implementation in the coming sprint.

**Comment by emmamedeiros** [comment]
AST_block_t new/init functions have been re-implemented. In Sprint 4, we will be adding functionality for an AST_block_t *next within the existing AST_block_t struct. We want to spend more time learning about the exact implementation (which will be done using ut list), and therefore  this issue will be closed, and a new issue for the continuation of AST_block_t modification will be added to Sprint 4.

**Comment by MaxineK36** [comment]
Issue Score: ✔️

Comments:
This issue has a great title and description, but your issue did not include any status updates between the opening of the issue and the closing of the issue (and this issue was not small enough to justify having no status updates at all). If you make any intermediate progress before finishing the task, then it should be documented on the GitHub issue via a comment.
Additionally, this issue was created very late in the sprint. Remember that Scrum board cards should be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
