### ISSUE TITLE
Redesign test code and implementation for action, conditional, control, and branch blocks 

### ISSUE THREAD

**Issue by emmamedeiros** [uchicago-cs/chiventure#637]
Given our team's choice to move the location of the AST_block_t *next pointer into the AST_block_t struct, we will need to reconfigure the struct functions and tests in order to properly implement this change. We also decided to delete our "attribute_functions" .h and .c files, given that we decided that the functions held within them seemed redundant given functions available from the "game-state/item.h" file. Therefore, we also will be updating these files to include those functions, rather than the previous attribute functions that we had defined.

**Comment by emmamedeiros** [comment]
Code has been re-implemented and is currently being tested/debugged.

**Comment by emmamedeiros** [comment]
Code has been debugged and has passed testing. This has been separated into five pull requests, one for each action, conditional, control, and branch module, along with the addition of the AST_block module. Given that requests are being submitted, this issue will be closed.

**Comment by emmamedeiros** [comment]
I accidentally closed this yesterday!! The code is currently undergoing review for a pull request.

**Comment by emmamedeiros** [comment]
The struct functions have now been implemented, tested and merged into dev, and the respective custom-actions branches have been deleted. These functions are now found in tests/custom-actions, src/custom-actions/include, src/custom-actions/src and any respective makefiles have been updated as needed. This issue will now be closed.

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
This issue looks good overall! Two quick places for improvement:
1. Remember that Scrum board cards should be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
2. For a task of this size, we would've expected to see more status updates and/or status updates that were more detailed. This seems like it was partly because the issue was created so late after work had begun on it.

$COMMENTS
