### ISSUE TITLE
Communicate with rpg-NPC to see if they need functionality for setting NPCs to a specific class. Implement functionality if so.

### ISSUE THREAD

**Issue by simrenk** [uchicago-cs/chiventure#670]
Playerclass would like to communicate with rpg-NPC to see if they need functionality for setting NPCs to a specific class. We would implement this functionality if so.

**Comment by simrenk** [comment]
**5/26** Asked rpg-NPC if they need classes implemented in dev-rpg channel. Awaiting further communication

**Comment by simrenk** [comment]
**5/26** Met w/ @anshikab and explained how the class struct works + that rpg-NPC can likely assign classes to NPCs by adding classes to their own struct. They will proceed with this methodology and currently do not need any functions implemented.

**Comment by simrenk** [comment]
**5/31** Merged PR #720 which replaces the hardcoded stats stub struct with playerstat's actual stat and effects hash structs

**Comment by simrenk** [comment]
**Closing:** After modifications to classes struct which include playerstat's actual stat and effects hash structs, NPC was able to add class to their struct.

**Comment by dwahme** [comment]
Issue Score: ✔️+

Comments:
Great job! Here are a few things you may want to improve in future issues:

The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies/#a-descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
