### ISSUE TITLE
Integrate Player Class with Battle 

### ISSUE THREAD

**Issue by Purrsephone** [uchicago-cs/chiventure#672]
Replace the class stub structs in battle code with the real player class implementation. This may involve meeting with the player class team. Fix all affected functions and tests.

**Comment by Purrsephone** [comment]
The class struct stubs in battle code were replaced with the real implementation from player class.  See PR #696. This is a step towards full integration in the future.

**Comment by dwahme** [comment]
Issue Score: ✔️+

Comments:
Great job! Here are a few things you may want to improve in future issues:

Your issue did not include any status updates between the opening of the issue and the closing of the issue (and this issue was not small enough to justify having no status updates at all). If you make any intermediate progress before finishing the task, then it should be documented on the GitHub issue via a comment.
