### ISSUE TITLE
Create an executable that uses modules of battle

### ISSUE THREAD

**Issue by Isaaq-Khader** [uchicago-cs/chiventure#673]
In this sprint, we should either create an executable that involves what is already inside of Chiventure or a separate executable that demonstrates the functionality of the modules of battle-systems.

**Comment by alex-sheen** [comment]
Todo:
- Coordinate with action management on how to start a battle and how player actions will be redirected to battle systems
- Implement battle flow "loop": 
1. carry out player move
2. ai module chooses an enemy move
3. carry out enemy move
4. return battle struct to action management

**Comment by Isaaq-Khader** [comment]
So far, we have been able to add into our executable the ai choosing an enemy move, executing that enemy move, and returning the ctx battle struct we have. Alex and I have created tests and everything passes as wanted so far. We are going to create a PR with what we have now so we can ensure everything makes sense and we will add onto the code from there.

**Comment by dwahme** [comment]
Issue Score: ✔️

Comments:
Great job! Here are a few things you may want to improve in future issues:

The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies/#a-descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.

When an issue is done, you should include a final comment summarizing what was done, and why the issue is being closed.
