### ISSUE TITLE
Get CLI/split screen example into sandbox

### ISSUE THREAD

**Issue by xmvalencia** [uchicago-cs/chiventure#675]
_Sprint Summary:_
A CLI screen with an image is a large checkpoint for the graphics team. This means being able to display graphics and the command line interface at the same time. An example of what that looks like has been previously made by members within the graphics team, the main hurdle for this sprint is to implement a method to accept input and display a reaction to that input. This issue is a step to our main goal of then being able to integrate it into chiventure and create examples into the examples folder, which is further elaborated in issue #676. 

_Products of Sprint:_
Briefly described in summary, the products of this sprint are to create a split screen example in the sandbox that can take in user input and produce an output. This will help us understand interactions between the user and raylib and it's ability to produce responses. We will also be adding a sandbox directory into the chiventure/src/ui folder and make a PR to add it into the 'master' branch. 

_Example Image:_
![image](https://user-images.githubusercontent.com/52059114/83214801-507fdd00-a11a-11ea-9658-88f34f147e99.png)

**Comment by aherman33** [comment]
I've added to the existing program from #585 which displays an image, an output textbox, and an input textbox. The text in that program was static, but the code has now been updated to display different text in the output box depending on the command given in the input box. Here is an example of a "look" command and its associated output below:
<img width="803" alt="Screen Shot 2020-06-02 at 3 15 14 PM" src="https://user-images.githubusercontent.com/63211362/83565894-c605f780-a4e4-11ea-8f70-5e067c58e940.png">

Here is another example of a "grab" command and its associated output below:
<img width="802" alt="Screen Shot 2020-06-02 at 3 18 06 PM" src="https://user-images.githubusercontent.com/63211362/83566092-0ebdb080-a4e5-11ea-9c24-6913da75e939.png">

The output will only update upon pressing enter, however, we still need to fix the program so that the input is properly cleared once enter is pressed. In addition to this, I have been updating this program on my Mac. We will eventually need to move this program to a VM to ensure that everything works properly and can eventually be added to chiventure.

**Comment by xmvalencia** [comment]
_Sprint Update:_
The examples developed by Abby in the previous update works on the VM

**Comment by xmvalencia** [comment]
_Sprint Update:_
We managed to implement an indicator for the text box as well as creating a way to clear output after the user hits enter, after hitting enter the prompt on the window now reacts to the specific command that was inputted by the user. This was all run on the VM as well.


**GIF Example:**
![example](https://user-images.githubusercontent.com/52059114/83577337-c607f680-a4e8-11ea-8df9-5a6290c3af0f.gif)

**Comment by xmvalencia** [comment]
_Closing Statement:_
This issue is being closed, seeing that we produced a CLI/Split screen that can take in user input, have the window respond with a specific response and clear the text in the text box after the user has hit enter. A blinking indicator for the text box was also added. All this was created in the sandbox, meaning on the developers personal machine so there won't be anything for the projet members outside of the members working on this to view. These sandbox examples will, however, be used as a building block for the integration into the examples folder of chiventure and eventually into chiventure itself.

**Comment by xmvalencia** [comment]
_Sprint Purpose and Summary_:
This sprint's purpose was to create a cli/split screen example for the sandbox. This would allow us to look at the implementation for future use in the development of the ui code, especially in the development of graphics and it's connection to the CLI. 

_Products of the Task_:
We created a way to display an image uploaded by the game author and a screen that can react to commands given in a text box by the user using raylib. This sandbox example was successfully merged into `dev` branch.

![example](https://user-images.githubusercontent.com/52059114/83577337-c607f680-a4e8-11ea-8df9-5a6290c3af0f.gif)

**Comment by ecoble** [comment]
Issue Score: ✔️++
Comments:
Great work here, and great job giving frequent updates!
