### ISSUE TITLE
Finish implementing skill tree code

### ISSUE THREAD

**Issue by VannStrasen** [uchicago-cs/chiventure#706]
With PR #697, Jackie and I did not finish writing all of the code necessary to implement skill trees fully. With help from code that Jackie wrote for a (now outdated) version of the skill trees structs, I will finish writing the necessary functions for skill trees and create a pull request for this issue.

**Comment by VannStrasen** [comment]
This work will be implemented in the branch skilltrees/skill_tree_additional_functions, which is branches off of skilltrees/skill_tree, a branch that is currently in the process of being approved for a pull request.

**Comment by firatciftci** [comment]
Issue Score: ✔️

Comments:
Good work on this issue! The only things I'll point out are that the title is a bit too generic (ideally we should be understand which team the issue is tied to from the title), that the summary card should have more detail in terms of the purpose, the steps needed to be taken, and the goal of the issue, and that the issue should have had some update comments regarding your progress with the task, as it is difficult to quantitatively and qualitatively assess the issue with just a summary and a closing comment.
