### ISSUE TITLE
Extra input in game-action's add_action_condition function

### ISSUE THREAD

**Issue by Dumplingz** [uchicago-cs/chiventure#713]
The (now outdated) function 
`add_action_condition(item_t *item, game_action_t *action,
                         item_t *cond_item, attribute_t *cond_attribute, attribute_value_t cond_value)`,
located in game-state's game_action, has two `item_t*` inputs, `item` and `cond_item`. 
This function adds a condition that checks whether the item's attribute matches the attribute value given. However, currently `cond_item` is only checked if it's not null and has no other uses, while `item` is actually given to the condition to compare its attribute against.

The function's successor, `attribute_condition_new`, still only includes one item.

Suggestions:
- Remove this extra field entirely, since the function works correctly without it
- Make use of `cond_item` as something related to the action condition (for example, a key to open a door).

**Comment by afranzese99** [comment]
After extensively looking through game_action.c, game_action.h, condition.c, and condition.h code and commit history   @WPDolan and I believe that the issue was resolved by the original poster but rather than closing the issue, the poster edited his comment (See Commit 963015: `add_action_condition` removed `item` field, `cond_item` is doing what `item` formally did; Commit 33dfba: `add_action_condition` -> `add_action_attribute_condition`). It appears they refactored the code such that `add_action_condition`'s original functionality has been moved to `add_action_attribute_condition `(found in game_action files) and `attribute_condition_new` (found in condition files).

**Comment by WPDolan** [comment]
Extra input `item` was removed with `cond_item` taking its functionality and `add_action_condition` was refactored to `add_action_attribute_condition` in previous commits. No further action is necessary.

**Comment by MaxineK36** [comment]
Issue Score: ✔️++

Comments:
Great work! You did a really good job documenting exactly what you examined to determine that this issue didn't warrant any code changes, and then clearly summarizing this in your closing statement.
