### ISSUE TITLE
Create sample NPC/dialogue program for presentation

### ISSUE THREAD

**Issue by lilyehsani** [uchicago-cs/chiventure#715]
We want to create a sample NPC/dialogue program. We already have a good, working version of a dialogue from the sandbox. For a more complete example, we expect to:
- Add descriptions to NPCs
- Add commands to look at and talk to NPCs
- Add command to ignore (stop talking to) NPCs

We will do these (hopefully) in chiventure in general, but the fall-back option is to do them within the example program. Additionally, we are depending on successful pull requests of our dialogue module, as well as of rpg-npc's room functions (though we can also write these in the example if necessary).

**Comment by SadracUchicago** [comment]
I was running several valgrind tests when I noticed a memory-related misuse of strncpy(). Maximum buffer sizes are defined by macros in dialogue.h, with `#define MAX_KEY_LEN 30` and 
`#define MAX_QUIP_LEN 100` Overflow can occur because there is no method in the code to detect a string that exceeds this length. Because of the formatting methods in the program, strings actually take up more bytes than expected 
![graph_c](https://user-images.githubusercontent.com/40720199/83596945-d1741580-a51a-11ea-84db-693c1bfc74e1.PNG).

As the image shows, the top char array (i.e. string) exceeds the size of what the bottom char array has allocated in memory. This is what leads to an invalid Read Size of 1, because the formatting requires additional space to store '' characters, for example. This could be fixed by changing the range of max sizes or cross-implementing a parsing method that would detect the overflow before it happens.

**Comment by lilyehsani** [comment]
The max lengths were chosen intuitively, and will be extended now that the need has been shown.

**Comment by lilyehsani** [comment]
I have created a branch called npc/example for work on this issue.

**Comment by ecoble** [comment]
Issue Score: ✔️+
Comments:
Nice work with this program and checking for memory leaks! Issues that are closed by PR do still need closing statements.
