### ISSUE TITLE
Make a conditional room connection demo for the presentation

### ISSUE THREAD

**Issue by victoriavillalba** [uchicago-cs/chiventure#724]
After all the errors are fixed and our issue is fully implemented, we must make the game that demonstrates the purpose of our code.

**Comment by victoriavillalba** [comment]
This issue was unnecessary because a demo issue for the group was concurrently made. To look into more details about this issue and the demos related to this one, got to issue #667

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Good work overall - the link to the newly created issue that supersedes this one is helpful. One thing for future issues: the summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies/#a-descriptive-summary for examples). It should also explain explicitly what's being done, as the person looking at this issue may not have seen any previous related issues.
