### ISSUE TITLE
Create a parse manager for the battle

### ISSUE THREAD

**Issue by Isaaq-Khader** [uchicago-cs/chiventure#757]
In this issue, the executable for rpg-battle should have a parse manager so that the user has a way to type in commands to continue a battle.

**Comment by Isaaq-Khader** [comment]
So far, the executable is almost complete, however, it does not take in the input correctly. It expects 5 strings even though the intention was to have up to 5 strings. Because of this, I spoke with my senior developer and he mentioned that I could use `fget` to accomplish this. I am currently working on it now and hoping to have it completed by end of day.

**Comment by Isaaq-Khader** [comment]
Currently, we are really close to a PR. The issue was integrating with player class and using their created moves for battle. After meeting with Alex and Sophie, we were able to integrate with them successfully and it reads the moves as we expect. But now, the battle is not functioning properly which is next on the list to fix.

**Comment by Isaaq-Khader** [comment]
The parse is complete along with the executable! It beautifully displays a battle in action. Starting a PR now!

**Comment by Isaaq-Khader** [comment]
The executable was created that allows for user input. The executable covers the use of a move along with displaying possible moves. This is a nice basis for the future rpg-batle developers to begin working off of to test their code or other functions such as those that involve items.

**Comment by dwahme** [comment]
Issue Score: ✔️+

Comments:
Great job! Here are a few things you may want to improve in future issues:

The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies/#a-descriptive-summary for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
