### ISSUE TITLE
A number of commands relating to get_supported_actions

### ISSUE THREAD

**Issue by yoonsjeong** [uchicago-cs/chiventure#76]
After discussing with another team is seems that in addition to a get_supported_actions function (which returns a linked list of action structs given an input of the action kind enum), 
we should have a function that will take a list of action structs (the output of get_supported actions) and a specific action enum, and return the action struct that is identified by that enum.

It would look something like
> action_t get_action_struct(list_t *search, enum action_type query)

additionally, an idea we got from CLI is to set all the enum action_types equal to the respective KIND number it is represented by, to facilitate a much easier way of finding things.
So for example, the enum EAT would be set equal to 1, since it is a KIND 1 action, USE_ON would be set equal to 5 since it is a KIND 5 action. This way, one could call get_supported_actions(EAT) to get a list of all KIND 1 actions, one of which will be EAT.

**Comment by borjasotomayor** [comment]
Why is this function necessary? Can't they just iterate over the list and look for the struct that matches the given enum?

Setting the action type enum values to their kind values is not a good idea: this basically invalidates the action type enum, because actions of the same kind will be indistinguishable. You should have separate enums for the action types and another one for the action kinds. However, all of this seems to hint towards the fact that the action type may not be necessary at all.

**Comment by borjasotomayor** [comment]
Also, please make sure that your issue titles are complete sentences (e.g., "Implement a number of commands relating to get_supported_actions")

**Comment by yoonsjeong** [comment]
I wasn't sure if that process of iterating over the list to look for the struct was a function we needed to cover as well--would CLI be implementing a function (or a series of commands) to execute this search?
I will clarify with CLI since it seems I overlooked the fact that CLI should be starting with a string rather than an enum, which means they could find the kind by using the action struct.

I will close this issue because it is not necessary
