### ISSUE TITLE
CLI/Split Screen and Map example

### ISSUE THREAD

**Issue by xmvalencia** [uchicago-cs/chiventure#812]
tie the map and the cli/split screen example together. Reference the design document for placing the map in the top right corner. This will most likely result in a new example (splice split_screen.c and map_raylib_example.c together in folder src/ui/examples)

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Good job picking up this backlog issue! When you do that, make sure you update the milestone to the current sprint. One area of improvement for next time: Your issue did not include any status updates between the opening of the issue and the closing of the issue (and this issue was not small enough to justify having no status updates at all). If you make any intermediate progress before finishing the task, then it should be documented on the GitHub issue via a comment.
