### ISSUE TITLE
Research ANTLR library

### ISSUE THREAD

**Issue by r-e-stern** [uchicago-cs/chiventure#822]
In parallel with four other libraries we're researching, we aim to research the [ANTLR ](https://www.antlr3.org/) parsing library, and to assess its possible use in the CLI++/DSL features. We'll write a pro/con list, and possibly some sandbox code.

Assignees: R.E. and Jack

**Comment by r-e-stern** [comment]
I also read the ANTLR documentation for both versions 3 and 4 (I later discarded v3, whose GitHub repository hasn't been updated in five years), and installed, built, and ran ANTLR v4's examples on my local machine:

**Pros**

- ANTLRv4 is _extremely_ compact. Its parser appears to require only a short specification of which structures it is seeking. Its quick-start example is four lines long. This may make it easier than other parsers to implement.
- ANTLR appears to be widely recognized (GitHub recognizes its `.g4` file extension), well-maintained, and frequently used.

**Cons**

- The documentation is possibly inaccessible. The ANTLR v4 website has a documentation section that frequently refers to a [book on the language](https://pragprog.com/titles/tpantlr2/the-definitive-antlr-4-reference/) that costs $27. Many of the relevant sections are available for free online; some are not. Having crucial documentation behind a paywall seems... less than ideal.
- ANTLR is primarily Java-based. It features _parsers_ that work with C and other languages but not code generators (it does appear to support C++). We discussed this in a meeting today and learned that several members of our group are not familiar with Java. This would also make it not suited to

**Comment by jacknugent1529** [comment]
I looked into ANTLR as an option for writing parsers in C. Since the fourth version did not support C, I primarily focused on the third version. I tried installing and running antlr3 on my local machine, but was not successful primarily due to lack of documentation. Overall, I concluded that we should not use antlr3 based on the reasons below

1. The github repository has not been updated since 2015, and the documentation has not been updated since 2009
2. When installing the c version of antlr 3, many of the webpages referred to by the readme no longer exist (or never existed)
3. The documentation that does exist seems incomplete, especially for the c-specific documentation

**Comment by r-e-stern** [comment]
Because ANTLR v3 has not been updated recently, and because our team probably doesn't have enough time to learn Java _and_ 
figure out how to implement the DSL in ANTLR v4 in Java, we decided not to use this library, instead preferring one of the Python-based parsers from #834.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Great job! The updates are great, as well as the clear closing statement. In the future, it would be better to put this research documentation into a Wiki page for your team, so that it is easier to reference in the future.
