### ISSUE TITLE
Write up documentation mapping out how openworld will need to connect to the rest of chiventure

### ISSUE THREAD

**Issue by wmingyan** [uchicago-cs/chiventure#830]
We would like to connect openworld to the rest of chiventure. Before doing this, we should go over the existing codes and create a wiki page that specifies which files will be involved and what potential functionality might we need to add.
Assignees: Mingyan, Justin, Sumaiya
team: openworld

**Comment by wmingyan** [comment]
Created [a wiki page](https://github.com/uchicago-cs/chiventure/wiki/Open-World:-Potential-connections-to-the-rest-of-chiventure) that maps out how openworld will need to connect to the rest of chiventure and specifies which files will be involved according to potential functionality we might need to add in the future.

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Good work overall! A few areas of improvement for next time:
1. This issue was created fairly late (and seems to still have some holdover text from being a card); remember that Scrum board cards should be converted to issues shortly after the Sprint meeting. Think of the Scrum board card as a rough outline of the issue, which you then need to flesh out with a more descriptive title and summary when converting it to an issue.
2. For an issue like this, which requires doing some deep dives into chiventure code, you should include some updates explaining what kind of investigation you're doing and what (if anything) is being left out. If this ended up being minimal, you can include it in the closing statement.
