### ISSUE TITLE
Write documentation for existing potential integration approaches + potential final approach (and why)

### ISSUE THREAD

**Issue by Justin08784** [uchicago-cs/chiventure#831]
Teams from previous years have outlined two possible approaches (lazy and eager) for integrating openworld into chiventure. We would like to document the pros and cons of these existing approaches and tentatively decide on a final approach, which could be either, neither, or some combination of both. We should create a wiki page for documentation.

Assignees: Justin, Sumaiya
Team: openworld

**Comment by Justin08784** [comment]
Wiki page for documentation:
https://github.com/uchicago-cs/chiventure/wiki/Open-World:-Deciding-an-integration-approach

**Comment by MaxineK36** [comment]
Issue Score: ✔️

Comments:
Good work overall! A few areas of improvement for next time:
- Even though you can add labels to issues to categorize them, you should avoid titles that could plausibly apply to multiple teams (in this case, your title should have mentioned that these were integration approaches for open world)
- Your issue did not include any status updates between the opening of the issue and the closing of the issue (and this issue was not small enough to justify having no status updates at all). If you make any intermediate progress (e.g. learning something about the existing code) before finishing the task, then it should be documented on the GitHub issue via a comment.
Also, please make sure to remove holdovers from the cards (e.g. "Assignees:" in the text)
