### ISSUE TITLE
Read through the "RPG Battle Systems: Design Document" wiki page and source code README, and update them.

### ISSUE THREAD

**Issue by lczielinski** [uchicago-cs/chiventure#839]
Summary: Currently, there exists an RPG Battle Systems Design Document on the wiki page, and we will go through the page together, updating it by reading through existing battle code. We will also communicate with other members on our team who are going through different battle wiki pages to figure out if we want to combine them.

Assignees: Elsa and Laura
team:battles

**Comment by lczielinski** [comment]
We read through the design document, and it seems up-to-date with all struct and function information. A few were missing fields, which we filled in. We will now focus on looking through the current tests and examples for battles, finding out what tasks we can work on first, and updating the README for src/battle.

**Comment by Elsa-Athiley** [comment]
We are currently unable to run any example battles by following the instructions in battle/example/README.md. The first direction is to run make however there is no Makefile already present. Using cmake to create a build directory solves this issue and allows us to run make however we get this error. We will try to resolve this problem so that the examples can be run and we can test all current functionality.

<img width="1091" alt="Screen Shot 2021-04-25 at 6 19 49 PM" src="https://user-images.githubusercontent.com/67703631/116012895-ece48500-a5f2-11eb-8134-237783fe7ebf.png">

**Comment by lczielinski** [comment]
After meeting with Maxine, we figured out how to run the current example (run make examples inside the build folder, then run the executable battle_command_example from inside build/src/battle/examples). For next sprint, we will make updating the "examples" README an issue, since the directions in that file were confusing and incorrect.

**Comment by Elsa-Athiley** [comment]
We have finished this issue. We were able to go through the wiki page and the README's and make sure they were up to date and matched the current code, we added any information that was missing. Once our pull request is reviewed we will close this issue.

**Comment by firatciftci** [comment]
Issue Score: ✔️++

Comments:
Great job! The summary is to-the-point and the updates you've made do a clear job of showing your progress on this issue.
