### ISSUE TITLE
Battle Systems Wishlist

### ISSUE THREAD

**Issue by jintae412** [uchicago-cs/chiventure#854]
Summary: Go through the "Battle Systems Existing Code Review" wiki page and see what tasks have been left undone, as well as familiarize ourselves with the implementation of the currently existing code.

Assignees: Matthew and Sonny
team: battles

**Comment by jintae412** [comment]
We have looked through the tasks listed on the "Battle Systems Existing Code Review" wiki page and have gathered a list of the tasks that remain undone, as well as other tasks we may be able to do to build on what the previous team accomplished. In addition, the previous group made a "RPG Battle Systems | User Stories" wiki page that we could draw ideas for features to implement from. We will put these together into an wiki page of our own.

**Comment by jintae412** [comment]
Finished. The wiki page has been created [here](https://github.com/uchicago-cs/chiventure/wiki/RPG-Battle-System-Wishlist).

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good job overall! Below is some feedback to improve upon with regards to future issues:
- The title of an issue has to convey what the issue will be producing. In the future, try using simple titles with a "Verb-Object" structure that clearly states what you will be doing in the issue (e.g., “Design and implement a ‘circle’ module”, “Research libraries for drawing simple geometric shapes”, etc.)
- The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies.html#tasks-issues for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
