### ISSUE TITLE
Write user stories for DSL (whole team involvement)

### ISSUE THREAD

**Issue by r-e-stern** [uchicago-cs/chiventure#861]
We will write one or more user stories featuring sample prototype use cases for the new domain-specific language, focusing on how our DSL will allow us to make the WDL more concise, less formatting-error-prone, and more intuitive and human-writeable.

**Comment by r-e-stern** [comment]
We had a meeting at which we discussed the features we'd like to see in the DSL, and created a (prototype) sample DSL file.

**Our desired features of DSL:**
- It should be easy for a user with no knowledge of Chiventure whatsoever to quickly write a simple item or room in the DSL in 1-2 lines.
- Whereas WDL is human-readable, the new DSL should be *both* human-readable and human-writeable.
- In comparison to WDL, the DSL should have a relatively generous syntax and/or grammar.
- The DSL should be far less reliant than WDL on punctuation (`"';.-`, etc) or indentation for the structure of its definitions.
- The DSL should feature a lot of default settings, to allow for quick and easy definitions of rooms or items, with default parameters left implicit.
- The DSL should allow easy deployment of common synonyms for actions.
- If possible, the DSL should allow users to declare any room or item anywhere in the file.

We then 'translated' a sample WDL file into a prototype version of DSL that accommodates these features. We used the [test_game.wdl](https://github.com/uchicago-cs/chiventure/blob/e9d9e8e66977a5a76a358abd83a300bba6d65dbc/src/action_management/examples/test_game.wdl) file in the `/src/action_management/examples/` directory:

The game is declared succinctly and clearly:
```
GAME START dining room END bedroom
   	intro: Welcome home! You just got back from a long day of work at Company X. You're exhausted, and think that it'd be best to just eat some dinner and go to bed. You're currently in your dining room, and dinner is on the table.
	end condition: dinner eaten
```
A room is declared compactly and its connections are made simple and readable:
```
ROOM living room
	short: Kevin's living room.
	long: The room is sensibly decorated.
	connections: NORTH to dining room, EAST to bedroom, WEST to bathroom
```
Here an item is declared with the `short` parameter unspecified, which is handled by assigning it a default short description. The actions are defined readably:
```
ITEM door IN living room
	long: This door leads to your bedroom.
	actions: OPEN, KICK
		OPEN success: You open the door.
		OPEN fail: You can't open the door.
		KICK success: The door applauds your marvelous kick... and then breaks.
		KICK fail: You stub your toe. Loser!
```
By using default parameters, we can shorten the specification of a room to three lines:
```
ROOM kitchen
	long: You see various eating utensils scattered everywhere.
	connections: WEST to dining room
```
We can also override default descriptions, and add synonyms for actions. Here `DEVOUR` works in place of `EAT`, and the resulting WDL file will reflect the two actions as having the same success and failure. The terms `fail` and `failure` used while specifying action results are also interchangeable, to make the language more fault-tolerant:
```
ITEM salad
	short: A green salad.
	long: A side salad. Nothing remarkably special about it.
   	actions: EAT = DEVOUR, ROLL AROUND IN, CRITICIZE
		EAT condition: fork is in inventory
		EAT success: You eat the salad. You feel quite satisfied.
		EAT fail: You cannot eat the salad.
		ROLL AROUND IN success: You roll around in the salad. You feel like a very big vegetable.
		ROLL AROUND IN failure: Alas, you cannot roll around in the salad.
		CRITICIZE success: You say 'This salad could use more lettuce.' You smile, because you know deep down you're right.
		CRITICIZE failure: Try as you might, you cannot find anything negative to say about this excellent salad.
```

**Comment by jacknugent1529** [comment]
Another thing to consider would be allowing allowing variables in the language. This might function similarly to [Sass](https://sass-lang.com/guide) where variables are denoted by a dollar sign. While the readability would decrease slightly, this would make it easier to create complex games which might reuse objects in different rooms. This would also result in less repetition of code which seems to be an issue in the `games/forks.wdl` example.

Taking this concept further, we could support template strings with unspecified variables in a similar manner to python's f-strings. This could look something like
```
$sentence = Sentence with {var1} and {var2}

$sentence {var1: abc, var2: def}
```
Here, the first reference to `$sentence` is declaring the variable and the second reference would be replaced with "Sentence with abc and def". 

The above two features could be used to create template objects which would drastically simplify the `forks.wdl` example. For example, we could declare
```
$fork = "
ITEM Fork IN {room}
    short: A fork.
    long: A fork. There's nothing remarkably special about it.
"
```
The rest of the file could look something like
```
$fork { room: kitchen }
    actions: TAKE
        TAKE success: You take the fork
        TAKE fail: You can't take the fork

$fork { room: kitchen }
    actions: OPEN
        OPEN success: You open the fork
        OPEN fail: You can't open the fork
```
This syntax would make it much easier to place a fork in different rooms, and if we wanted to change the long description, we wouldn't have to edit every single instance of the forks.

The language should also allow us to override certain values such as
```
$fork { room: kitchen }
    long: A fork. There is something remarkable about it.
```
Here, the long description given above would take precedence over the long description declared with the fork variable. Overall, this does does make the language more complex, but since these features are not necessary to use, beginners could still create games without difficulty. Furthermore, experienced game designers would have more powerful tools to avoid repeating themselves and create games more quickly.

**Comment by r-e-stern** [comment]
The requirements/goals/specifications we talked about here have been transferred to the newly created [DSL: User Stories wiki page](https://github.com/uchicago-cs/chiventure/wiki/DSL:-User-Stories).

Closing the issue.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Excellent work! Your updates are super detailed and the wiki is great as well.
