### ISSUE TITLE
Document, plan, and prepare customs actions code for integration into action-management and Chiventure

### ISSUE THREAD

**Issue by LapsededPacifist** [uchicago-cs/chiventure#878]
Explore the current state of customs actions and update the documentation. Includes looking at existing custom actions issues.
Make make minor code adjustments and clean up existing issues to prepare for integration into action-management and chiventure.
Document/Update existing documentation about a plan for integrating the custom actions code into Chiventure.

**Comment by LapsededPacifist** [comment]
Documentation for the current state of Custom Actions and future plans has been added to [Current State and Future Plan of Custom Actions](https://github.com/uchicago-cs/chiventure/wiki/Custom-Actions-~-Current-State-and-Future-Plan-of-Custom-Actions). 
It documents all of the existing structs, their functionality, and the plans we have for them. It is also contains a short roadmap of the modifications that need to be made in the near future for the integration of custom actions. 
Currently it references [pull request](https://github.com/uchicago-cs/chiventure/pull/802/) and [issue#796](https://github.com/uchicago-cs/chiventure/issues/796).  It will be updated as more issues are created.

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Great job! One area of improvement for future issues: Your issue did not include any status updates between the opening of the issue and the closing of the issue (and this issue was not small enough to justify having no status updates at all). If you make any intermediate progress before finishing the task, then it should be documented on the GitHub issue via a comment. In this case, for example, it would have been useful to note as you discovered things about custom actions and updated the wiki.
