### ISSUE TITLE
Write documentation for quests

### ISSUE THREAD

**Issue by zsp255** [uchicago-cs/chiventure#889]
Currently the quest.h and quest.c documentation is out of date and does not clearly explain the functionality of the code. We aim to improve this.

**Comment by gabigarc03** [comment]
Updated quests_structs.h with more accurate documentation in the quests/update-documentation branch that reflects what we learned from looking at the npc.h struct and that quests_structs.h now uses structs instead of unions.

**Comment by gabigarc03** [comment]
Updated quests_state.h with more accurate documentation in the quests/update-documentation branch that reflects what functions are actually doing and uses proper language (e.g. no longer refers to a quest marked "failed" as marked "started"). I had a couple questions come out of this - one, is `get_quest_status` absolutely necessary? All it does is `return quest->status`, which isn't really something that I feel needs to be in its own function. I also noticed a lot of pass-through variables, though they may be unavoidable due to the nature of this file. Finally, I noticed that, contrary to our earlier thoughts, the linked list implementation of achievements actually _does_ stipulate that achievements be completed in order, as `complete_achievement` only checks the _first_ incomplete achievement against the item and npc passed in.

**Comment by gabigarc03** [comment]
### Some thoughts for proceeding with trees:
- We're going to need to completely rethink how `complete_achievement` works, and we'll have to decide whether we want to use BFS or DFS on our tree
- We're going to need to figure out how adding achievements to a quest works (AKA: how do we specify exactly where we want to put a new achievement? Is there a way to identify a branch? A preceding item?)
- Do we want to simplify the code we've got at all, since it's a bit messy?
- Or do we just want to refactor with trees?

**Comment by oliviajerdee** [comment]
Added component descriptions for structures within the quest_structs.h file.

**Comment by oliviajerdee** [comment]
We met on Zoom earlier today and feel that we have probably added enough additional documentation to be able to close this issue. We will speak to Lily today and see if we are ready to pull.
