### ISSUE TITLE
Clarify instructions in the /battles/examples README

### ISSUE THREAD

**Issue by adinilfeld** [uchicago-cs/chiventure#892]
Currently, the README in ``/src/battle/examples/`` contains vague and arguably incorrect instructions for running the example files (as noted in Issue #839, in [this](https://github.com/uchicago-cs/chiventure/issues/839#issuecomment-827041434) comment). Specifically, the README doesn't specify which folder to run the commands from, and contains instructions for running an example (``battle_flow_example``) which doesn't seem to actually compile.

**Comment by adinilfeld** [comment]
So far, I've updated the instructions to be more detailed (especially concerning which directory each command should be run from). I also fixed a typo where the executables were listed with the `.c` extension. Next step is to figure out why the `battle_flow_example` file isn't building, and then update the README accordingly.

**Comment by adinilfeld** [comment]
After discussing with @lczielinski and @Elsa-Athiley, it seems like the `battle_flow_example` file is unfinished, and the CMake file hasn't been properly set up to compile it anyway. Fixing it seems out of the scope of this issue (I gave it a shot, but it seems non-trivial), so I'm removing it from README instructions (though keeping it as a note). 

Besides that, the README should now be much more clear.

**Comment by firatciftci** [comment]
Issue Score: ✔️

Comments:
Good work! I only have two things to comment on, which are regarding the summary and the closing statement:
- An issue should have the goal of producing something tangible, such as code or documentation, which must be specified in the summary.
- When an issue is done, you should include a final comment summarizing what was done, and why the issue is being closed.
