### ISSUE TITLE
Update .proto file

### ISSUE THREAD

**Issue by ellynliu** [uchicago-cs/chiventure#90]
Once game state has pushed to master, change/update our .proto file to reflect the new game state structs. These changes will break our current save and load.

We especially need to focus on which fields are repeated/optional, and how to save data structures that protobuf does not support (i.e hash tables, linked lists)

**Comment by jonahdf** [comment]
I updated the proto file to match the game state in master. 
My biggest changes were:
- Changed "objects" to items
- Added "attributes" and corresponding tags to items
- Added attributes to paths
- Added "length" members below any repeated member (array) to simplify loading
- Minor struct fixes to reflect changes in Game State

The biggest thing to look out for is the "condition" message that each Path contains. If I understand their code correctly, I believe Game State made an error in implementing these conditions, since they should be using the struct they created in their "items.h" file. I asked them about this on their slack channel, and I'm waiting for them to respond. In this proto file, I implemented it in the way I believe to be most logical (not how is currently is in master).

@jarvislam1999, I would appreciate if you can look over my changes and also take a look at Game State's paths.h to see if you agree with my interpretation of the "condition" struct.

**Comment by jarvislam1999** [comment]
Hi,

I rewrote some of your stuff to match with Master anyway (some of them are actually needed and not only a result of their faulty Condition struct). I was going to also text them in the morning but I see that you did that too so it's awesome! I can try to take it from here and figure out how to best understand Game state's intentions.

Cheers,
Jarvis

**Comment by jonahdf** [comment]
So after the meeting, we have decided that we do not need to serialize the conditions anyway, so our communications with GS didn't end up mattering. Christian and Ellyn also noticed some errors and requested some variable name changes in the PR, so Jarvis made those changes.

**Comment by jarvislam1999** [comment]
We also did more talking and we think it would be best for us to try to still serialize and deserialize the conditions and every other struct anyway so that we can still perform save and load even if the worst happens. Once we finish all of these tasks, then we can go back to the proto file, save and load and begin deleting the unnecessary structs. We should not do it or even work on the wdl part before we can make sure that everything works for saving. Let me know if you think this is a good idea.

**Comment by jonahdf** [comment]
I did some talking with Jarvis and Sheryl, and we believe the best course of action for the conditions is to save/load them (and include them in the proto file), and then after everything works in dev, we branch off (to save our work), and delete the conditions for the merge to master. This way, we can access our functions just in case, but since we agreed at the team meeting that we could extract the conditions from WDL each time, we can work to integrate that feature.

**Comment by jarvislam1999** [comment]
I agree with Jonah, I have edited the code in save.h to reflect your comment and merged it to checkpointing/dev. Now all you need to do is to begin compiling it, fix errors, run tests, and we need to merge them to master. I edited the game.proto to reflect this as well, commenting out Condition and expected_attribute so that our code compiles smoothly. There may be changes in the future but I think this should somewhat be our final state of the game.proto file for now.

**Comment by jonahdf** [comment]
I have branched off the proto file that includes all conditions and called it checkpointing/dump-it-all.
Since this game.proto has been reviewed enough times, we are going to close this issue.

All optional fields should be optional, and each name matches the variable name in game-state. Jarvis has successfully saved all repeated fields in save.c by using Game State's iterators, and we are working on loading them.

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
