### ISSUE TITLE
Implement the Load Sound Module

### ISSUE THREAD

**Issue by vivianwu00** [uchicago-cs/chiventure#912]
We will begin the implementation of the Load Sound module. We will need to familiarize ourselves with ut_hasttable because we envision using a hash table to store different sound structs. The goal is to implement the functions that are currently on our Load Module in the sound design [wiki](https://github.com/uchicago-cs/chiventure/wiki/Sound-Module-Design-Document).

**Comment by vivianwu00** [comment]
Documenting progress on creating the load sound function within our module:
EC recommends referencing /chiventure/src/game-state and cli for usage of hash_find() function variants

**Comment by vivianwu00** [comment]
Added load_sound module .c and .h files. Free_sound() has been implementation, still working on load_sound()

**Comment by vivianwu00** [comment]
Conducting research on loading a sound file through SDL_mixer package from libsdl: Need a function, SDL
https://wiki.libsdl.org/SDL_LoadWAV
   // Load audio files
    Mix_Music *example1 = Mix_LoadMUS("example1.mp3");
    Mix_Chunk *example2 = Mix_LoadWAV("example2.wav");

**Comment by gypark23** [comment]
After the team meeting, this issue had been moved to Sprint 4

**Comment by gypark23** [comment]
Currently, the load function had been created, however with many compile errors. We look forward to edit these errors and check if the functions work properly by the end of Sprint 4

**Comment by gypark23** [comment]
Due to lack of time, we were unable to implement compilable load functions as it contains many compiler errors. I have left my work in comment block, so next team could review my code and improve them, while maintaining the current code compilable for pull request.

**Comment by jiguba** [comment]
Additionally, after team discussion, we concluded that there was no need for a separate play sound and load sound module because the play and load functions of audio are primarily intertwined so there is no need to separate them. We have consolidated the load and play functions into a singular sound module with the primary functions being load and play sound.

**Comment by jiguba** [comment]
We are closing this issue because the load sound module is being combined with the play sound module to create a singular sound module. We created demo implementations of load and play sound modules by using the external data structures and functions from the SDL library. Kyu submitted a pull request to review our current implementation of the sound module.

**Comment by gypark23** [comment]
To separate working code and developing code, two separate branches of sound were made, sound/dev and sound/inprogress. sound/dev contains a skeleton function for load, and sound/dev has implementation that needs to be improved.

**Comment by gypark23** [comment]
Closing statement:

This issue is closed since a pull-request with load implementation had ben submitted. The initial goal was to implement load sound functions. Currently, there are only skeleton functions for load implementation in sound/dev branch and incomplete implementation in sound/inprogress branch. The future sound could build up on this issue and finish the functioning implementation of load sound function.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Nice work on this issue, even though you weren't able to fully implement everything you did a great job adapting and separating out work in progress code!
