### ISSUE TITLE
Create a design document for further enhancement of npc/battle integration

### ISSUE THREAD

**Issue by amymorrill** [uchicago-cs/chiventure#920]
We have figured out a basic way to integrate the npc and battle modules (see #883). Now, we want to brainstorm more complex ways in which npcs and battles can be integrated. 

One idea that we have briefly discussed and want to think more about is having npcs drop their items after death, which the player can then choose to pick up. We also, more generally, want to discuss how to deal with npcs that have died in battle. We will expand on these ideas—and come up with other ones—during this sprint.

**Comment by northofsophia** [comment]
We have updated the Wiki "RPG NPC Dependencies: Player class, Open world, Battle" where we discussed possibilities of how to include appropriate levels of NPCs the player can battle, plans to possibly implement looting of dead bodies, and allowing for multiple battles with the same NPC. Going forward, we will discuss with the CLI team about if its possible to print out a list of the NPC's items. We will also be adding change functions to various npc_battle members in order to implement allowing multiple battles with the same NPC.

**Comment by northofsophia** [comment]
After reading the [wiki](https://github.com/uchicago-cs/chiventure/wiki/NPC:-Player-Interaction-Design-and-Planning) about npc-player interactions by team-npc2, I talked to them to see if their implementation of the actions such as TAKE would be done by the end of the sprint as that would aid us in our implementation of looting dead npc bodies. They said that it would take a little longer to fully implement, so instead we will use the method of transferring all npc items to the room struct where the player can then take items from. We will now move forward in implementing looting dead bodies using this method.

**Comment by northofsophia** [comment]
We have begun integration of looting dead bodies through the method of transferring all npc items to the room struct so that the player may loot from the room items after npc deaths. We have also begun adding multiple new npc_battle functions that aim to help other teams working with npcs and retrieving various npc information.

**Comment by lilyehsani** [comment]
Issue Score: ✔️++

Comments:
Great work overall! Great job opening this issue on the first day of the sprint.
