### ISSUE TITLE
Write Unit Tests for functions in mode module

### ISSUE THREAD

**Issue by pkasner** [uchicago-cs/chiventure#921]
The functions in game-state/mode.h currently do not have unit tests, so I will write unit tests for them.
Assignees: Peter
team:npc2

**Comment by pkasner** [comment]
Wrote unit tests for init/new/free functions, and load_normal_mode() 5dd78077bc3028f24faedda9962d163a5823278f

**Comment by lilyehsani** [comment]
Issue Score: ✔️+

Comments:
Great work overall! One comment:
- The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies.html#tasks-issues for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
