### ISSUE TITLE
Save: update transfer functions (for hash table structs)

### ISSUE THREAD

**Issue by ellynliu** [uchicago-cs/chiventure#93]
Along with issue #92, write implementation in save.c to pack anything that used to be a hash table. This will need to call the functions that game state will provide. 

Update: write functions to iterate through hashtable in game structs and load that into our serializable arrays

**Comment by jarvislam1999** [comment]
Hi everyone, I finished all of the hashtable function, which made our save function officially complete! There will probably still be a lot of bugs and even without bugs we may not be able to run this function. So the next step should be:

- @jonahdf Could you look through my codes and spot if there are any errors. There should be a lot. Please try to see if Ellyn's code have any bugs as well. If the code can compile aside from the Condition stuff which we are likely to comment out, that would be great
- The rest of the team @jonahdf @chrisfernandes18 @ellynliu @schin99 Time to write the test function for save! I'm unsure how to go about this, but there must be functions from game state that can help you write a game and test our functions

I believe even though this task is finished, we should leave it open since we may have to comment out/ delete stuff once we figure out what will be immutable for WDL. This means that people from the other save task which was closed may still have to work on this in the future.

**Comment by jarvislam1999** [comment]
Update: I have edited the code according to others' reviews and merged the code to checkpointing/dev. The next step is for others to write the Makefile so that we can begin to try to compile the code and then run them through tests. This task, however, belongs to a different issue and updates should not be posted here.

**Comment by jarvislam1999** [comment]
More updates:

We have finished all communications and are happy with current version of save.c. We will go ahead and close this issue soon. A few notes on what's happening:

- save.c will no longer store Condition structs since they are immutable. However, we may end up still saving paths because it may be the case where a path can be added to a room during the game or that the path destination is still mutable. Everything else stays the same, as item, room, players are all mutable objects.
- As failsafe, we did write the code for Condition anyway. This will be pushed into a separate branch, and the code in dev for condition will be deleted for merging into master. 
- The test functions for save are almost finished and we will test them soon. However, the save interface has been successfully delivered to CLI for usage.

**Comment by jarvislam1999** [comment]
Closing statement: I believe this is a good time to close this issue. The only other stuff to be fixed on is to review the code, delete the comments and push them to master. 

In short, aside from debugging purposes, which I feel is an issue for #96 , our save function is complete. Please read above for updates on what's new during this process.

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
