### ISSUE TITLE
Integrate default object functions with example battle code

### ISSUE THREAD

**Issue by sonnykaiyuenlee** [uchicago-cs/chiventure#930]
There is currently no way to call default objects such as items or moves in the battle. Our plan is to use calls to default object functions (items, moves, stats) in example battle code to show how functions work in the battle setting. 

team: battles
assignees: Sonny and Laura

**Comment by lczielinski** [comment]
After reviewing the battle_command_example code, we found places where we could integrate our default functions. However, we also realized that the code creates player classes for the player and the enemy, which then calls a function from the playerclass code (class-list.c) to assign a default move to each. We will communicate with the playerclass team to find out if their hard-coded classes are also default classes, and if so, integrate their code to call our default move functions.

**Comment by lczielinski** [comment]
After discussing with the playerclass team, we found out that they are working on default classes that would come with default moves. We will continue to integrate these default moves with them once they are farther along on their code. For now, we are working on integrating default stats and items with the example, and editing the default item function to return stat-improving items, since that is the functionality that was recently added to our code.

**Comment by lczielinski** [comment]
To summarize this issue, we worked on integrating our default item and stat functions into the example code for battles. We decided not to use our default move function until we communicate more with the playerclass team. We also added a function in battle_default_objects that would return a random consumable that could then be used in battle, and distinguished between consumables and weapons, and will further work on implementing weapon use into battles. We then used the random consumable and stat functions in the example battle code, so each time the example battle is run, the player and enemy have random stats and the player has a random consumable they can use.

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good job! I only have one thing to comment on:
- The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies.html#tasks-issues for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
