### ISSUE TITLE
Implement DSL grammar in code

### ISSUE THREAD

**Issue by jacknugent1529** [uchicago-cs/chiventure#931]
Our goal is to create a lark grammar file which describes the dsl language. This will occur after creating a document with the language specifications. As a result of this, lark will be able to parse the dsl into a parsing tree, which will later be transformed into the desired output.

Assignees: Jack and Tessie
team: dsl

**Comment by r-e-stern** [comment]
We've defined the DSL grammar for its initial iteration in #937, and it should now be convert-able to a Lark grammar.

**Comment by tessied** [comment]
We had a meeting where we discussed the current implementation of the DSL grammar. We brought up a few issues that we hope to discuss with the whole team:
- Newline-agnosticism is tricky to implement. We proposed that having a new line for each declaration might not be a bad idea as it increases readability and writability for the author as well. 
- The end condition is not necessarily the room in which the player ends the game, as Jack mentioned above. Therefore, we may need to modify the way in which we define a game at the top to accommodate the various end conditions we may be given.

Currently, we have all the basic features outlined in the DSL design guide. I will now attempt to add actions to the grammar.

**Comment by tessied** [comment]
I've implemented the "actions" feature to the dsl grammar (commit [a0e8382](a0e83823147555d76fe15a6c626d4f2328f5b6bf)). I also added a short example dsl file to test the new actions feature. However, actions currently need to be defined separately. For example, if one wants to specify the actions `TAKE` and `EAT`, they will have to define two actions: `action: TAKE` and `action: EAT` and specify the conditions, success and failure outcomes separately for each action. We will figure out how to fix the implementation to support `actions: TAKE, EAT` and take into account the conditions that follow each of the actions.

In addition, I am currently only able to run the tree that lark produces. I will add to dsl_parser.py so that we can have actions in the python dictionary output.

**Comment by jacknugent1529** [comment]
When adding newlines, we have run into several problems with defining our grammar. Specifically, many of our keywords such as `ROOM` or `ITEM` would also be considered phrases. We initially used the lalr(1) parser which can look ahead for 1 token. Once newlines are added, this look-ahead is less powerful, and the lalr parser reaches errors. The earley parser that lark provides is more powerful, and avoids this issue. While it is slightly slower, based on lark's [JSON tutorial](https://lark-parser.readthedocs.io/en/latest/json_tutorial.html), this should not be an issue until the files become 10s or 100s of megabytes in size. Given that the current size of the files is only a few kilobytes, this should not be an issue in the foreseeable future. Therefore, we switched to the earley parser (commit af8fc49)

**Comment by tessied** [comment]
The pull request linked to this issue reflects the work done for this issue — the implementation of the DSL grammar file in code. Pull request has been merged, closing the issue.

**Comment by tessied** [comment]
The pull request linked to this issue reflects the work done for this issue — the implementation of the DSL grammar file in code. Pull request has been merged, closing the issue.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Excellent work! The parser is looking great, and the documentation on this issue is really great as well!
