### ISSUE TITLE
Basic implementation of DSL to "intermediate stage"

### ISSUE THREAD

**Issue by r-e-stern** [uchicago-cs/chiventure#938]
Implement a function or functions in Python that takes output from the DSL parser and converts it into an internal Python representation that can later be converted into JSON.

**Comment by r-e-stern** [comment]
@jacknugent1529 and I have finished (commits [`1d6dc3cb`](https://github.com/uchicago-cs/chiventure/commit/1d6dc3cbcaf77f9bc6155985429d75d69b9f05a7) through [`187a0c18a3`](https://github.com/uchicago-cs/chiventure/commit/187a0c18a30117429008baf9aaf52b1d77083f40)) one full draft of a Python script that can successfully transpile DSL to the WDL JSON format. It features a [`to_wdl.py`](https://github.com/uchicago-cs/chiventure/blob/dsl/to-wdl/src/dsl/src/to_wdl.py) file dedicated to helper functions that format rooms, items, and games correctly in JSON, and a [`main.py`](https://github.com/uchicago-cs/chiventure/blob/dsl/to-wdl/src/dsl/src/main.py) file that parses a DSL file and calls `to-wdl.py` to convert it to WDL.

We've tested `main.py` on both examples in the `examples` directory; the output from these files lives in the new [`wdl`](https://github.com/uchicago-cs/chiventure/tree/dsl/to-wdl/src/dsl/wdl) directory. We've also written a new example ([`long-example.dsl`](https://github.com/uchicago-cs/chiventure/blob/dsl/to-wdl/src/dsl/examples/long-example.dsl)) designed to use the intended features of the final version of `to-wdl.py`.

Next steps: fleshing out the empty `<Class>.generate_defaults()` methods to allow the parser to interpolate incomplete long and short description information where it is missing.

**Comment by Mich0608** [comment]
I have implemented basic default generation for the Room and Item short/long descriptions and the Game intro (commit 0bc5ca2a3ec85e9424e212a37bca37bea71ef56b). Depending on how many properties the game author provides, the automatically generated descriptions/intro will be of varying complexity.

For example, if the game author specifies the short description but not the long description, the long description will be automatically generated to `"This is a <room id, or if no room id, simply "room">. <short description>"`. If the game author doesn't specify any descriptions, the short description will be `"<room id or "room">"` and the long description will be "This is a <room id>".

In the future, we could discuss whether we want to include items in self-generated room descriptions, or if there are more creative ways to use specified properties to generate default properties.

**Comment by r-e-stern** [comment]
To do:
- [ ] Handle items without actions, rooms without connections, rooms without items

**Comment by jacknugent1529** [comment]
In recent commits (including 0ae3b97 and da37559) I allowed the dsl-to-wdl stage to include arbitrary properties in the final wdl file. The function first replaces common aliases for `short_desc` and other common properties with the name that will be recognized by chiventure. Then the rest of the properties are included for future flexibility, even if chiventure won't recognize them now.

At this point, we can transform dsl into valid wdl effectively. Currently, our grammar provides more flexibility than chiventure can handle. For example, items must be capitalized in chiventure, and actions can only take on specific values. Since the features of chiventure may expand in the future, we do not intend to restrict our language to chiventure's specifications, but we will try to align with them. Currently, we warn users when item names are not uppercase, and we transform them to uppercase. As we come across them, we will add similar warnings for other peculiarities of chiventure.

**Comment by r-e-stern** [comment]
In preparation for a pull request, we [merged](https://github.com/uchicago-cs/chiventure/commit/1b3d896abc1f25a56909f050bb4d11c86f59c6ba) the `dsl/vars` branch into this one, meaning it should now be able to handle variables. We'll update the examples to showcase this. We'll also rearrange the file structure somewhat, in order to group like files (`.py`, `.lark`, `.dsl`, `.wdl`) with like.

**Comment by r-e-stern** [comment]
Closing the issue — the features written for this issue were merged into `dev` as part of PR #1118. `dev` now contains most of the code we've written this year, and is able to fully convert a `.dsl` file to a `.wdl` version that can (usually) be run in Chiventure, with variable evaluation and default parameters to boot.

**Comment by ecoble** [comment]
Issue Score: ✔️++

Comments:
Excellent work on this implementation, and great documentation and progress updates as well!
