### ISSUE TITLE
Design and implement damage based skill effects into the effect module

### ISSUE THREAD

**Issue by tgao564** [uchicago-cs/chiventure#953]
Implementation for different effects that are currently supported by chiventure (damage, statistic modification and attribute modification) is in progress of development, and each effect implementation has to be designed separately.

Attribute modifying skills will most likely require communicating with game state, action management and player class teams.

**Comment by tgao564** [comment]
After looking through the rpg battles code I've determined that it might better for the skill to implement a move instead of simply dealing damage. Have set up a meeting with two rpg battles team members to discuss the best ways to integrate skills with battle.

**Comment by tgao564** [comment]
Updated damage structures and functions in effect.h and effect.c to moves in order to allow for move implementation.

**Comment by tgao564** [comment]
- Implemented define, make, and execute move functions
- Updated inventory struct to no longer use a linked list of effect_t
- Execute move function uses function add_move in include/battle/battle_move_maker.h which is still in a pending pull request from battles

**Comment by tgao564** [comment]
Had a call with @rohangupta2806 where we discussed implementing moves skills based on future battles integration instead of their current unintegrated form. We decided this proactive approach is good and will better improve Chiventure in the long run.

-  Refactored the execute_move function to no longer add all move-based skills in the inventory to the battles combatant struct and instead the function adds one move-based skill to the ctx player struct. 
- The function refers to a moves list in the ctx player struct which doesn't yet exist
- Reached out to battles about integrating their combatant stuct that contains the moves list into the ctx player struct

**Comment by tgao564** [comment]
- Refactored the move effect struct and the define_move_effect function
- Added tests for the define and make move effect function
- Execute skill function doesn't have tests yet as it is waiting on future implementation
- Waiting on battles to fix some code before pull request for effects can go through(will link when submitted)

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Great work on this! The updates that you have provided give a really detailed overview of your work. I only have one thing to comment on:
- The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies.html#tasks-issues for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
