### ISSUE TITLE
Save: write tests

### ISSUE THREAD

**Issue by ellynliu** [uchicago-cs/chiventure#97]
Write tests for each of the transfer functions in save.c. Also write tests for the higher level save function written in issue #96. More elaboration coming

**Comment by chrisfernandes18** [comment]
We are going to use the criterion library to help us create tests to see if the functions we make to serialize the game state structs and put the serialized structs into a file function correctly. We are going to test each on of the smaller functions as well as the higher-level, overall save function which uses all of the smaller functions.

**Comment by schin99** [comment]
Mostly finished with test_save.c. Only problem is with saving attributes and saving repeated structs since save.c is not quite finished. Found some problems with player struct and discussed with game-state. More specifically, game-state's player struct function does not init a player id.

**Comment by jarvislam1999** [comment]
Hi guys, saving is finished and pushed to checkpointing/dev. Also, we should comment out any Condition testing within Path (since save.c no longer store Condition inside a Path). Keep the Condition struct though. In addition, we should comment out the expected_attribute within the Condition struct since game-state haven't pushed it master so their Condition structs do not make sense.

**Comment by chrisfernandes18** [comment]
I just wholly got rid of both the path and condition tests until we have further elaboration on whether we need them or not. Other than that, we have all of the other tests for the other functions. The only test we do not have is one for the higher level save function, but that is coming soon. The only other note would be that we are using functions in some of the tests from the GAME-STATE.md in docs to create some examples to assert they were saved or not. However, as of right now those functions have not been created yet, but hopefully will be within the next PR to Master from game-state.

**Comment by schin99** [comment]
The save_tests.c is complete and compiles. The only problem we run into is the iterator macros from game-state in save.c. If we disregard the iterators, the tests all pass. We are pretty sure the problem lies in the iterators since we have a counter in one of the iterators and it returns 0 when we know that there is at least one item in the data structure. This suggests the iterator doesn't even go through the data structure and run the rest of the code we have in the iterator. However, we've talked to game-state and the macro might change to a function that returns a linked list of the items in the data structure.

**Comment by mpcsh** [comment]
Issue Score: ✓+

Comments:
Great work!
