### ISSUE TITLE
Write documentation about the effect.c and effect.h file

### ISSUE THREAD

**Issue by rohangupta2806** [uchicago-cs/chiventure#972]
These files have been newly implemented and there is no documentation that explains what has been done and what should be done in the future.  We should create a wiki page detailing the current status of these files and upcoming changes to them so that future teams can continue to work on these files.

**Comment by rohangupta2806** [comment]
Wrote a wiki page that describes the different effect types and what we plan to do with them, and gave a rough date for their implementation as well.  Link is here: https://github.com/uchicago-cs/chiventure/wiki/Skilltree-%22effect%22-implementation-and-roadmap

**Comment by firatciftci** [comment]
Issue Score: ✔️+

Comments:
Good work! I only have two things to comment on:
- Even though you can add labels to issues to categorize them, you should avoid titles that could plausibly apply to multiple teams
- The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies.html#tasks-issues for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
