### ISSUE TITLE
Integrating CLI into the GUI Splitscreen

### ISSUE THREAD

**Issue by xWngl** [uchicago-cs/chiventure#975]
Work with the new gui.c to set up the command line in the split screen. This should give full chiventure functionality to the CLI portion of the gui.

**Comment by xWngl** [comment]
Including draw_images.h changes the constants for KEY_BACKSPACE and KEY_ENTER from raylib in gui.c. Removing this include statement fixes the issue and causes gui.c to run with intended behavior

**Comment by MaxineK36** [comment]
Issue Score: ✔️+

Comments:
Great work overall! Here are a few things you may want to improve in future issues:
- The summary for this issue is too terse. A good rule of thumb is that you should be writing at least one full paragraph in your summary (see https://uchicago-cs.github.io/cmsc22000/project/policies.html#tasks-issues for examples). If this issue was generated from a Scrum board card, please remember that the summary you write in the Sprint meeting is meant to be a quick draft; it needs to be fleshed out when you convert the card to an issue.
- For a task of this size, we would've expected to see more status updates and/or status updates that were more detailed. For example, it would have been helpful to describe the backspace-failing bug when you first discovered it, and then update once you figure out the problem.
