### ISSUE TITLE
Support incremental game save

### ISSUE THREAD

**Issue by ellynliu** [uchicago-cs/chiventure#99]
No code is necessary for this task, but think about how to go about saving incrementally. It appears we will approach storing the command lines and then run them one by one. This requires intensive communication with CLI and action management to get their structs and save data, as well as making their engine run all of our commands once loaded. Basically, start communicating with CLI and action management soon.

**Comment by borjasotomayor** [comment]
Since this is a very high-level task, this feels more like a Backlog task. I think having incremental saving done by the end of the 3rd sprint is going to be too ambitious, given all the other things you'll have to focus on. At the start of Sprint 4, we can decide whether we actually want to commit to doing this.

Please note that placing a task on the Backlog doesn't preclude having a discussion about it. It just means you're not committing to doing it in this sprint.

Minor nit: A better title for this issue would be "Support incremental game saves"

**Comment by jarvislam1999** [comment]
I agree that supporting incremental game save is an issue that should not be done in Sprint 3. However, I feel like we should still communicate with command line interface and action management in order to understand how they operate. This is beneficial in the long run because:
- At one point we want command line to be able to call our function when users type in save, so we should talk to them about that. In addition, we need to have our function be called where the Game struct is at, thus we need action management.
- If we ever support incremental game save, understanding CLI is essential because we need to access a list of commands to save, and when we load we need them to run those exact list of commands.

Hence, I will make a new issue which would focus on communicating and understanding how CLI and action management work. Please let me know if this is a good idea.

**Comment by borjasotomayor** [comment]
@jarvislam1999: I don't think a new issue is needed. This issue can serve as a focal point to discuss this feature until the issue becomes enough of a priority that it gets assigned to a specific sprint (maybe Sprint 4, maybe a future sprint in a future offering of the class)

Also, at this point we should avoid tasks of the form "communicate with...", "understand how...", etc. Sprint 3/4 tasks should be finer-grained tasks with specific outcomes (and this could, of course, involve communicating with CLI and Game State).

**Comment by jarvislam1999** [comment]
Understood. In that case, I may just post any communication results with CLI and action management here then.

**Comment by ellynliu** [comment]
A long overdue comment, but we have since decided to use a method of "semi-incremental" saving instead of full incremental saving. This semi-incremental approach currently only saves the mutable aspects of a game. The immutable aspects such as path, attribute of item, and attribute value will not change, and so do not need to be saved. By first loading in WDL and then calling our load function, we will load over an existing game struct and write over the appropriate fields with changes.

**Comment by jonahdf** [comment]
We also implemented the beginning stages of incremental saving as described in #229. I am closing this issue since the class is over, but future work should expand and test our unused logging feature.
