### ISSUE TITLE
Implement the looting of dead NPC bodies according to issue #920

### ISSUE THREAD

**Issue by northofsophia** [uchicago-cs/chiventure#992]
We have decided on the method in which to integrate the looting of dead npc bodies after a battle has been won (see #920). After an npc dies, all of their items will be removed from the npc and placed into the room struct, where the player can then directly take whatever items they want. We will now begin implementation using this strategy.

**Comment by lilyehsani** [comment]
Issue Score: ✔️+

Comments:
Great work overall! I have one comment:
- Your issue did not include any status updates between the opening of the issue and the closing of the issue (and this issue was not small enough to justify having no status updates at all). If you make any intermediate progress before finishing the task, then it should be documented on the GitHub issue via a comment. This could include things like when the branch was opened, what was added to it, when the PR was opened, etc.
